// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_0, 						ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\0.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_01, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\01.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_02, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\02.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_03, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\03.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_04, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\04.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_05, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\05.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_06, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\06.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_07, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\07.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_08, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\08.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_09, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\09.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_100, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\100.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ANGEL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ANGEL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_APOLLO, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\APOLLO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ARCHER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ARCHER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_01, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_01.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_02, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_02.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_03, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_03.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_04, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_04.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_05, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_05.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_06, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_06.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_07, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_07.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_08, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_08.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_09, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_09.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_10, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_10.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_11, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_11.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_12, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\ATC_12.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BANSHEE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\BANSHEE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BEARING, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\BEARING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BLOODHOU, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\BLOODHOU.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BULLDOG, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\BULLDOG.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHARGER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\CHARGER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHEETAH, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\CHEETAH.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHIEFTAI, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\CHIEFTAI.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COBRA, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\COBRA.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COMET, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\COMET.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CONDOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\CONDOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COUGAR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\COUGAR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COWBOY, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\COWBOY.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DARKHORS, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\DARKHORS.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DEMON, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\DEMON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DODGER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\DODGER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DRAGON, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\DRAGON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_EAGLE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\EAGLE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_EIGHTBAL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\EIGHTBAL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FARSIGHT, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\FARSIGHT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREBALL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\FIREBALL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREBIRD, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\FIREBIRD.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREFOX, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\FIREFOX.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FREELANC, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\FREELANC.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GATOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\GATOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GAUNTLET, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\GAUNTLET.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GHOSTRID, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\GHOSTRID.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GLADIATO, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\GLADIATO.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GOLIATH, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\GOLIATH.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GOOSE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\GOOSE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HAWKEYE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\HAWKEYE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HELLCAT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\HELLCAT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HUNTER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\HUNTER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JAGUAR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\JAGUAR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JESTER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\JESTER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JUGGERNA, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\JUGGERNA.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JUPITER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\JUPITER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KESTREL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\KESTREL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KNOT, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\KNOT.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KNOTS, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\KNOTS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_LANCER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\LANCER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_LIMA, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\LIMA.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MANIAC, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MANIAC.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MANTIS, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MANTIS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MAULER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MAULER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MERCURY, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MERCURY.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MERLIN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MERLIN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MILKMAN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MILKMAN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MUSTANG, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\MUSTANG.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_NIGHTMAR, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\NIGHTMAR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PANTHER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\PANTHER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PATRIOT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\PATRIOT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PHANTOM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\PHANTOM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PHOENIX, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\PHOENIX.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PREACHER, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\PREACHER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PYTHON, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\PYTHON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RANGE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\RANGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAPTOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\RAPTOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RATTLESN, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\RATTLESN.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAZORBAC, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\RAZORBAC.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAZORWOR, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\RAZORWOR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_REAPER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\REAPER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RENEGADE, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\RENEGADE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SABRE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SABRE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SAVAGE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SAVAGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHADOW, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SHADOW.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHERIFF, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SHERIFF.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHOGUN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SHOGUN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SNOWBALL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SNOWBALL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPARTACU, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SPARTACU.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPECTRUM, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SPECTRUM.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPEED, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SPEED.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STALKER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\STALKER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STINGRAY, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\STINGRAY.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STRIKER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\STRIKER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SUNDOWN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SUNDOWN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SWAMPFOX, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\SWAMPFOX.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TEMPEST, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\TEMPEST.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TIGERSHA, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\TIGERSHA.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TOUCHDOW, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\TOUCHDOW.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VAMPIRE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VAMPIRE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VERTIGO, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VERTIGO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIGILANT, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VIGILANT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIKING, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VIKING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIPER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VIPER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VOODOO, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VOODOO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VULCAN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VULCAN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VULTURE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\VULTURE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARLOCK, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\WARLOCK.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARLORD, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\WARLORD.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARRIOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\WARRIOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WILDCAT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\WILDCAT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WOLFPACK, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\ATC\\WOLFPACK.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_0,						ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\0.PCM",					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_01,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\01.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_02,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\02.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_03,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\03.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_04,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\04.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_05,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\05.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_06,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\06.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_07,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\07.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_08,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\08.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_09,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\09.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_100,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\100.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ANGEL,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ANGEL.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_APOLLO,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\APOLLO.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ARCHER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ARCHER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_01,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_01.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_02,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_02.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_03,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_03.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_04,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_04.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_05,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_05.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_06,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_06.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_07,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_07.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_08,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_08.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_09,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_09.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_10,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_10.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_11,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_11.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_12,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\ATC_12.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BANSHEE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\BANSHEE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BEARING,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\BEARING.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BLOODHOU,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\BLOODHOU.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BULLDOG,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\BULLDOG.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHARGER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\CHARGER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHEETAH,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\CHEETAH.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHIEFTAI,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\CHIEFTAI.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COBRA,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\COBRA.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COMET,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\COMET.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CONDOR,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\CONDOR.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COUGAR,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\COUGAR.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COWBOY,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\COWBOY.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DARKHORS,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\DARKHORS.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DEMON,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\DEMON.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DODGER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\DODGER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DRAGON,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\DRAGON.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_EAGLE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\EAGLE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_EIGHTBAL,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\EIGHTBAL.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FARSIGHT,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\FARSIGHT.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREBALL,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\FIREBALL.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREBIRD,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\FIREBIRD.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREFOX,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\FIREFOX.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FREELANC,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\FREELANC.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GATOR,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\GATOR.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GAUNTLET,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\GAUNTLET.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GHOSTRID,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\GHOSTRID.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GLADIATO,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\GLADIATO.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GOLIATH,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\GOLIATH.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GOOSE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\GOOSE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HAWKEYE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\HAWKEYE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HELLCAT,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\HELLCAT.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HUNTER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\HUNTER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JAGUAR,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\JAGUAR.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JESTER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\JESTER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JUGGERNA,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\JUGGERNA.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JUPITER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\JUPITER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KESTREL,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\KESTREL.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KNOT,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\KNOT.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KNOTS,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\KNOTS.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_LANCER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\LANCER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_LIMA,					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\LIMA.PCM",				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MANIAC,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MANIAC.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MANTIS,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MANTIS.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MAULER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MAULER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MERCURY,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MERCURY.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MERLIN,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MERLIN.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MILKMAN,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MILKMAN.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MUSTANG,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\MUSTANG.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_NIGHTMAR,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\NIGHTMAR.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PANTHER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\PANTHER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PATRIOT,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\PATRIOT.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PHANTOM,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\PHANTOM.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PHOENIX,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\PHOENIX.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PREACHER,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\PREACHER.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PYTHON,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\PYTHON.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RANGE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\RANGE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAPTOR,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\RAPTOR.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RATTLESN,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\RATTLESN.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAZORBAC,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\RAZORBAC.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAZORWOR,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\RAZORWOR.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_REAPER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\REAPER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RENEGADE,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\RENEGADE.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SABRE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SABRE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SAVAGE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SAVAGE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHADOW,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SHADOW.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHERIFF,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SHERIFF.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHOGUN,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SHOGUN.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SNOWBALL,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SNOWBALL.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPARTACU,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SPARTACU.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPECTRUM,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SPECTRUM.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPEED,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SPEED.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STALKER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\STALKER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STINGRAY,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\STINGRAY.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STRIKER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\STRIKER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SUNDOWN,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SUNDOWN.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SWAMPFOX,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\SWAMPFOX.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TEMPEST,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\TEMPEST.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TIGERSHA,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\TIGERSHA.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TOUCHDOW,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\TOUCHDOW.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VAMPIRE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VAMPIRE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VERTIGO,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VERTIGO.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIGILANT,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VIGILANT.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIKING,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VIKING.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIPER,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VIPER.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VOODOO,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VOODOO.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VULCAN,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VULCAN.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VULTURE,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\VULTURE.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARLOCK,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\WARLOCK.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARLORD,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\WARLORD.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARRIOR,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\WARRIOR.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WILDCAT,				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\WILDCAT.PCM",			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WOLFPACK,			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\ATC\\WOLFPACK.PCM",		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


