// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_0,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_01,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_02,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_03,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_04,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_05,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_06,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_07,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_08,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_09,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_100,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ANGEL,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_APOLLO,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ARCHER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_01,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_02,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_03,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_04,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_05,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_06,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_07,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_08,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_09,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_10,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_11,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ATC_12,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BANSHEE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BEARING,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BLOODHOU,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BULLDOG,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHARGER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHEETAH,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHIEFTAI,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COBRA,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COMET,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CONDOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COUGAR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COWBOY,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DARKHORS,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DEMON,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DODGER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DRAGON,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_EAGLE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_EIGHTBAL,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FARSIGHT,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREBALL,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREBIRD,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREFOX,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FREELANC,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GATOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GAUNTLET,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GHOSTRID,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GLADIATO,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GOLIATH,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GOOSE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HAWKEYE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HELLCAT,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HUNTER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JAGUAR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JESTER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JUGGERNA,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JUPITER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KESTREL,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KNOT,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KNOTS,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_LANCER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_LIMA,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MANIAC,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MANTIS,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MAULER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MERCURY,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MERLIN,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MILKMAN,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MUSTANG,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_NIGHTMAR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PANTHER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PATRIOT,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PHANTOM,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PHOENIX,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PREACHER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PYTHON,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RANGE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAPTOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RATTLESN,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAZORBAC,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAZORWOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_REAPER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RENEGADE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SABRE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SAVAGE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHADOW,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHERIFF,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHOGUN,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SNOWBALL,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPARTACU,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPECTRUM,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPEED,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STALKER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STINGRAY,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STRIKER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SUNDOWN,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SWAMPFOX,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TEMPEST,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TIGERSHA,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TOUCHDOW,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VAMPIRE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VERTIGO,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIGILANT,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIKING,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIPER,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VOODOO,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VULCAN,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VULTURE,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARLOCK,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARLORD,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARRIOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WILDCAT,
	SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WOLFPACK,

	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_0,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_01,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_02,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_03,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_04,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_05,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_06,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_07,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_08,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_09,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_100,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ANGEL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_APOLLO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ARCHER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_01,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_02,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_03,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_04,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_05,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_06,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_07,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_08,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_09,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_10,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_11,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ATC_12,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BANSHEE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BEARING,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BLOODHOU,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BULLDOG,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHARGER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHEETAH,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHIEFTAI,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COBRA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COMET,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CONDOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COUGAR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COWBOY,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DARKHORS,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DEMON,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DODGER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DRAGON,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_EAGLE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_EIGHTBAL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FARSIGHT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREBALL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREBIRD,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREFOX,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FREELANC,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GATOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GAUNTLET,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GHOSTRID,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GLADIATO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GOLIATH,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GOOSE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HAWKEYE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HELLCAT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HUNTER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JAGUAR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JESTER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JUGGERNA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JUPITER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KESTREL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KNOT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KNOTS,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_LANCER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_LIMA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MANIAC,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MANTIS,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MAULER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MERCURY,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MERLIN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MILKMAN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MUSTANG,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_NIGHTMAR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PANTHER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PATRIOT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PHANTOM,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PHOENIX,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PREACHER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PYTHON,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RANGE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAPTOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RATTLESN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAZORBAC,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAZORWOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_REAPER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RENEGADE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SABRE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SAVAGE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHADOW,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHERIFF,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHOGUN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SNOWBALL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPARTACU,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPECTRUM,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPEED,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STALKER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STINGRAY,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STRIKER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SUNDOWN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SWAMPFOX,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TEMPEST,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TIGERSHA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TOUCHDOW,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VAMPIRE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VERTIGO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIGILANT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIKING,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIPER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VOODOO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VULCAN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VULTURE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARLOCK,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARLORD,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARRIOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WILDCAT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WOLFPACK,

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


