// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_0,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_01,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_02,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_03,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_04,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_05,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_06,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_07,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_08,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_09,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_100,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_ANGEL,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_APOLLO,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_ARCHER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BANSHEE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BEARING,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BLOODHOU,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BULLDOG,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHARGER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHEETAH,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHIEFTAI,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COBRA,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COMET,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CONDOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COUGAR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COWBOY,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DARKHORS,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DEMON,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DODGER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DRAGON,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_EAGLE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_EIGHTBAL,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_01,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_02,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_03,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_04,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_05,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_06,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FARSIGHT,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREBALL,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREBIRD,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREFOX,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FREELANC,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GATOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GAUNTLET,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GHOSTRID,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GLADIATO,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GOLIATH,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GOOSE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HAWKEYE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HELLCAT,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HUNTER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JAGUAR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JESTER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JUGGERNA,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JUPITER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KESTREL,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KNOT,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KNOTS,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_LANCER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_LIMA,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MANIAC,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MANTIS,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MAULER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MERCURY,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MERLIN,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MILKMAN,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MUSTANG,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_NIGHTMAR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PANTHER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PATRIOT,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PHANTOM,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PHOENIX,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PREACHER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PYTHON,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RANGE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAPTOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RATTLESN,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAZORBAC,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAZORWOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_REAPER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RENEGADE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SABRE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SAVAGE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHADOW,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHERIFF,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHOGUN,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SNOWBALL,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPARTACU,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPECTRUM,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPEED,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STALKER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STINGRAY,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STRIKER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SUNDOWN,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SWAMPFOX,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TEMPEST,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TIGERSHA,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TOUCHDOW,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VAMPIRE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VERTIGO,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIGILANT,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIKING,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIPER,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VOODOO,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VULCAN,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VULTURE,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARLOCK,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARLORD,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARRIOR,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WILDCAT,
	SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WOLFPACK,

	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_0,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_01,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_02,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_03,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_04,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_05,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_06,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_07,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_08,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_09,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_100,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_ANGEL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_APOLLO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_ARCHER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BANSHEE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BEARING,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BLOODHOU,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BULLDOG,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHARGER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHEETAH,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHIEFTAI,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COBRA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COMET,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CONDOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COUGAR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COWBOY,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DARKHORS,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DEMON,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DODGER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DRAGON,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_EAGLE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_EIGHTBAL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_01,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_02,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_03,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_04,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_05,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_06,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FARSIGHT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREBALL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREBIRD,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREFOX,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FREELANC,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GATOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GAUNTLET,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GHOSTRID,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GLADIATO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GOLIATH,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GOOSE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HAWKEYE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HELLCAT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HUNTER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JAGUAR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JESTER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JUGGERNA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JUPITER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KESTREL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KNOT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KNOTS,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_LANCER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_LIMA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MANIAC,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MANTIS,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MAULER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MERCURY,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MERLIN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MILKMAN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MUSTANG,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_NIGHTMAR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PANTHER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PATRIOT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PHANTOM,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PHOENIX,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PREACHER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PYTHON,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RANGE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAPTOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RATTLESN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAZORBAC,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAZORWOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_REAPER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RENEGADE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SABRE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SAVAGE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHADOW,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHERIFF,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHOGUN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SNOWBALL,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPARTACU,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPECTRUM,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPEED,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STALKER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STINGRAY,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STRIKER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SUNDOWN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SWAMPFOX,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TEMPEST,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TIGERSHA,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TOUCHDOW,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VAMPIRE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VERTIGO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIGILANT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIKING,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIPER,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VOODOO,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VULCAN,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VULTURE,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARLOCK,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARLORD,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARRIOR,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WILDCAT,
	SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WOLFPACK,

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

