// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_0, 						ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\0.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_01, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\01.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_02, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\02.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_03, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\03.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_04, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\04.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_05, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\05.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_06, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\06.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_07, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\07.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_08, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\08.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_09, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\09.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_100, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\100.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_ANGEL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\ANGEL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_APOLLO, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\APOLLO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_ARCHER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\ARCHER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BANSHEE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\BANSHEE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BEARING, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\BEARING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BLOODHOU, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\BLOODHOU.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BULLDOG, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\BULLDOG.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHARGER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\CHARGER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHEETAH, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\CHEETAH.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHIEFTAI, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\CHIEFTAI.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COBRA, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\COBRA.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COMET, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\COMET.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CONDOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\CONDOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COUGAR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\COUGAR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COWBOY, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\COWBOY.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DARKHORS, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\DARKHORS.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DEMON, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\DEMON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DODGER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\DODGER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DRAGON, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\DRAGON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_EAGLE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\EAGLE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_EIGHTBAL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\EIGHTBAL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_01, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FAC_01.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_02, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FAC_02.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_03, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FAC_03.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_04, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FAC_04.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_05, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FAC_05.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FAC_06, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FAC_06.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FARSIGHT, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FARSIGHT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREBALL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FIREBALL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREBIRD, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FIREBIRD.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREFOX, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FIREFOX.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FREELANC, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\FREELANC.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GATOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\GATOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GAUNTLET, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\GAUNTLET.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GHOSTRID, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\GHOSTRID.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GLADIATO, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\GLADIATO.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GOLIATH, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\GOLIATH.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GOOSE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\GOOSE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HAWKEYE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\HAWKEYE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HELLCAT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\HELLCAT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HUNTER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\HUNTER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JAGUAR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\JAGUAR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JESTER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\JESTER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JUGGERNA, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\JUGGERNA.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JUPITER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\JUPITER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KESTREL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\KESTREL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KNOT, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\KNOT.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KNOTS, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\KNOTS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_LANCER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\LANCER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_LIMA, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\LIMA.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MANIAC, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MANIAC.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MANTIS, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MANTIS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MAULER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MAULER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MERCURY, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MERCURY.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MERLIN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MERLIN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MILKMAN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MILKMAN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MUSTANG, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\MUSTANG.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_NIGHTMAR, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\NIGHTMAR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PANTHER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\PANTHER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PATRIOT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\PATRIOT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PHANTOM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\PHANTOM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PHOENIX, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\PHOENIX.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PREACHER, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\PREACHER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PYTHON, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\PYTHON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RANGE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\RANGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAPTOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\RAPTOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RATTLESN, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\RATTLESN.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAZORBAC, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\RAZORBAC.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAZORWOR, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\RAZORWOR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_REAPER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\REAPER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RENEGADE, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\RENEGADE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SABRE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SABRE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SAVAGE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SAVAGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHADOW, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SHADOW.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHERIFF, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SHERIFF.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHOGUN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SHOGUN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SNOWBALL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SNOWBALL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPARTACU, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SPARTACU.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPECTRUM, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SPECTRUM.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPEED, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SPEED.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STALKER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\STALKER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STINGRAY, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\STINGRAY.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STRIKER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\STRIKER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SUNDOWN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SUNDOWN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SWAMPFOX, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\SWAMPFOX.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TEMPEST, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\TEMPEST.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TIGERSHA, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\TIGERSHA.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TOUCHDOW, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\TOUCHDOW.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VAMPIRE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VAMPIRE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VERTIGO, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VERTIGO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIGILANT, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VIGILANT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIKING, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VIKING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIPER, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VIPER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VOODOO, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VOODOO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VULCAN, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VULCAN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VULTURE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\VULTURE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARLOCK, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\WARLOCK.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARLORD, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\WARLORD.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARRIOR, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\WARRIOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WILDCAT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\WILDCAT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WOLFPACK, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\FAC\\WOLFPACK.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_0, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\0.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_01, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\01.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_02,	 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\02.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_03, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\03.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_04, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\04.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_05, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\05.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_06, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\06.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_07, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\07.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_08, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\08.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_09, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\09.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_100, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\100.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_ANGEL, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\ANGEL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_APOLLO, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\APOLLO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_ARCHER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\ARCHER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BANSHEE, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\BANSHEE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BEARING, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\BEARING.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BLOODHOU, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\BLOODHOU.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BULLDOG, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\BULLDOG.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHARGER, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\CHARGER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHEETAH, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\CHEETAH.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHIEFTAI, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\CHIEFTAI.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COBRA, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\COBRA.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COMET, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\COMET.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CONDOR, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\CONDOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COUGAR, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\COUGAR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COWBOY, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\COWBOY.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DARKHORS, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\DARKHORS.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DEMON, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\DEMON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DODGER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\DODGER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DRAGON, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\DRAGON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_EAGLE, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\EAGLE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_EIGHTBAL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\EIGHTBAL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_01, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FAC_01.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_02, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FAC_02.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_03, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FAC_03.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_04, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FAC_04.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_05, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FAC_05.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FAC_06, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FAC_06.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FARSIGHT, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FARSIGHT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREBALL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FIREBALL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREBIRD, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FIREBIRD.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREFOX, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FIREFOX.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FREELANC, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\FREELANC.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GATOR, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\GATOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GAUNTLET, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\GAUNTLET.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GHOSTRID, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\GHOSTRID.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GLADIATO, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\GLADIATO.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GOLIATH, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\GOLIATH.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GOOSE, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\GOOSE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HAWKEYE, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\HAWKEYE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HELLCAT, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\HELLCAT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HUNTER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\HUNTER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JAGUAR, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\JAGUAR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JESTER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\JESTER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JUGGERNA, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\JUGGERNA.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JUPITER, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\JUPITER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KESTREL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\KESTREL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KNOT, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\KNOT.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KNOTS, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\KNOTS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_LANCER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\LANCER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_LIMA, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\LIMA.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MANIAC, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MANIAC.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MANTIS, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MANTIS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MAULER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MAULER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MERCURY, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MERCURY.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MERLIN, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MERLIN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MILKMAN, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MILKMAN.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MUSTANG, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\MUSTANG.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_NIGHTMAR, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\NIGHTMAR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PANTHER, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\PANTHER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PATRIOT, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\PATRIOT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PHANTOM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\PHANTOM.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PHOENIX, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\PHOENIX.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PREACHER, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\PREACHER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PYTHON, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\PYTHON.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RANGE, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\RANGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAPTOR, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\RAPTOR.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RATTLESN, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\RATTLESN.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAZORBAC, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\RAZORBAC.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAZORWOR, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\RAZORWOR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_REAPER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\REAPER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RENEGADE, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\RENEGADE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SABRE, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SABRE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SAVAGE, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SAVAGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHADOW, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SHADOW.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHERIFF, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SHERIFF.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHOGUN, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SHOGUN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SNOWBALL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SNOWBALL.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPARTACU, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SPARTACU.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPECTRUM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SPECTRUM.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPEED, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SPEED.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STALKER, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\STALKER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STINGRAY, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\STINGRAY.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STRIKER, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\STRIKER.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SUNDOWN, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SUNDOWN.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SWAMPFOX, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\SWAMPFOX.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TEMPEST, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\TEMPEST.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TIGERSHA, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\TIGERSHA.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TOUCHDOW, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\TOUCHDOW.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VAMPIRE, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VAMPIRE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VERTIGO, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VERTIGO.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIGILANT, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VIGILANT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIKING, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VIKING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIPER, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VIPER.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VOODOO, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VOODOO.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VULCAN, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VULCAN.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VULTURE, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\VULTURE.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARLOCK, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\WARLOCK.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARLORD, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\WARLORD.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARRIOR, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\WARRIOR.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WILDCAT, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\WILDCAT.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WOLFPACK, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\FAC\\WOLFPACK.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

