// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_0, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\0.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_01, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\01.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_01_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\01_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_01_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\01_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_02, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\02.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_02_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\02_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_02_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\02_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_03, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\03.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_03_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\03_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_03_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\03_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_04, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\04.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_04_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\04_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_04_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\04_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_05, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\05.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_05_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\05_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_05_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\05_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_06, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\06.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_06_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\06_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_06_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\06_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_07, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\07.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_07_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\07_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_07_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\07_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_08, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\08.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_08_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\08_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_08_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\08_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_09, 					ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\09.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_09_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\09_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_09_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\09_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_100, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\100.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_10_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\10_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_10_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\10_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_11_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\11_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_11_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\11_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_12_CL, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\12_CL.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_12_KM, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\12_KM.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_BEARING, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\BEARING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_01, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_01.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_02, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_02.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_03, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_03.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_04, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_04.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_05, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_05.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_06, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_06.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_07, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_07.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_08, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_08.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_09, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_09.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_10, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_10.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_11, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_11.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_CLOCK_12, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\CLOCK_12.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_01, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_01.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_02, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_02.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_03, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_03.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_04, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_04.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_05, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_05.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_06, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_06.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_07, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_07.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_08, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_08.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_09, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_09.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_10, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_10.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_11, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_11.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_GC_12, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\GC_12.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_HALF_CL, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\HALF_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_HALF_KM, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\HALF_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_KNOT, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\KNOT.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_KNOTS, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\KNOTS.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_RANGE, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\RANGE.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_GC_SPEED, 				ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\GC\\SPEED.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_0, 					ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\0.PCM", 					22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_01, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\01.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_01_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\01_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_01_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\01_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_02, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\02.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_02_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\02_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_02_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\02_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_03, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\03.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_03_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\03_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_03_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\03_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_04, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\04.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_04_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\04_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_04_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\04_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_05, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\05.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_05_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\05_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_05_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\05_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_06, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\06.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_06_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\06_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_06_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\06_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_07, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\07.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_07_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\07_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_07_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\07_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_08, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\08.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_08_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\08_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_08_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\08_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_09, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\09.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_09_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\09_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_09_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\09_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_100, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\100.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_10_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\10_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_10_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\10_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_11_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\11_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_11_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\11_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_12_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\12_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_12_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\12_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_BEARING, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\BEARING.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_01, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_01.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_02, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_02.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_03, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_03.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_04, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_04.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_05, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_05.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_06, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_06.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_07, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_07.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_08, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_08.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_09, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_09.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_10, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_10.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_11, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_11.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_CLOCK_12, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\CLOCK_12.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_01, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_01.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_02, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_02.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_03, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_03.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_04, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_04.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_05, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_05.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_06, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_06.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_07, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_07.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_08, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_08.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_09, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_09.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_10, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_10.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_11, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_11.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_GC_12, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\GC_12.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_HALF_CL, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\HALF_CL.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_HALF_KM, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\HALF_KM.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_KNOT, 				ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\KNOT.PCM", 				22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_KNOTS, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\KNOTS.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_RANGE, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\RANGE.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_GC_SPEED, 			ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\GC\\SPEED.PCM", 			22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


