// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_01, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_01.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_02, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_02.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_03, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_03.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_04, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_04.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_05, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_05.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_06, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_06.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_07, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_07.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_08, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_08.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_09, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_09.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_10, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_10.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_11, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_11.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_12, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_12.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_13, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_13.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_14, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_14.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_15, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_15.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_16, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_16.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_17, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_17.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_18, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_18.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_19, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_19.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_20, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_20.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_21, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_21.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_22, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_22.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_23, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_23.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_24, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_24.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_25, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_25.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_26, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_26.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_27, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_27.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_28, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_28.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_29, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_29.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_30, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_30.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_31, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_31.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_32, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_32.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_33, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_33.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_34, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_34.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_35, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_35.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_36, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_36.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_37, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_37.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_38, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_38.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_39, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_39.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_40, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_40.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_41, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_41.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_42, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_42.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_US_SYSTEM_WARN_43, 			ENTITY_SIDE_BLUE_FORCE,	"SPEECH\\US\\SYSTEM\\WARN_43.PCM", 		22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_01, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_01.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_02, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_02.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_03, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_03.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_04, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_04.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_05, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_05.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_06, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_06.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_07, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_07.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_08, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_08.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_09, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_09.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_10, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_10.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_11, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_11.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_12, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_12.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_13, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_13.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_14, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_14.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_15, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_15.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_16, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_16.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_17, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_17.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_18, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_18.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_19, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_19.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_20, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_20.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_21, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_21.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
//	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_22, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_22.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_23, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_23.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_24, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_24.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_25, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_25.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_26, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_26.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_27, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_27.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_28, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_28.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_29, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_29.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_30, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_30.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_31, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_31.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_32, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_32.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_33, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_33.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_34, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_34.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_35, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_35.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_36, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_36.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_37, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_37.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_38, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_38.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_39, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_39.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_40, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_40.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_41, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_41.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_42, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_42.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },
	{ SOUND_SAMPLE_INDEX_SPEECH_CIS_SYSTEM_WARN_43, 		ENTITY_SIDE_RED_FORCE,	"SPEECH\\CIS\\SYSTEM\\WARN_43.PCM", 	22050,	SOUND_MAXIMUM_VOLUME,	0.0 },

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


