// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



		////////////////////////////////////////////////////////////////////////////////
		//
		// ENTITY_SUB_TYPE_AIRCRAFT_KA50_HOKUM
		//
		////////////////////////////////////////////////////////////////////////////////

		#define LHS_HARDPOINT1							(HOKUM_LHS_INNER_PYLON)
		#define RHS_HARDPOINT1							(HOKUM_RHS_INNER_PYLON)
		#define LHS_HARDPOINT2							(HOKUM_LHS_OUTER_PYLON)
		#define RHS_HARDPOINT2							(HOKUM_RHS_OUTER_PYLON)
		#define CANNON_TURRET							(HOKUM_CANNON_TURRET)
		#define LHS_CHAFF_DISPENSER					(HOKUM_LHS_CHAFF_DISPENSER)
		#define RHS_CHAFF_DISPENSER					(HOKUM_RHS_CHAFF_DISPENSER)
		#define LHS_FLARE_DISPENSER					(HOKUM_LHS_FLARE_DISPENSER)
		#define RHS_FLARE_DISPENSER					(HOKUM_RHS_FLARE_DISPENSER)
		#define BLADE1_EJECT								(11)
		#define BLADE2_EJECT								(12)
		#define BLADE3_EJECT								(13)
		#define BLADE4_EJECT								(14)
		#define BLADE5_EJECT								(15)
		#define BLADE6_EJECT								(16)
		#define PILOT_EJECT								(9)
		#define CO_PILOT_EJECT							(10)
		#define PILOT_DOOR_EJECT						(7)
		#define CO_PILOT_DOOR_EJECT					(8)

		#define CANNON_BARREL							(0)
		#define VIKHR_RACK								(0)
		#define IGLA_PYLON								(1)
		#define B8_POD										(2)
		#define B13_POD									(3)
		#define CANNON_POD								(4)
		#define CHAFF_VECTOR								(0)
		#define FLARE_VECTOR								(0)
		#define BLADE_EJECT_VECTOR						(0)
		#define CREW_EJECT_VECTOR						(0)
		#define DOOR_EJECT_VECTOR						(0)

		#define NUM_HE_CANNON_ROUNDS					(230)
		#define NUM_AP_CANNON_ROUNDS					(240)
		#define NUM_VIKHR_MISSILES						(6)
		#define NUM_IGLA_MISSILES						(2)
		#define NUM_S8_ROCKETS							(20)
		#define NUM_S13_ROCKETS							(5)
		#define NUM_CANNON_POD_ROUNDS					(250)
		#define NUM_CHAFFS								(32)
		#define NUM_FLARES								(32)
		#define NUM_BLADES								(1)
		#define NUM_PILOTS								(1)
		#define NUM_CO_PILOTS							(1)
		#define NUM_DOORS									(1)

		#define CANNON_TURRET_HEADING_RATE			(rad (10.0))
		#define CANNON_TURRET_MIN_HEADING_LIMIT	(rad (-2.5))
		#define CANNON_TURRET_MAX_HEADING_LIMIT	(rad (9.0))
		#define CANNON_BARREL_PITCH_RATE				(rad (45.0))
		#define CANNON_BARREL_MIN_PITCH_LIMIT		(rad (-37.0))
		#define CANNON_BARREL_MAX_PITCH_LIMIT		(rad (3.0))

		#define VIKHR_RACK_PITCH_RATE					(rad (20.0))
		#define VIKHR_RACK_MIN_PITCH_LIMIT			(rad (-10.0))
		#define VIKHR_RACK_MAX_PITCH_LIMIT			(rad (2.0))

//		sub_type, number, heading_depth, pitch_depth, muzzle_depth, make_weapon_system_ready, rotate, salvo_size, heading_rate, min_heading_limit, max_heading_limit, pitch_rate, min_pitch_limit, max_pitch_limit, muzzle_rotate_rate, rotate_inhibit_velocity, heading_share_mask, pitch_share_mask, muzzle_flash_type

		#define WEAPON_CHAFF(HEADING) ENTITY_SUB_TYPE_WEAPON_CHAFF, NUM_CHAFFS, HEADING, CHAFF_VECTOR, 0, FALSE, FALSE, 4, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_INVALID,
		#define WEAPON_FLARE(HEADING) ENTITY_SUB_TYPE_WEAPON_FLARE, NUM_FLARES, HEADING, FLARE_VECTOR, 0, FALSE, FALSE, 4, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_INVALID,
		#define WEAPON_2A42_30MM_HE_ROUND ENTITY_SUB_TYPE_WEAPON_2A42_30MM_HE_ROUND, NUM_HE_CANNON_ROUNDS, CANNON_TURRET, CANNON_BARREL, 0, FALSE, TRUE, 1, CANNON_TURRET_HEADING_RATE, CANNON_TURRET_MIN_HEADING_LIMIT, CANNON_TURRET_MAX_HEADING_LIMIT, CANNON_BARREL_PITCH_RATE, CANNON_BARREL_MIN_PITCH_LIMIT, CANNON_BARREL_MAX_PITCH_LIMIT, rad (0.0), knots_to_metres_per_second (10000.0), SHARE_WEAPON_PACKAGE5 + SHARE_WEAPON_PACKAGE6, SHARE_WEAPON_PACKAGE5 + SHARE_WEAPON_PACKAGE6, MUZZLE_FLASH_MEDIUM_CALIBRE_STRAIGHT,
		#define WEAPON_2A42_30MM_AP_ROUND ENTITY_SUB_TYPE_WEAPON_2A42_30MM_AP_ROUND, NUM_AP_CANNON_ROUNDS, CANNON_TURRET, CANNON_BARREL, 0, FALSE, TRUE, 1, CANNON_TURRET_HEADING_RATE, CANNON_TURRET_MIN_HEADING_LIMIT, CANNON_TURRET_MAX_HEADING_LIMIT, CANNON_BARREL_PITCH_RATE, CANNON_BARREL_MIN_PITCH_LIMIT, CANNON_BARREL_MAX_PITCH_LIMIT, rad (0.0), knots_to_metres_per_second (10000.0), SHARE_WEAPON_PACKAGE5 + SHARE_WEAPON_PACKAGE6, SHARE_WEAPON_PACKAGE5 + SHARE_WEAPON_PACKAGE6, MUZZLE_FLASH_MEDIUM_CALIBRE_STRAIGHT,
		#define WEAPON_HOKUM_BLADE(HEADING) ENTITY_SUB_TYPE_WEAPON_HOKUM_BLADE, NUM_BLADES, HEADING, BLADE_EJECT_VECTOR, 0, FALSE, FALSE, 6, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_LARGE_CALIBRE_STRAIGHT,
		#define WEAPON_HOKUM_PILOT ENTITY_SUB_TYPE_WEAPON_HOKUM_PILOT, NUM_PILOTS, PILOT_EJECT, CREW_EJECT_VECTOR, 0, FALSE, FALSE, 1, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_LARGE_CALIBRE_STRAIGHT,
		#define WEAPON_HOKUM_CO_PILOT ENTITY_SUB_TYPE_WEAPON_HOKUM_CO_PILOT, NUM_CO_PILOTS, CO_PILOT_EJECT, CREW_EJECT_VECTOR, 0, FALSE, FALSE, 1, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_LARGE_CALIBRE_STRAIGHT,
		#define WEAPON_HOKUM_LH_DOOR ENTITY_SUB_TYPE_WEAPON_HOKUM_LH_DOOR, NUM_DOORS, PILOT_DOOR_EJECT, DOOR_EJECT_VECTOR, 0, FALSE, FALSE, 1, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_INVALID,
		#define WEAPON_HOKUM_RH_DOOR ENTITY_SUB_TYPE_WEAPON_HOKUM_RH_DOOR, NUM_DOORS, CO_PILOT_DOOR_EJECT, DOOR_EJECT_VECTOR, 0, FALSE, FALSE, 1, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_INVALID,
		#define WEAPON_VIKHR(HEADING) ENTITY_SUB_TYPE_WEAPON_9K121_VIKHR, NUM_VIKHR_MISSILES, HEADING, VIKHR_RACK, 0, FALSE, TRUE, 1, rad (0.0), rad (0.0), rad (0.0), VIKHR_RACK_PITCH_RATE, VIKHR_RACK_MIN_PITCH_LIMIT, VIKHR_RACK_MAX_PITCH_LIMIT, rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_SMALL_ROCKET,
		#define WEAPON_IGLA_V(HEADING) ENTITY_SUB_TYPE_WEAPON_9M39_IGLA_V, NUM_IGLA_MISSILES, HEADING, IGLA_PYLON, 0, FALSE, FALSE, 1, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_SMALL_ROCKET,
		#define WEAPON_S8(HEADING) ENTITY_SUB_TYPE_WEAPON_S8, NUM_S8_ROCKETS, HEADING, B8_POD, 0, FALSE, FALSE, 2, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_MEDIUM_ROCKET,
		#define WEAPON_S13(HEADING) ENTITY_SUB_TYPE_WEAPON_S13, NUM_S13_ROCKETS, HEADING, B13_POD, 0, FALSE, FALSE, 2, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_LARGE_ROCKET,
		#define WEAPON_GSH23L_23MM_ROUND(HEADING) ENTITY_SUB_TYPE_WEAPON_GSH23L_23MM_ROUND, NUM_CANNON_POD_ROUNDS, HEADING, CANNON_POD, 0, FALSE, FALSE, 2, rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), rad (0.0), knots_to_metres_per_second (10000.0), 0, 0, MUZZLE_FLASH_MEDIUM_CALIBRE_STRAIGHT,
				
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_1
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 18
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_2
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_3
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_4
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_5
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_6
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_VIKHR(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 18
			{ WEAPON_VIKHR(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_7
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_VIKHR(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_VIKHR(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_8
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_VIKHR(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_VIKHR(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_9
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_VIKHR(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_VIKHR(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_10
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_VIKHR(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_VIKHR(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_11
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_12
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_IGLA_V(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_IGLA_V(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_13
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_IGLA_V(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_IGLA_V(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_14
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_IGLA_V(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_IGLA_V(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_15
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_IGLA_V(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_IGLA_V(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_16
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_17
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S8(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S8(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_18
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S8(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S8(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_19
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S8(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S8(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_20
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S8(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S8(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_21
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_22
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S13(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S13(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_23
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S13(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S13(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_24
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S13(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S13(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_25
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_S13(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_S13(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_26
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 19
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 20
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_27
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_IGLA_V(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_IGLA_V(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_28
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S8(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S8(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_29
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_S13(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_S13(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},
		////////////////////////////////////////
		//
		// WEAPON_CONFIG_TYPE_KA50_HOKUM_30
		//
		////////////////////////////////////////
		{
			// WEAPON PACKAGE 1
			{ WEAPON_CHAFF(LHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 2
			{ WEAPON_CHAFF(RHS_CHAFF_DISPENSER) },
			// WEAPON PACKAGE 3
			{ WEAPON_FLARE(LHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 4
			{ WEAPON_FLARE(RHS_FLARE_DISPENSER) },
			// WEAPON PACKAGE 5
			{ WEAPON_2A42_30MM_HE_ROUND },
			// WEAPON PACKAGE 6
			{ WEAPON_2A42_30MM_AP_ROUND },
			// WEAPON PACKAGE 7
			{ WEAPON_HOKUM_BLADE(BLADE1_EJECT) },
			// WEAPON PACKAGE 8
			{ WEAPON_HOKUM_BLADE(BLADE2_EJECT) },
			// WEAPON PACKAGE 9
			{ WEAPON_HOKUM_BLADE(BLADE3_EJECT) },
			// WEAPON PACKAGE 10
			{ WEAPON_HOKUM_BLADE(BLADE4_EJECT) },
			// WEAPON PACKAGE 11
			{ WEAPON_HOKUM_BLADE(BLADE5_EJECT) },
			// WEAPON PACKAGE 12
			{ WEAPON_HOKUM_BLADE(BLADE6_EJECT) },
			// WEAPON PACKAGE 13
			{ WEAPON_HOKUM_PILOT },
			// WEAPON PACKAGE 14
			{ WEAPON_HOKUM_CO_PILOT },
			// WEAPON PACKAGE 15
			{ WEAPON_HOKUM_LH_DOOR },
			// WEAPON PACKAGE 16
			{ WEAPON_HOKUM_RH_DOOR },
			// WEAPON PACKAGE 17
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT1) },
			// WEAPON PACKAGE 18
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT1) },
			// WEAPON PACKAGE 19
			{ WEAPON_GSH23L_23MM_ROUND(LHS_HARDPOINT2) },
			// WEAPON PACKAGE 20
			{ WEAPON_GSH23L_23MM_ROUND(RHS_HARDPOINT2) },
			// WEAPON PACKAGE 21
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 22
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 23
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 24
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 25
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 26
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 27
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 28
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 29
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 30
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 31
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
			// WEAPON PACKAGE 32
			{ENTITY_SUB_TYPE_WEAPON_NO_WEAPON},
		},

		#undef LHS_HARDPOINT1
		#undef RHS_HARDPOINT1
		#undef LHS_HARDPOINT2
		#undef RHS_HARDPOINT2
		#undef CANNON_TURRET
		#undef LHS_CHAFF_DISPENSER
		#undef RHS_CHAFF_DISPENSER
		#undef LHS_FLARE_DISPENSER
		#undef RHS_FLARE_DISPENSER
		#undef BLADE1_EJECT
		#undef BLADE2_EJECT
		#undef BLADE3_EJECT
		#undef BLADE4_EJECT
		#undef BLADE5_EJECT
		#undef BLADE6_EJECT
		#undef PILOT_EJECT
		#undef CO_PILOT_EJECT
		#undef PILOT_DOOR_EJECT
		#undef CO_PILOT_DOOR_EJECT

		#undef CANNON_BARREL
		#undef VIKHR_RACK
		#undef IGLA_PYLON
		#undef B8_POD
		#undef B13_POD
		#undef CANNON_POD
		#undef CHAFF_VECTOR
		#undef FLARE_VECTOR
		#undef BLADE_EJECT_VECTOR
		#undef CREW_EJECT_VECTOR
		#undef DOOR_EJECT_VECTOR

		#undef NUM_HE_CANNON_ROUNDS
		#undef NUM_AP_CANNON_ROUNDS
		#undef NUM_VIKHR_MISSILES
		#undef NUM_IGLA_MISSILES
		#undef NUM_S8_ROCKETS
		#undef NUM_S13_ROCKETS
		#undef NUM_CANNON_POD_ROUNDS
		#undef NUM_CHAFFS
		#undef NUM_FLARES
		#undef NUM_BLADES
		#undef NUM_PILOTS
		#undef NUM_CO_PILOTS
		#undef NUM_DOORS

		#undef CANNON_TURRET_HEADING_RATE
		#undef CANNON_TURRET_MIN_HEADING_LIMIT
		#undef CANNON_TURRET_MAX_HEADING_LIMIT
		#undef CANNON_BARREL_PITCH_RATE
		#undef CANNON_BARREL_MIN_PITCH_LIMIT
		#undef CANNON_BARREL_MAX_PITCH_LIMIT

		#undef WEAPON_CHAFF
		#undef WEAPON_FLARE
		#undef WEAPON_2A42_30MM_HE_ROUND
		#undef WEAPON_2A42_30MM_AP_ROUND
		#undef WEAPON_HOKUM_BLADE
		#undef WEAPON_HOKUM_PILOT
		#undef WEAPON_HOKUM_CO_PILOT
		#undef WEAPON_HOKUM_LH_DOOR
		#undef WEAPON_HOKUM_RH_DOOR
		#undef WEAPON_VIKHR
		#undef WEAPON_IGLA_V
		#undef WEAPON_S8
		#undef WEAPON_S13
		#undef WEAPON_GSH23L_23MM_ROUND
