//
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
//
// 	 Please see the document LICENSE.TXT for the full licence agreement
//
// 2. LICENCE
//  2.1
//  	Subject to the provisions of this Agreement we now grant to you the
//  	following rights in respect of the Source Code:
//   2.1.1
//   	the non-exclusive right to Exploit  the Source Code and Executable
//   	Code on any medium; and
//   2.1.2
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
//
// 3. GENERAL OBLIGATIONS
//  3.1
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5
// 	not to place any restrictions on the operability of the Source
// 	Code;
//   3.1.6
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
//



#if 0
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum GRAPHICS_CONVERSION_PASS_TYPES
{
	GRAPHICS_CONVERSION_FIRST_PASS,
	GRAPHICS_CONVERSION_SECOND_PASS,
};

typedef enum GRAPHICS_CONVERSION_PASS_TYPES graphics_conversion_pass_types;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum GRAPHICS_CONVERSION_TYPES
{
#if 0
	CONVERT_TGA_TO_ALPHA_MASK,
	CONVERT_TGA_TO_RGB,
	CONVERT_TGA_TO_RGB_ALPHA,
	CONVERT_TGA_TO_RLE,
	CONVERT_PSD_TO_ALPHA_MASK,
	CONVERT_PSD_TO_RGB,
	CONVERT_PSD_TO_RGB_ALPHA,
	CONVERT_PSD_TO_RLE,
	CONVERT_PSD_TO_DITHERED_RGB,
	CONVERT_PSD_TO_DITHERED_RGB_ALPHA,
	CONVERT_PSD_TO_DITHERED_RLE,
	NUM_GRAPHICS_CONVERSION_TYPES
#else
	CONVERT_PSD_TO_RGBX,
	CONVERT_PSD_TO_RGBA,
	NUM_GRAPHICS_CONVERSION_TYPES,
	CONVERT_PSD_TO_RGB = CONVERT_PSD_TO_RGBX,
	CONVERT_PSD_TO_RGB_ALPHA = CONVERT_PSD_TO_RGBA,
	CONVERT_PSD_TO_DITHERED_RGB = CONVERT_PSD_TO_RGBX,
	CONVERT_PSD_TO_DITHERED_RGB_ALPHA = CONVERT_PSD_TO_RGBA,
#endif
};

typedef enum GRAPHICS_CONVERSION_TYPES graphics_conversion_types;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum PATH_NAMES
{
	GRAPHICS_COCKPITS,
#if 0
	GRAPHICS_COCKPITS_APACHE_LEVEL1,
	GRAPHICS_COCKPITS_APACHE_LEVEL2,
	GRAPHICS_COCKPITS_APACHE_LEVEL3,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3,
	GRAPHICS_UI_APACHE,
#endif
	GRAPHICS_UI_COMMON,
#if 0
	GRAPHICS_UI_HAVOC,
#endif
	COMMON_MAPS_MAP1_GRAPHICS,
	COMMON_MAPS_MAP2_GRAPHICS,
	COMMON_MAPS_MAP3_GRAPHICS,
	COMMON_MAPS_MAP4_GRAPHICS,
	NUM_PATH_NAMES
};

typedef enum PATH_NAMES path_names;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct FILE_DATA
{
	path_names
		path_name;

	char
		file_name[9],
		distribution_extension[4],
		installation_extension[4];

	graphics_conversion_types
		graphics_conversion_type;

	rgb_data
		*data;

	int
		first_pass_conversion;

	unsigned int
		required_for_demo				  					  				:1,
		required_for_comanche_hokum		 							:1,
		required_for_apache_havoc_cockpits	 						:1,
		required_for_apache_havoc_cockpits_patched_versions	:1;
};

typedef struct FILE_DATA file_data;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

extern file_data
	graphics_files[];

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#if 0
enum APACHE_GRAPHICS_FILE_OFFSETS
{
	GRAPHICS_COCKPITS_APACHE_U40_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_U40_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_U40_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_U40_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_U40_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_U40_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_U40_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_U20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LVL_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_D20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LHS_MFD_RGB,
	GRAPHICS_COCKPITS_APACHE_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_MFD_MASK_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_MFD_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_MFD_MASK_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_MFD_MASK_LHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_MFD_MASK_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_SPRITES,
	GRAPHICS_COCKPITS_APACHE_SPRITES_MASK,
	GRAPHICS_COCKPITS_APACHE_WEAPONS_MFD_SPRITES,
	GRAPHICS_COCKPITS_APACHE_WEAPONS_MFD_SPRITES_MASK,
};

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum HAVOC_GRAPHICS_FILE_OFFSETS
{
	GRAPHICS_COCKPITS_HAVOC_U40_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_U40_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_U40_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_U40_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_U40_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_U20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LVL_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_D20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_CRT_RGB,
	GRAPHICS_COCKPITS_HAVOC_HUD_RLE,
	GRAPHICS_COCKPITS_HAVOC_CRT_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_CRT_MASK_CRT_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_WIPER_HUD,
	GRAPHICS_COCKPITS_HAVOC_SPRITES,
	GRAPHICS_COCKPITS_HAVOC_SPRITES_MASK,
	GRAPHICS_COCKPITS_HAVOC_TWD,
};
#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum GRAPHICS_FILE_SPECIFIERS
{
	////////////////////////////////////////
	//
	// IMPORTANT! ORDER MUST MATCH graphics_files[] (GFXFILES.C)
	//
	////////////////////////////////////////

	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//
	// FIRST PASS CONVERSIONS
	//
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#if 0
	////////////////////////////////////////
	//
	// INIT SCREEN
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_INIT_SCREEN,
	GRAPHICS_UI_HAVOC_INIT_SCREEN,
#endif

	////////////////////////////////////////
	//
	// UI\COMMON
	//
	////////////////////////////////////////

	GRAPHICS_UI_COMMON_MOUSE_POINTER,
	GRAPHICS_UI_COMMON_ARIAL_22_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_BLACK_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_DARK_GREY_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_BLUE_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_GREEN_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_ORANGE_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_RED_FONT,
	GRAPHICS_UI_COMMON_ARIAL_22_YELLOW_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_BLUE_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_RED_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_YELLOW_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_GREY_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_ORANGE_FONT,
	GRAPHICS_UI_COMMON_ARIAL_15_GREEN_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_BLACK_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_DARK_GREY_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_BLUE_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_GREEN_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_GREY_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_ORANGE_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_RED_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_YELLOW_FONT,
	GRAPHICS_UI_COMMON_ARIAL_11_BLACK,
	GRAPHICS_UI_COMMON_ADS_11_WHITE_FONT,
	GRAPHICS_UI_COMMON_ADS_11_YELLOW_FONT,
	GRAPHICS_UI_COMMON_ADS_11_GREY_FONT,
	GRAPHICS_UI_COMMON_ADS_11_BLUE_FONT,
	GRAPHICS_UI_COMMON_ADS_11_ORANGE_FONT,
	GRAPHICS_UI_COMMON_ADS_15_WHITE_FONT,
	GRAPHICS_UI_COMMON_ADS_15_YELLOW_FONT,
	GRAPHICS_UI_COMMON_ADS_15_BLUE_FONT,
	GRAPHICS_UI_COMMON_ADS_15_ORANGE_FONT,
	GRAPHICS_UI_COMMON_ADS_22_WHITE_FONT,
	GRAPHICS_UI_COMMON_ADS_22_YELLOW_FONT,
	GRAPHICS_UI_COMMON_ADS_22_BLUE_FONT,
	GRAPHICS_UI_COMMON_ADS_22_ORANGE_FONT,
	GRAPHICS_UI_COMMON_MONO_7_FONT,
	GRAPHICS_UI_COMMON_ARIAL_8_FONT_WHITE,
	GRAPHICS_UI_COMMON_ARIAL_8_FONT_YELLOW,

	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//
	// SECOND PASS CONVERSIONS
	//
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////
	//
	// COCKPITS
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_LOGO,

#if 0
	////////////////////////////////////////
	//
	// COCKPITS\APACHE\LEVEL1 (must match APACHE_GRAPHICS_FILE_OFFSETS)
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_APACHE_LEVEL1_BASE,

	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_L90_RLE = GRAPHICS_COCKPITS_APACHE_LEVEL1_BASE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U40_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_U20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LVL_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_D20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_LHS_MFD_RGB,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_MFD_MASK_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_MFD_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_MFD_MASK_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_MFD_MASK_LHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_MFD_MASK_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_SPRITES,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_SPRITES_MASK,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WEAPONS_MFD_SPRITES,
	GRAPHICS_COCKPITS_APACHE_LEVEL1_WEAPONS_MFD_SPRITES_MASK,

	////////////////////////////////////////
	//
	// COCKPITS\APACHE\LEVEL2 (must match APACHE_GRAPHICS_FILE_OFFSETS)
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_APACHE_LEVEL2_BASE,

	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_L90_RLE = GRAPHICS_COCKPITS_APACHE_LEVEL2_BASE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U40_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_U20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LVL_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_D20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_LHS_MFD_RGB,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_MFD_MASK_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_MFD_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_MFD_MASK_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_MFD_MASK_LHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_MFD_MASK_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_SPRITES,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_SPRITES_MASK,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WEAPONS_MFD_SPRITES,
	GRAPHICS_COCKPITS_APACHE_LEVEL2_WEAPONS_MFD_SPRITES_MASK,

	////////////////////////////////////////
	//
	// COCKPITS\APACHE\LEVEL3 (must match APACHE_GRAPHICS_FILE_OFFSETS)
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_APACHE_LEVEL3_BASE,

	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_L90_RLE = GRAPHICS_COCKPITS_APACHE_LEVEL3_BASE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U40_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_U20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LVL_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_L90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_L60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_R60_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_D20_R90_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_LHS_MFD_RGB,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_MFD_MASK_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_MFD_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_MFD_MASK_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_MFD_MASK_LHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_MFD_MASK_RHS_MFD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_U20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_SPRITES,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_SPRITES_MASK,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WEAPONS_MFD_SPRITES,
	GRAPHICS_COCKPITS_APACHE_LEVEL3_WEAPONS_MFD_SPRITES_MASK,

	////////////////////////////////////////
	//
	// COCKPITS\HAVOC\LEVEL1 (must match HAVOC_GRAPHICS_FILE_OFFSETS)
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_HAVOC_LEVEL1_BASE,

	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_L90_RLE = GRAPHICS_COCKPITS_HAVOC_LEVEL1_BASE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U40_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_U20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_LVL_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_D20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_CRT_RGB,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_HUD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_CRT_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_CRT_MASK_CRT_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_WIPER_HUD,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_SPRITES,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_SPRITES_MASK,
	GRAPHICS_COCKPITS_HAVOC_LEVEL1_TWD,

	////////////////////////////////////////
	//
	// COCKPITS\HAVOC\LEVEL2 (must match HAVOC_GRAPHICS_FILE_OFFSETS)
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_HAVOC_LEVEL2_BASE,

	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_L90_RLE = GRAPHICS_COCKPITS_HAVOC_LEVEL2_BASE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U40_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_U20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_LVL_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_D20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_CRT_RGB,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_HUD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_CRT_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_CRT_MASK_CRT_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_WIPER_HUD,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_SPRITES,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_SPRITES_MASK,
	GRAPHICS_COCKPITS_HAVOC_LEVEL2_TWD,

	////////////////////////////////////////
	//
	// COCKPITS\HAVOC\LEVEL3 (must match HAVOC_GRAPHICS_FILE_OFFSETS)
	//
	////////////////////////////////////////

	GRAPHICS_COCKPITS_HAVOC_LEVEL3_BASE,

	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_L90_RLE = GRAPHICS_COCKPITS_HAVOC_LEVEL3_BASE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U40_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_U20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_LVL_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_L90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_L60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_R60_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_D20_R90_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_CRT_RGB,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_HUD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_CRT_MASK_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_CRT_MASK_CRT_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_U40_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_U40_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_U20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_U20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_LVL_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_LVL_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_LVL_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_D20_L30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_D20_AHD_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_D20_R30_RLE,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_WIPER_HUD,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_SPRITES,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_SPRITES_MASK,
	GRAPHICS_COCKPITS_HAVOC_LEVEL3_TWD,

	////////////////////////////////////////
	//
	// UI\APACHE
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_CZONE_SCREEN,
	GRAPHICS_UI_APACHE_EXIT_SCREEN,
	GRAPHICS_UI_APACHE_GAME_OPTION_SCREEN,
	GRAPHICS_UI_APACHE_LOADING_SCREEN,
	GRAPHICS_UI_APACHE_MAIN_SCREEN,
	GRAPHICS_UI_APACHE_MULTI_SCREEN,
	GRAPHICS_UI_APACHE_PLAYER_SCREEN,
	GRAPHICS_UI_APACHE_TITLE_SCREEN,
	GRAPHICS_UI_APACHE_CAMPAIGN_OVER_SCREEN,
	GRAPHICS_UI_APACHE_GUNSHIP_SCREEN,
	GRAPHICS_UI_APACHE_DEMO_SCREEN,

	////////////////////////////////////////
	//
	// MAIN SCREEN BUTTONS
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_MAIN_SCREEN_PLAYER_BUTTON,
	GRAPHICS_UI_APACHE_MAIN_SCREEN_MULTI_BUTTON,
	GRAPHICS_UI_APACHE_MAIN_SCREEN_OPTIONS_BUTTON,
	GRAPHICS_UI_APACHE_MAIN_SCREEN_COMBAT_BUTTON,
	GRAPHICS_UI_APACHE_MAIN_SCREEN_EXIT_BUTTON,
	GRAPHICS_UI_APACHE_MAIN_SCREEN_DEMO_BUTTON,

	////////////////////////////////////////
	//
	// GAME OPTION SCREEN
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// COMBAT ZONE SCREEN
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_COMBAT_ZONE_NEXT_BUTTON,
	GRAPHICS_UI_APACHE_COMBAT_ZONE_BACK_BUTTON,

	////////////////////////////////////////
	//
	// COMBAT MISSIONS SCREEN
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_COMBAT_MISSIONS_BACK_BUTTON,
	GRAPHICS_UI_APACHE_COMBAT_MISSIONS_NEXT_BUTTON,
	GRAPHICS_UI_APACHE_COMBAT_MISSIONS_NEXT_MASK,

	////////////////////////////////////////
	//
	// GUNSHIPS SCREEN
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_GUNSHIPS_APACHE_BUTTON,
	GRAPHICS_UI_APACHE_GUNSHIPS_HAVOC_BUTTON,
	GRAPHICS_UI_APACHE_GUNSHIPS_APACHE_UNSELECTED_BUTTON,
	GRAPHICS_UI_APACHE_GUNSHIPS_HAVOC_UNSELECTED_BUTTON,
	GRAPHICS_UI_APACHE_GUNSHIPS_CONNECTING_BUTTON,

	////////////////////////////////////////
	//
	// PLANNER SCREEN
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_PLANNER_BACK_BUTTON_UNSELECTED,
	GRAPHICS_UI_APACHE_PLANNER_BACK_BUTTON_SELECTED,
	GRAPHICS_UI_APACHE_PLANNER_FORWARD_BUTTON_UNSELECTED,
	GRAPHICS_UI_APACHE_PLANNER_FORWARD_BUTTON_SELECTED,
	GRAPHICS_UI_APACHE_PLANNER_ZOOM_IN_BUTTON_UNSELECTED,
	GRAPHICS_UI_APACHE_PLANNER_ZOOM_IN_BUTTON_SELECTED,
	GRAPHICS_UI_APACHE_PLANNER_ZOOM_OUT_BUTTON_UNSELECTED,
	GRAPHICS_UI_APACHE_PLANNER_ZOOM_OUT_BUTTON_SELECTED,
	GRAPHICS_UI_APACHE_PLANNER_GOTO_BUTTON_UNSELECTED,
	GRAPHICS_UI_APACHE_PLANNER_GOTO_BUTTON_SELECTED,
	GRAPHICS_UI_APACHE_PLANNER_VIEW_BUTTON_UNSELECTED,
	GRAPHICS_UI_APACHE_PLANNER_VIEW_BUTTON_SELECTED,

	////////////////////////////////////////
	//
	// FARP SCREENS
	//
	////////////////////////////////////////

	GRAPHICS_UI_APACHE_AIRBASE_SCREEN,
	GRAPHICS_UI_APACHE_FARP_SCREEN,
	GRAPHICS_UI_APACHE_SHIP_SCREEN,
	GRAPHICS_UI_APACHE_DYNAMIC_MISSIONS_SCREEN,

	////////////////////////////////////////
	//
	// UI\HAVOC
	//
	////////////////////////////////////////

	GRAPHICS_UI_HAVOC_CZONE_SCREEN,
	GRAPHICS_UI_HAVOC_GAME_OPTION_SCREEN,
	GRAPHICS_UI_HAVOC_LOADING_SCREEN,
	GRAPHICS_UI_HAVOC_MAIN_SCREEN,
	GRAPHICS_UI_HAVOC_TITLE_SCREEN,
	GRAPHICS_UI_HAVOC_CAMPAIGN_OVER_SCREEN,

	////////////////////////////////////////
	//
	// MAIN SCREEN BUTTONS
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// GAME OPTION SCREEN
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// COMBAT ZONE SCREEN
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// COMBAT MISSIONS SCREEN
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// GUNSHIPS SCREEN
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// PLANNER SCREEN
	//
	////////////////////////////////////////

	////////////////////////////////////////
	//
	// FARP SCREENS
	//
	////////////////////////////////////////

	GRAPHICS_UI_HAVOC_AIRBASE_SCREEN,
	GRAPHICS_UI_HAVOC_FARP_SCREEN,
	GRAPHICS_UI_HAVOC_SHIP_SCREEN,
	GRAPHICS_UI_HAVOC_DYNAMIC_MISSIONS_SCREEN,
#endif

	////////////////////////////////////////
	//
	// UI\COMMON
	//
	////////////////////////////////////////

	GRAPHICS_UI_COMMON_SESSION_BRIEFING_OVERLAY,

	GRAPHICS_UI_COMMON_STATUS_BALANCE_OF_POWER_OVERLAY,
	GRAPHICS_UI_COMMON_GROUPS_GUNSHIPS_OVERLAY,
	GRAPHICS_UI_COMMON_MISSIONS_TASKS_OVERLAY,
	GRAPHICS_UI_COMMON_GROUPS_VERTICAL_LINE_OVERLAY,
	GRAPHICS_UI_COMMON_UNKNOWN_AIRPORT_ICON,

	GRAPHICS_UI_COMMON_AVAILABLE_MISSIONS_SCREEN,
	GRAPHICS_UI_COMMON_AVAILABLE_GAMES_SCREEN,
	GRAPHICS_UI_COMMON_AVAILABLE_GAMES_SCREEN_MAGAZINE_DEMO,

	GRAPHICS_UI_COMMON_US_AAA_ICON,
	GRAPHICS_UI_COMMON_US_APC_ICON,
	GRAPHICS_UI_COMMON_US_ARTILLERY_ICON,
	GRAPHICS_UI_COMMON_US_BUILDING_ICON,
	GRAPHICS_UI_COMMON_US_HELICOPTER_ICON,
	GRAPHICS_UI_COMMON_US_FARP_ICON,
	GRAPHICS_UI_COMMON_US_FIXED_WING_ICON,
	GRAPHICS_UI_COMMON_US_FARP_MISSION_ICON,
	GRAPHICS_UI_COMMON_US_JET_ICON,
	GRAPHICS_UI_COMMON_US_LANDED_FARP_ICON,
	GRAPHICS_UI_COMMON_US_LANDED_RUNWAY_ICON,
	GRAPHICS_UI_COMMON_US_LANDED_SHIP_ICON,
	GRAPHICS_UI_COMMON_US_PLAYER_MISSION_ICON,
	GRAPHICS_UI_COMMON_US_RUNWAY_MISSION_ICON,
	GRAPHICS_UI_COMMON_US_RUNWAY_ICON,
	GRAPHICS_UI_COMMON_US_SAM_ICON,
	GRAPHICS_UI_COMMON_US_SHIP_ICON,
	GRAPHICS_UI_COMMON_US_SHIP_MISSION_ICON,
	GRAPHICS_UI_COMMON_US_SMALL_4X4_ICON,
	GRAPHICS_UI_COMMON_US_SMALL_8X8_ICON,
	GRAPHICS_UI_COMMON_US_TANK_ICON,
	GRAPHICS_UI_COMMON_US_TRUCK_ICON,
	GRAPHICS_UI_COMMON_US_USER_ICON,
	GRAPHICS_UI_COMMON_US_WAYPOINT_NAVIGATION_ICON,
	GRAPHICS_UI_COMMON_US_WAYPOINT_TARGET_ICON,
	GRAPHICS_UI_COMMON_US_WAYPOINT_ADD_ICON,
	GRAPHICS_UI_COMMON_US_WAYPOINT_SELECTED_ICON,
	GRAPHICS_UI_COMMON_US_GREY_FARP_ICON,
	GRAPHICS_UI_COMMON_US_GREY_RUNWAY_ICON,
	GRAPHICS_UI_COMMON_US_GREY_SHIP_ICON,
	GRAPHICS_UI_COMMON_US_MULTIPLAYER_ICON,

	GRAPHICS_UI_COMMON_CIS_AAA_ICON,
	GRAPHICS_UI_COMMON_CIS_APC_ICON,
	GRAPHICS_UI_COMMON_CIS_ARTILLERY_ICON,
	GRAPHICS_UI_COMMON_CIS_BUILDING_ICON,
	GRAPHICS_UI_COMMON_CIS_HELICOPTER_ICON,
	GRAPHICS_UI_COMMON_CIS_FARP_ICON,
	GRAPHICS_UI_COMMON_CIS_FIXED_WING_ICON,
	GRAPHICS_UI_COMMON_CIS_FARP_MISSION_ICON,
	GRAPHICS_UI_COMMON_CIS_JET_ICON,
	GRAPHICS_UI_COMMON_CIS_LANDED_FARP_ICON,
	GRAPHICS_UI_COMMON_CIS_LANDED_RUNWAY_ICON,
	GRAPHICS_UI_COMMON_CIS_LANDED_SHIP_ICON,
	GRAPHICS_UI_COMMON_CIS_PLAYER_MISSION_ICON,
	GRAPHICS_UI_COMMON_CIS_RUNWAY_MISSION_ICON,
	GRAPHICS_UI_COMMON_CIS_RUNWAY_ICON,
	GRAPHICS_UI_COMMON_CIS_SAM_ICON,
	GRAPHICS_UI_COMMON_CIS_SHIP_ICON,
	GRAPHICS_UI_COMMON_CIS_SHIP_MISSION_ICON,
	GRAPHICS_UI_COMMON_CIS_SMALL_4X4_ICON,
	GRAPHICS_UI_COMMON_CIS_SMALL_8X8_ICON,
	GRAPHICS_UI_COMMON_CIS_TANK_ICON,
	GRAPHICS_UI_COMMON_CIS_TRUCK_ICON,
	GRAPHICS_UI_COMMON_CIS_USER_ICON,
	GRAPHICS_UI_COMMON_CIS_WAYPOINT_NAVIGATION_ICON,
	GRAPHICS_UI_COMMON_CIS_WAYPOINT_TARGET_ICON,
	GRAPHICS_UI_COMMON_CIS_WAYPOINT_ADD_ICON,
	GRAPHICS_UI_COMMON_CIS_WAYPOINT_SELECTED_ICON,
	GRAPHICS_UI_COMMON_CIS_GREY_FARP_ICON,
	GRAPHICS_UI_COMMON_CIS_GREY_RUNWAY_ICON,
	GRAPHICS_UI_COMMON_CIS_GREY_SHIP_ICON,
	GRAPHICS_UI_COMMON_CIS_MULTIPLAYER_ICON,

	GRAPHICS_UI_COMMON_UP_ARROW_UNSELECTED,
	GRAPHICS_UI_COMMON_UP_ARROW_SELECTED,
	GRAPHICS_UI_COMMON_DOWN_ARROW_UNSELECTED,
	GRAPHICS_UI_COMMON_DOWN_ARROW_SELECTED,

	GRAPHICS_UI_COMMON_BASEMASK,
	GRAPHICS_UI_COMMON_APACHE_HAVOC_V,

	GRAPHICS_UI_COMMON_DEBRIEF_TOP_LINE,
	GRAPHICS_UI_COMMON_DEBRIEF_BOTTOM_LINE,

	////////////////////////////////////////
	//
	// AITOOL GRAPHICS
	//
	////////////////////////////////////////

	GRAPHICS_UI_COMMON_AITOOL_SCREEN,

	NUM_GRAPHICS_FILE_SPECIFIERS
};

typedef enum GRAPHICS_FILE_SPECIFIERS graphics_file_specifiers;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define get_graphics_file(FILE_SPEC) (graphics_files[(FILE_SPEC)])

#define get_graphics_file_data(FILE_SPEC) (graphics_files[(FILE_SPEC)].data)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

extern int get_uninstalled_graphics_file_count (int pass_conversion);

extern int install_graphics_files (int pass_conversion);

extern void uninstall_graphics_files (void);

extern void mopen_all_graphics_files (int pass_conversion);

extern void mclose_all_graphics_files (void);

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#endif
