/*
 * ap_mfd_buttons.h
 *
 *  Created on: 05.sep.2009
 *      Author: arneh
 */

#ifndef AP_MFD_BUTTONS_H_
#define AP_MFD_BUTTONS_H_

typedef enum {
	MFD_BUTTON_ADF,
	MFD_BUTTON_ASE,
	MFD_BUTTON_CHAN,
	MFD_BUTTON_CL,
	MFD_BUTTON_CODE,
	MFD_BUTTON_DMS,
	MFD_BUTTON_ETF,
	MFD_BUTTON_FUEL,
	MFD_BUTTON_ENG,
	MFD_BUTTON_FLT,
	MFD_BUTTON_PERF,
	MFD_BUTTON_SYS,
	MFD_BUTTON_UTIL,
	MFD_BUTTON_VERS,
	MFD_BUTTON_WCA,
	MFD_BUTTON_WPN,

	MFD_BUTTON_MENU_TSD,
	MFD_BUTTON_MENU_ENG,
	MFD_BUTTON_MENU_CHECKLIST,
	MFD_BUTTON_MENU_FLT,
	MFD_BUTTON_MENU_FUEL,
	MFD_BUTTON_MENU_ADF,
	MFD_BUTTON_MENU_WPN,
	MFD_BUTTON_MENU_TADS,

	MFD_BUTTON_PAGE1,
	MFD_BUTTON_PAGE2,
	MFD_BUTTON_PAGE3,
	MFD_BUTTON_PAGE4,

	// Acquisition Source
	MFD_BUTTON_ACQ_SRC,
	MFD_BUTTON_ACQ_PHS,
	MFD_BUTTON_ACQ_GHS,
	MFD_BUTTON_ACQ_SKR,
	MFD_BUTTON_ACQ_RFI,
	MFD_BUTTON_ACQ_FCR,
	MFD_BUTTON_ACQ_FXD,
	MFD_BUTTON_ACQ_TADS,
	MFD_BUTTON_ACQ_WPT_TP,

	// TSD pages
	MFD_BUTTON_RPT,
	MFD_BUTTON_PSN,
	MFD_BUTTON_PP,
	MFD_BUTTON_COORD,
	MFD_BUTTON_TSD_UTIL,
	MFD_BUTTON_HDG,
	MFD_BUTTON_REC,
	MFD_BUTTON_JAM,
	MFD_BUTTON_SHOW,
	MFD_BUTTON_SC,
	MFD_BUTTON_CTR,
	MFD_BUTTON_FRZ,
	MFD_BUTTON_PHASE_NAV,
	MFD_BUTTON_PHASE_ATK,
	MFD_BUTTON_ZN,
	MFD_BUTTON_WPT,
	MFD_BUTTON_RTE,
	MFD_BUTTON_THRT,

	MFD_BUTTON_TSD_SCALE_50,
	MFD_BUTTON_TSD_SCALE_25,
	MFD_BUTTON_TSD_SCALE_10,
	MFD_BUTTON_TSD_SCALE_5,

	MFD_BUTTON_POINT_INPUT,
	MFD_BUTTON_IDENT_INPUT,
	MFD_BUTTON_FREE_INPUT,
	MFD_BUTTON_ADD,
	MFD_BUTTON_DEL,
	MFD_BUTTON_DELETE,
	MFD_BUTTON_NEW,
	MFD_BUTTON_END,
	MFD_BUTTON_EDT,
	MFD_BUTTON_XMIT,
	MFD_BUTTON_SEND,
	MFD_BUTTON_YES,
	MFD_BUTTON_NO,
	MFD_BUTTON_NOW,
	MFD_BUTTON_STO,
	MFD_BUTTON_UP,
	MFD_BUTTON_DOWN,
	MFD_BUTTON_TSD_WAYPOINT_SELECT,

	MFD_BUTTON_RTE_DIR,
	MFD_BUTTON_RTE_RVW,
	MFD_BUTTON_RTE_RTM,

	MFD_BUTTON_RTM_REVERSE_ROUTE,

	MFD_BUTTON_WPT_TYPE_WP,
	MFD_BUTTON_WPT_TYPE_HZ,
	MFD_BUTTON_WPT_TYPE_CM,

	// radar page
	MFD_BUTTON_C_SCP,
	MFD_BUTTON_NTS,
	MFD_BUTTON_TGT,
	MFD_BUTTON_ELEV,
	MFD_BUTTON_ZOOM,
	MFD_BUTTON_RF_HO,

	MFD_BUTTON_RADAR_SCAN_LEFT,
	MFD_BUTTON_RADAR_SCAN_RIGHT,
	MFD_BUTTON_RADAR_SCAN_UP,
	MFD_BUTTON_RADAR_SCAN_DOWN,

	// radar TPM page
	MFD_BUTTON_TPM_PROF,
	MFD_BUTTON_TPM_PROF_GEOM,
	MFD_BUTTON_TPM_PROF_ARITH,
	MFD_BUTTON_TPM_PROF_TEST,
	MFD_BUTTON_TPM_LINES,
	MFD_BUTTON_TPM_LINES_0,
	MFD_BUTTON_TPM_LINES_1,
	MFD_BUTTON_TPM_LINES_2,
	MFD_BUTTON_TPM_LINES_3,
	MFD_BUTTON_TPM_LINES_4,
	MFD_BUTTON_TPM_CLEARANCE,
	MFD_BUTTON_TPM_CLEARANCE_20,
	MFD_BUTTON_TPM_CLEARANCE_50,
	MFD_BUTTON_TPM_CLEARANCE_100,
	MFD_BUTTON_TPM_CLEARANCE_200,
	MFD_BUTTON_ELEV_NEAR,
	MFD_BUTTON_ELEV_FAR,

	// radar UTIL page
	MFD_BUTTON_FCR_RFI,
	MFD_BUTTON_FCR_FCR,
	MFD_BUTTON_FCR_RFI_MODE_ALL,
	MFD_BUTTON_FCR_RFI_MODE_HOSTILE,
	MFD_BUTTON_FCR_PRIORITY_SCHEME,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY,
	MFD_BUTTON_FCR_MMA_PINNED,
	MFD_BUTTON_FCR_MMA_NORM,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_AUTO,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_1,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_2,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_3,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_4,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_5,
	MFD_BUTTON_FCR_TERRAIN_SENSIVITY_6,

	// TADS page
	MFD_BUTTON_TADS_ZOOM_W,
	MFD_BUTTON_TADS_ZOOM_N,
	MFD_BUTTON_TADS_ZOOM_Z,
	MFD_BUTTON_TADS_SHARPNESS,

	// weapon page
	MFD_BUTTON_TRAIN,
	MFD_BUTTON_LRFD_FIRST,
	MFD_BUTTON_LRFD_LAST,
	MFD_BUTTON_GUN,
	MFD_BUTTON_MSL,
	MFD_BUTTON_ATA,
	MFD_BUTTON_RKT,
	MFD_BUTTON_MANRNG_INPUT,
	MFD_BUTTON_BORESIGHT,
	MFD_BUTTON_GRAYSCALE,

	MFD_BUTTON_GUN_BURST_10,
	MFD_BUTTON_GUN_BURST_20,
	MFD_BUTTON_GUN_BURST_50,
	MFD_BUTTON_GUN_BURST_100,
	MFD_BUTTON_GUN_BURST_ALL,
	MFD_BUTTON_GUN_MODE_NORM,
	MFD_BUTTON_GUN_MODE_FXD,
	MFD_BUTTON_RANGE_INPUT,

	MFD_BUTTON_RKT_QTY,
	MFD_BUTTON_RKT_QTY_1,
	MFD_BUTTON_RKT_QTY_2,
	MFD_BUTTON_RKT_QTY_4,
	MFD_BUTTON_RKT_QTY_8,
	MFD_BUTTON_RKT_QTY_12,
	MFD_BUTTON_RKT_QTY_24,
	MFD_BUTTON_RKT_QTY_ALL,
	MFD_BUTTON_RKT_ZONE_CTR,
	MFD_BUTTON_RKT_ZONE_QUAD,
	MFD_BUTTON_RKT_ZONE_PERIMITER,

	MFD_BUTTON_MSL_POWER_ALL,
	MFD_BUTTON_MSL_POWER_AUTO,
	MFD_BUTTON_MSL_POWER_NONE,
	MFD_BUTTON_SAL_SELECT_AUTO,
	MFD_BUTTON_MSL_PRI,
	MFD_BUTTON_MSL_ALT,
	MFD_BUTTON_MSL_CHAN_SEL,
	MFD_BUTTON_LOBL_INHIBIT,
	MFD_BUTTON_2ND_TARGET_INHIBIT,
	MFD_BUTTON_MSL_TYPE_RF,
	MFD_BUTTON_MSL_TYPE_SAL,
	MFD_BUTTON_MSL_MODE_NORM,
	MFD_BUTTON_MSL_MODE_RIPL,
	MFD_BUTTON_MSL_MODE_MAN,
	MFD_BUTTON_MSL_TRAJ_DIR,
	MFD_BUTTON_MSL_TRAJ_HI,
	MFD_BUTTON_MSL_TRAJ_LO,
	MFD_BUTTON_MSL_TRAIN,

	// flight page buttons
	MFD_BUTTON_SET,
	MFD_BUTTON_PITCH_W,

	// arrow sprites
	MFD_BUTTON_PITCH_DATUM_UP,
	MFD_BUTTON_PITCH_DATUM_DOWN,

	// fuel page buttons
	MFD_BUTTON_L_AUX,
	MFD_BUTTON_R_AUX,
	MFD_BUTTON_FUEL_TRANS_FWD,
	MFD_BUTTON_FUEL_TRANS_OFF,
	MFD_BUTTON_FUEL_TRANS_AFT,
	MFD_BUTTON_FUEL_TRANS_XFER_MAN,
	MFD_BUTTON_FUEL_TRANS_XFER_AUTO,
	MFD_BUTTON_AUX_GAL,
	MFD_BUTTON_BOOST,
	MFD_BUTTON_FUEL_CROSS_FWD,
	MFD_BUTTON_FUEL_CROSS_NORM,
	MFD_BUTTON_FUEL_CROSS_AFT,
	MFD_BUTTON_FUEL_TYPE,
	MFD_BUTTON_FUEL_JP4,
	MFD_BUTTON_FUEL_JP5,
	MFD_BUTTON_FUEL_JP8,

	// checklist buttons
	MFD_BUTTON_CHECKLIST_THROUGH_FLIGHT,
	MFD_BUTTON_CHECKLIST_PERF_DATA1,
	MFD_BUTTON_CHECKLIST_PERF_DATA2,
	MFD_BUTTON_CHECKLIST_AFTER_STARTING_APU,
	MFD_BUTTON_CHECKLIST_BEFORE_STARTING_ENG,
	MFD_BUTTON_CHECKLIST_STARTING_ENG,
	MFD_BUTTON_CHECKLIST_BEFORE_TAXI,
	MFD_BUTTON_CHECKLIST_TAXI,
	MFD_BUTTON_CHECKLIST_BEFORE_TO,
	MFD_BUTTON_CHECKLIST_BEFORE_LANDING,
	MFD_BUTTON_CHECKLIST_AFTER_LANDING,
	MFD_BUTTON_CHECKLIST_ENGINE_SHUTDOWN,
	MFD_BUTTON_CHECKLIST_RAPID_REFUELING,
	MFD_BUTTON_CHECKLIST_RAPID_REARMING,
	MFD_BUTTON_CHECKLIST_FCR_OPR_CHECK,
	MFD_BUTTON_CHECKLIST_PILOT_IHADDS_BORE,
	MFD_BUTTON_CHECKLIST_FLIR_OPR_CHECK,
	MFD_BUTTON_CHECKLIST_MANUAL_DRIFT_NULL,
	MFD_BUTTON_CHECKLIST_PECHAN_REALLIGN,
	MFD_BUTTON_CHECKLIST_CUE_UPDATE_PROC,
	MFD_BUTTON_CHECKLIST_TADS_OPR_CHECK,
	MFD_BUTTON_CHECKLIST_TADS_OUTFR_BORE,
	MFD_BUTTON_CHECKLIST_FLIGHT_CONTROL,
	MFD_BUTTON_CHECKLIST_RETURN,

	MFD_BUTTON_ADF_TUNE,
	MFD_BUTTON_ADF_TONE,
	MFD_BUTTON_ADF_IDENTIFY,
	MFD_BUTTON_ADF_ON_OFF,
	MFD_BUTTON_ADF_MODE_ANT,
	MFD_BUTTON_ADF_MODE_ADF,
	MFD_BUTTON_ADF_FREQ,
	MFD_BUTTON_ADF_TEST,
	MFD_BUTTON_ADF_LAST,
	MFD_BUTTON_ADF_PRSET,
	MFD_BUTTON_ADF_ID,
	MFD_BUTTON_ADF_500,
	MFD_BUTTON_ADF_2182,
	MFD_BUTTON_ADF_PRSET_SELECT,

	NUM_PUSHBUTTON_TYPES
} mfd_push_button_types;

typedef enum {
	// six each for top, left, right and bottom
	BTN_T1, BTN_T2, BTN_T3,	BTN_T4,	BTN_T5,	BTN_T6,
	BTN_L1,	BTN_L2,	BTN_L3,	BTN_L4,	BTN_L5,	BTN_L6,
	BTN_R1,	BTN_R2,	BTN_R3,	BTN_R4,	BTN_R5,	BTN_R6,
	BTN_M,  BTN_B1,	BTN_B2,	BTN_B3,	BTN_B4,	BTN_B5,  // M is menu button
	BTN_FCR, BTN_WPN, BTN_TSD, BTN_AC, BTN_COM, BTN_VID, NO_BTN,
	NUM_PUSHBUTTONS,
} mfd_button_labels;

typedef struct {
	const char* sprite;
	const char* label;
	const char* label2;
	int new_page_arrow;
	int vertical;
	int box_on_click;

	// returns TRUE if press was successful
	int (*push_function)(mfd_push_button_types, mfd_button_labels);
} mfd_push_button;

//extern mfd_push_button mfd_push_button_definitions[NUM_PUSHBUTTON_TYPES];

// extern mfd_push_button* mfd_button_handlers[NUM_PUSHBUTTONS];

void initialise_apache_pushbuttons(void);

void setup_apache_mfd_buttons(mfd_modes mfd_mode, mfd_locations location, int is_sub_mode);

void render_apache_mfd_buttons(mfd_modes mfd_mode, mfd_locations location, rgb_colour fg_col, rgb_colour bg_col, rgb_colour clear_colour, int shade_background);
void draw_apache_mfd_page_number_buttons(mfd_locations location, int backward, int forward);

void handle_apache_mfd_click(void);
void swap_apache_mfd_focus(void);
void swap_apache_seat_mfd_focus(void);

#endif /* AP_MFD_BUTTONS_H_ */
