#define origcount 352

// test test 123

const char* standard_key_mapping[origcount] = {
"#######################################################################################\n",
"# Key Mapping File                                                                    #\n",
"# If you want to deactivate a command, just insert a '#' at the beginning of the line #\n",
"#                                                                                     #\n",
"# Everything in here is case-sensitive !!                                             #\n",
"#                                                                                     #\n",
"# Right now there are no checks fo duplicate key assignments, so take care !!         #\n",
"#######################################################################################\n",
"#																						\n",
"# Padlock target																		\n",
"virtual_cockpit_track_target		1	MODIFIER_NONE		KEY_STATE_DOWN				\n",
"# Set Left/Right Hand Side MFD to ground radar mode									\n",
"select_lhs_ground_radar_main_mfd	1	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"select_rhs_ground_radar_main_mfd	1	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"# ???																					\n",
"set_padlock_view			2	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Set Left/Right Hand Side MFD to air radar mode										\n",
"select_lhs_air_radar_mfd		2	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_air_radar_mfd		2	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# ???																					\n",
"set_padlock_view			3	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Set Left/Right Hand Side MFD to tads mode											\n",
"select_lhs_tads_mfd			3	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_tads_mfd			3	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# ???																					\n",
"set_padlock_view			4	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Set Left/Right Hand Side MFD to tsd mode												\n",
"select_lhs_tsd_mfd			4	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"select_rhs_tsd_mfd			4	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"# ???																					\n",
"set_padlock_view			5	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Set Left/Right Hand Side MFD to ase mode												\n",
"select_lhs_ase_mfd			5	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"select_rhs_ase_mfd			5	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"# ???																					\n",
"set_padlock_view			6	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Set Left/Right Hand Side MFD to weapon mode											\n",
"select_lhs_weapon_mfd			6	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_weapon_mfd			6	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# Set Left/Right Hand Side MFD to system mode											\n",
"select_lhs_system_mfd			7	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_system_mfd			7	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# Set the Field of View to the 'Low' value												\n",
"lo_fov					7	MODIFIER_NONE		KEY_STATE_DOWN							\n",
"# Cheat, gives your AC an air to ground loadout										\n",
"load_air_to_ground_weapons		7	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"# Set the Field of View to the 'Standard' value										\n",
"std_fov					8	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Cheat, gives your AC an air to air loadout											\n",
"load_air_to_air_weapons			8	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"# Set Left/Right Hand Side MFD to engine mode											\n",
"select_lhs_engine_mfd			8	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_engine_mfd			8	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# Set the Field of View to the 'High' value											\n",
"hi_fov					9	MODIFIER_NONE		KEY_STATE_DOWN							\n",
"# Cheat, gives your AC an scout loadout												\n",
"load_scout_weapons			9	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"# Set Left/Right Hand Side MFD to flight mode											\n",
"select_lhs_flight_main_mfd		9	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_flight_main_mfd		9	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# ???																					\n",
"set_padlock_view			0	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# ???																					\n",
"special_cockpit_toggle			0	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"# Set Left/Right Hand Side MFD to mission mode											\n",
"select_lhs_mission_mfd			0	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"select_rhs_mission_mfd			0	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# Outside panning																		\n",
"adjust_view_left			LEFT	MODIFIER_LEFT_ALT	KEY_STATE_EITHER				\n",
"adjust_view_right			RIGHT	MODIFIER_LEFT_ALT	KEY_STATE_EITHER				\n",
"adjust_view_up				UP	MODIFIER_LEFT_ALT	KEY_STATE_EITHER					\n",
"adjust_view_down			DOWN	MODIFIER_LEFT_ALT	KEY_STATE_EITHER				\n",
"adjust_view_zoom_in			PERIOD	MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"adjust_view_zoom_out			COMMA	MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"# Sets 3D to 640*480																	\n",
"set_default_3d_resolutions		F1	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"# Forward View																			\n",
"forward_view				F1	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Toggles No Cockpit View																\n",
"toggle_draw_cockpit_graphics		F1	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"# Toggles unscaled HUD																	\n",
"toggle_unscaled_displays		F1	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# Instrument view																		\n",
"instrument_view				F2	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"# Toggles HUD in external view															\n",
"toggle_display_hud_on_external_view	F2	MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"# ???																					\n",
"toggle_draw_overlaid_instruments	F2	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"# Toggles see-through cockpit struts													\n",
"toggle_glass_cockpit			F2	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"# Toggles HUD view																		\n",
"hud_view				F2	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN							\n",
"decrease_cockpit_detail			F3	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"decrease_3d_resolutions			F3	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"look_at_special1			F3	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"increase_cockpit_detail			F4	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"increase_3d_resolutions			F4	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"look_at_special2			F4	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# 'Side' setting when viewing all available objects									\n",
"next_side				F5	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN						\n",
"previous_side				F5	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"# View all available objects															\n",
"view_all				F5	MODIFIER_LEFT_ALT	KEY_STATE_DOWN							\n",
"# Outside view																			\n",
"players_gunship				F5	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"# Target View																			\n",
"players_target				F6	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Wingman View																			\n",
"view_wingmen				F6	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"# Next category when viewing all available objects										\n",
"next_category				F6	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"previous_category			F6	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"# Next type when viewing all available objects											\n",
"next_type				F7	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN						\n",
"players_weapon				F7	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"previous_type				F7	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"view_players				F7	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"next_object				F8	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"# View padlocked object																\n",
"players_padlock				F8	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"previous_object				F8	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"view_available_gunships			F8	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"# Chase camera																			\n",
"chase_camera				F9	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"reset_chase_camera_position		F9	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"toggle_chase_camera_lock_rotate		F9	MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"# Fly by camera																		\n",
"fly_by_camera				F10	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Drop Camera																			\n",
"drop_camera				F10	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"# Static camera																		\n",
"static_camera				F10	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"# Weapon view																			\n",
"weapon_camera				F10	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"# Crew Camera																			\n",
"crew_camera				F11	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"# Auto Action View																		\n",
"camera_auto_edit			F11	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Cinematic camera																		\n",
"cinematic_camera			F11	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"# Toggle 'view objects' menu															\n",
"toggle_view_menu			F12	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"# Toggle viewed object text															\n",
"toggle_object_text			F12	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"# Toggle inset target																	\n",
"toggle_inset_target			F12	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"# Toggle intelligence messages															\n",
"toggle_display_in_flight_intelligence_messages	F12	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN\n",
"# ???																					\n",
"look_rel_left				LEFT	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"look_rel_right				RIGHT	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"look_rel_up				UP	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"look_rel_down				DOWN	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"look_abs_left				LEFT	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"look_abs_right				RIGHT	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"look_abs_up				UP	MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER					\n",
"look_abs_down				DOWN	MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER				\n",
"# ???																					\n",
"release_virtual_cockpit			LALT	MODIFIER_LEFT_ALT	KEY_STATE_UP			\n",
"# ???																					\n",
"look_abs_left				LEFT	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"look_abs_right				RIGHT	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"forward_view				UP	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"instrument_view				DOWN	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"look_at_special1			LEFT	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"look_at_special2			RIGHT	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"# Set to pilot position																\n",
"set_pilot_seat_position			UP	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"# Set to CP/G position																	\n",
"set_co_pilot_seat_position		DOWN	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"# Switch seat position																	\n",
"switch_seat_position			ESCAPE		MODIFIER_NONE	KEY_STATE_DOWN				\n",
"# Wideview keys																		\n",
"wide_cockpit_toggle			BACKSLASH	MODIFIER_NONE	KEY_STATE_DOWN				\n",
"wide_cockpit_edit			BACKSLASH	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"wide_cockpit_save			BACKSLASH	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"hokum_pilot_view1			DELETE		MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"hokum_pilot_view2			END	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"hokum_pilot_view3			NEXT	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"next_view_range				EQUALS	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"previous_view_range			MINUS		MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"next_view_range				NUMPADPLUS	MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"previous_view_range			NUMPADMINUS	MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"look_rel_left				NUMPAD4		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"look_rel_right				NUMPAD6		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"look_rel_up				NUMPAD8		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"look_rel_down				NUMPAD2		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"look_abs_left				NUMPAD4		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"look_abs_right				NUMPAD6		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"look_abs_up				NUMPAD8		MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER			\n",
"look_abs_down				NUMPAD2		MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER			\n",
"adjust_view_left			NUMPAD4		MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"adjust_view_right			NUMPAD6		MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"adjust_view_up				NUMPAD8		MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"adjust_view_down			NUMPAD2		MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"wide_cockpit_toggle			BACKSLASH	MODIFIER_NONE		KEY_STATE_DOWN			\n",
"wide_cockpit_edit			BACKSLASH	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"wide_cockpit_save			BACKSLASH	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"comms_shortcut_attack_my_target		A	MODIFIER_LEFT_SHIFT		KEY_STATE_DOWN		\n",
"toggle_ase_auto_page			A	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"toggle_ase_auto_page			A	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"hokum_pilot_view2			B	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"launch_chaff				C	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"toggle_auto_countermeasures		C	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"select_next_tsd_declutter_level		D	MODIFIER_NONE		KEY_STATE_DOWN			\n",
"select_previous_tsd_declutter_level	D	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN			\n",
"select_next_tsd_ase_range		E	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"select_previous_tsd_ase_range		E	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"eject					E	MODIFIER_LEFT_ALT	KEY_STATE_DOWN							\n",
"launch_flare				F	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"fire_extinguisher_release		F	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"toggle_gear				G	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"toggle_infra_red_jammer			I	MODIFIER_NONE		KEY_STATE_DOWN				\n",
"toggle_radar_jammer			J	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"set_next_hud_colour			K	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"set_prev_hud_colour			K	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"toggle_hud_enlarge			K	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN					\n",
"toggle_lobl_loal			L	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"acknowledge_master_caution		M	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"toggle_night_vision_system		N	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"hokum_pilot_view3			N	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"set_hud_bob_up_overlay			O	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"clear_hud_bob_up_overlay		O	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"toggle_blurred_main_rotors_visible_from_cockpit	R	MODIFIER_LEFT_ALT	KEY_STATE_DOWN\n",
"rearm_refuel_repair			R	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN				\n",
"increase_rocket_salvo_size		S	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"decrease_rocket_salvo_size		S	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"toggle_ground_stabilisation		S	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"toggle_navigation_lights		V	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"hokum_pilot_view1			V	MODIFIER_LEFT_ALT	KEY_STATE_DOWN						\n",
"set_next_waypoint			W	MODIFIER_NONE		KEY_STATE_DOWN						\n",
"set_prev_waypoint			W	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN						\n",
"toggle_wiper_on				Y	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"toggle_intermittent_wipe		Y	MODIFIER_LEFT_ALT	KEY_STATE_DOWN					\n",
"launch_weapon				SPACE		MODIFIER_NONE	KEY_STATE_EITHER				\n",
"select_next_weapon			BACKSPACE	MODIFIER_NONE	KEY_STATE_DOWN					\n",
"select_previous_weapon			BACKSPACE	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN			\n",
"weapons_safe				BACKSPACE	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"select_cannon				BACKSPACE	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"select_target_acquisition_system_off		DECIMAL	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN\n",
"select_target_acquisition_system_ground_radar	INSERT	MODIFIER_NONE		KEY_STATE_DOWN\n",
"select_target_acquisition_system_air_radar	HOME	MODIFIER_NONE		KEY_STATE_DOWN	\n",
"select_target_acquisition_system_flir		DELETE	MODIFIER_NONE		KEY_STATE_DOWN	\n",
"select_target_acquisition_system_dtv		END	MODIFIER_NONE		KEY_STATE_DOWN		\n",
"select_target_acquisition_system_dvo		NEXT	MODIFIER_NONE		KEY_STATE_DOWN	\n",
"select_target_acquisition_system_ihadss		PRIOR	MODIFIER_NONE		KEY_STATE_DOWN\n",
"select_target_acquisition_system_hidss		PRIOR	MODIFIER_NONE		KEY_STATE_DOWN	\n",
"select_target_acquisition_system_periscope	NEXT	MODIFIER_NONE		KEY_STATE_DOWN	\n",
"select_target_acquisition_system_hms		PRIOR	MODIFIER_NONE		KEY_STATE_DOWN	\n",
"steer_left				NUMPAD4		MODIFIER_NONE		KEY_STATE_EITHER				\n",
"steer_left_fast				NUMPAD4		MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER		\n",
"steer_left_fine				NUMPAD4		MODIFIER_LEFT_ALT	KEY_STATE_EITHER		\n",
"steer_right				NUMPAD6		MODIFIER_NONE		KEY_STATE_EITHER			\n",
"steer_right_fast			NUMPAD6		MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER			\n",
"steer_right_fine			NUMPAD6		MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"steer_up				NUMPAD8		MODIFIER_NONE		KEY_STATE_EITHER				\n",
"vsteer_up_fast				NUMPAD8		MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER			\n",
"steer_up_fine				NUMPAD8		MODIFIER_LEFT_ALT	KEY_STATE_EITHER			\n",
"steer_down				NUMPAD2		MODIFIER_NONE		KEY_STATE_EITHER				\n",
"steer_down_fast				NUMPAD2		MODIFIER_LEFT_SHIFT	KEY_STATE_EITHER		\n",
"steer_down_fine				NUMPAD2		MODIFIER_LEFT_ALT	KEY_STATE_EITHER		\n",
"inc_range				ADD		MODIFIER_NONE		KEY_STATE_DOWN						\n",
"inc_range_fast				ADD		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"dec_range				SUBTRACT	MODIFIER_NONE		KEY_STATE_DOWN					\n",
"dec_range_fast				SUBTRACT	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"steer_centre				NUMPAD5		MODIFIER_NONE		KEY_STATE_DOWN				\n",
"steer_centre				NUMPAD5		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"toggle_show_allied_targets		NUMPAD7		MODIFIER_NONE		KEY_STATE_DOWN			\n",
"inc_target_priority			NUMPAD9		MODIFIER_NONE		KEY_STATE_DOWN			\n",
"inc_target_priority_fast		NUMPAD9		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN			\n",
"vdec_target_priority			NUMPAD3		MODIFIER_NONE		KEY_STATE_DOWN			\n",
"dec_target_priority_fast		NUMPAD3		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN			\n",
"select_next_target			NUMPAD0		MODIFIER_NONE		KEY_STATE_DOWN				\n",
"select_previous_target			NUMPAD0		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN			\n",
"toggle_auto_target			NUMPAD1		MODIFIER_NONE		KEY_STATE_DOWN				\n",
"toggle_lock_target			NUMPADENTER	MODIFIER_NONE		KEY_STATE_DOWN				\n",
"toggle_lock_target			NUMPADENTER	MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"toggle_lock_target			NUMPADENTER	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"target_acquisition_system_misc_function1	MULTIPLY	MODIFIER_NONE	KEY_STATE_DOWN	\n",
"target_acquisition_system_misc_function2	DIVIDE		MODIFIER_NONE	KEY_STATE_DOWN	\n",
"select_next_lhs_mfd			LBRACKET	MODIFIER_NONE		KEY_STATE_DOWN			\n",
"select_previous_lhs_mfd			LBRACKET	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN		\n",
"toggle_lhs_mfd_on_off			LBRACKET	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN		\n",
"toggle_lhs_side_mfd_on_off		LBRACKET	MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"select_next_lhs_main_mfd		LBRACKET	MODIFIER_NONE		KEY_STATE_DOWN			\n",
"select_previous_lhs_main_mfd		LBRACKET	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN		\n",
"toggle_lhs_main_mfd_on_off		LBRACKET	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN		\n",
"select_next_rhs_main_mfd		RBRACKET	MODIFIER_NONE		KEY_STATE_DOWN			\n",
"select_previous_rhs_main		RBRACKET	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN			\n",
"toggle_rhs_main_mfd_on			RBRACKET	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN		\n",
"toggle_rhs_side_mfd_on_off		RBRACKET	MODIFIER_LEFT_ALT	KEY_STATE_DOWN			\n",
"select_next_rhs_mfd			RBRACKET	MODIFIER_NONE		KEY_STATE_DOWN			\n",
"select_previous_rhs_mfd			RBRACKET	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN		\n",
"toggle_rhs_mfd_on_off			RBRACKET	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN		\n",
"# Exit game																			\n",
"exit_apache_havoc			X		MODIFIER_LEFT_CONTROL	KEY_STATE_UP				\n",
"# Quit mission																			\n",
"ingame_quit_function			Q		MODIFIER_LEFT_CONTROL	KEY_STATE_UP			\n",
"# Toggles 2d/3d screen																	\n",
"toggle_in_flight_game_modes		RETURN		MODIFIER_NONE		KEY_STATE_DOWN		\n",
"# ???																					\n",
"campaign_screen_show_external_view_entity	RETURN	MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN	\n",
"# Take control of displayed gunship													\n",
"set_gunship_entity_to_external_view_entity	U	MODIFIER_NONE		KEY_STATE_DOWN		\n",
"# Time acceleration																	\n",
"set_small_inc_time_acceleration		EQUALS		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN\n",
"set_small_dec_time_acceleration		MINUS		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN\n",
"set_small_inc_time_acceleration		NUMPADPLUS	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN\n",
"set_small_dec_time_acceleration		NUMPADMINUS	MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN\n",
"# Toggle Pause																			\n",
"toggle_pause_time_acceleration		P		MODIFIER_NONE		KEY_STATE_DOWN			\n",
"# Take screenshow																		\n",
"save_screen_image_event			SYSRQ		MODIFIER_NONE		KEY_STATE_DOWN		\n",
"# Opens communication screen															\n",
"start_messaging_system			TAB		MODIFIER_NONE		KEY_STATE_DOWN				\n",
"# Displays last message																\n",
"display_last_received_message		TAB		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN		\n",
"# Cyclic																				\n",
"cyclic_left				LEFT		MODIFIER_NONE		KEY_STATE_EITHER			\n",
"cyclic_right				RIGHT		MODIFIER_NONE		KEY_STATE_EITHER			\n",
"cyclic_forward				UP		MODIFIER_NONE		KEY_STATE_EITHER				\n",
"cyclic_backward				DOWN		MODIFIER_NONE		KEY_STATE_EITHER		\n",
"# Collective																			\n",
"collective_forward			Q		MODIFIER_NONE		KEY_STATE_EITHER				\n",
"collective_backward			A		MODIFIER_NONE		KEY_STATE_EITHER			\n",
"collective_forward			EQUALS		MODIFIER_NONE		KEY_STATE_EITHER			\n",
"collective_backward			MINUS		MODIFIER_NONE		KEY_STATE_EITHER		\n",
"# Pedals																				\n",
"pedal_left				Z		MODIFIER_NONE		KEY_STATE_EITHER					\n",
"pedal_right				X		MODIFIER_NONE		KEY_STATE_EITHER				\n",
"# Sets Trim																			\n",
"set_trim_control			T		MODIFIER_NONE		KEY_STATE_DOWN					\n",
"# Clears trim																			\n",
"clear_trim_control			T		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"# Toggles rotor brake																	\n",
"toggle_rotor_brake			R		MODIFIER_NONE		KEY_STATE_DOWN					\n",
"# Toggles wheel brake																	\n",
"toggle_wheel_brake			B		MODIFIER_NONE		KEY_STATE_DOWN					\n",
"# Toggles auto hover																	\n",
"toggle_auto_hover			H		MODIFIER_NONE		KEY_STATE_DOWN					\n",
"toggle_auto_hover			H		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN					\n",
"# Toggles auto altitude hold															\n",
"toggle_altitude_lock			H		MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"# In/Decrease altitude hold values														\n",
"decrease_altitude_lock			J		MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"increase_altitude_lock			K		MODIFIER_LEFT_ALT	KEY_STATE_DOWN				\n",
"# Toggles autopilot																	\n",
"toggle_auto_pilot			G		MODIFIER_NONE		KEY_STATE_DOWN					\n",
"# Razorworks debug stuff																\n",
"load_dynamics_model			TAB		MODIFIER_LEFT_SHIFT	KEY_STATE_DOWN				\n",
"save_dynamics_model			TAB		MODIFIER_LEFT_CONTROL	KEY_STATE_DOWN			\n",
"# End\n"
};