// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "project.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
// CALLSIGNS ARRAY
// 

void initialise_speech_callsign_data (void)
{
	speech_array_types
		a = SPEECH_ARRAY_CALLSIGNS;

	speech_originator_types
		o;

	int
		max_items = NUM_GROUP_CALLSIGNS;

	//
	// SYSTEM
	//
	{				
		o = SPEECH_ORIGINATOR_SYSTEM;
	
		initialise_sample_index_array (a, o, max_items);
	}

	//
	// CO PILOT
	//
	{	
		o = SPEECH_ORIGINATOR_CO_PILOT;
		
		initialise_sample_index_array (a, o, max_items);
	}

	//
	// WINGMAN 
	//
	{	
		o = SPEECH_ORIGINATOR_WINGMAN1;
		
		initialise_sample_index_array (a, o, max_items);

		#if !DEMO_VERSION

		initialise_speech_data (a, o, GROUP_CALLSIGN_ANGEL, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_ANGEL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_ANGEL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_APOLLO, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_APOLLO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_APOLLO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_ARCHER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_ARCHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_ARCHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BANSHEE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_BANSHEE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_BANSHEE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BLOODHOUND, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_BLOODHOU, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_BLOODHOU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BULLDOG, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_BULLDOG, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_BULLDOG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHARGER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_CHARGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_CHARGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHEETAH, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_CHEETAH, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_CHEETAH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHIEFTAIN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_CHIEFTAI, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_CHIEFTAI);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COBRA, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_COBRA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_COBRA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COMET, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_COMET, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_COMET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CONDOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_CONDOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_CONDOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COUGAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_COUGAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_COUGAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COWBOY, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_COWBOY, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_COWBOY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DARKHORSE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_DARKHORS, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_DARKHORS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DEMON, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_DEMON, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_DEMON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DODGER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_DODGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_DODGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DRAGON, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_DRAGON, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_DRAGON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EAGLE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_EAGLE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_EAGLE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EIGHTBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_EIGHTBAL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_EIGHTBAL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FARSIGHT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_FARSIGHT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_FARSIGHT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_FIREBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_FIREBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBIRD, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_FIREBIRD, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_FIREBIRD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREFOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_FIREFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_FIREFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FREELANCER, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_FREELANC, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_FREELANC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GATOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_GATOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_GATOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GAUNTLET, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_GAUNTLET, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_GAUNTLET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GHOSTRIDER, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_GHOSTRID, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_GHOSTRID);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GLADIATOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_GLADIATO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_GLADIATO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOLIATH, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_GOLIATH, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_GOLIATH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOOSE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_GOOSE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_GOOSE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HAWKEYE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_HAWKEYE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_HAWKEYE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HELLCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_HELLCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_HELLCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HUNTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_HUNTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_HUNTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JAGUAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_JAGUAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_JAGUAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JESTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_JESTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_JESTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUPITER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_JUPITER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_JUPITER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUGGERNAUT, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_JUGGERNA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_JUGGERNA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_KESTREL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_KESTREL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_KESTREL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LANCER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_LANCER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_LANCER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LIMA, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_LIMA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_LIMA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANIAC, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MANIAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MANIAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANTIS, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MANTIS, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MANTIS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MAULER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MAULER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MAULER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERCURY, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MERCURY, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MERCURY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERLIN, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MERLIN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MERLIN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MILKMAN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MILKMAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MILKMAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MUSTANG, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_MUSTANG, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_MUSTANG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_NIGHTMARE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_NIGHTMAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_NIGHTMAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PANTHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_PANTHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_PANTHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PATRIOT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_PATRIOT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_PATRIOT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHANTOM, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_PHANTOM, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_PHANTOM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHOENIX, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_PHOENIX, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_PHOENIX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PREACHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_PREACHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_PREACHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PYTHON, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_PYTHON, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_PYTHON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAPTOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_RAPTOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_RAPTOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RATTLESNAKE, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_RATTLESN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_RATTLESN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORBACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_RAZORBAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_RAZORBAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORWORKS, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_RAZORWOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_RAZORWOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_REAPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_REAPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_REAPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RENEGADE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_RENEGADE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_RENEGADE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SABRE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SABRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SABRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SAVAGE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SAVAGE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SAVAGE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHADOW, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SHADOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SHADOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHERIFF, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SHERIFF, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SHERIFF);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHOGUN, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SHOGUN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SHOGUN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SNOWBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SNOWBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SNOWBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPARTAKUS, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SPARTACU, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SPARTACU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPECTRUM, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SPECTRUM, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SPECTRUM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STALKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_STALKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_STALKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STINGRAY, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_STINGRAY, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_STINGRAY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STRIKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_STRIKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_STRIKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SUNDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SUNDOWN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SUNDOWN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SWAMP_FOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_SWAMPFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_SWAMPFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TEMPEST, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_TEMPEST, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_TEMPEST);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TIGER_SHARK, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_TIGERSHA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_TIGERSHA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TOUCHDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_TOUCHDOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_TOUCHDOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VAMPIRE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VAMPIRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VAMPIRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VERTIGO, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VERTIGO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VERTIGO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIGILANTE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VIGILANT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VIGILANT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIKING, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VIKING, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VIKING);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VIPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VIPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VOODOO, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VOODOO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VOODOO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULCAN, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VULCAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VULCAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULTURE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_VULTURE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_VULTURE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLOCK, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WARLOCK, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WARLOCK);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLORD, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WARLORD, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WARLORD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARRIOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WARRIOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WARRIOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WILDCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WILDCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WILDCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WOLFPACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WOLFPACK, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WOLFPACK);

		#endif
	}

	{	
		o = SPEECH_ORIGINATOR_WINGMAN2;
		
		initialise_sample_index_array (a, o, max_items);

		#if !DEMO_VERSION

		initialise_speech_data (a, o, GROUP_CALLSIGN_ANGEL, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_ANGEL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_ANGEL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_APOLLO, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_APOLLO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_APOLLO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_ARCHER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_ARCHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_ARCHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BANSHEE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_BANSHEE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_BANSHEE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BLOODHOUND, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_BLOODHOU, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_BLOODHOU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BULLDOG, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_BULLDOG, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_BULLDOG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHARGER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_CHARGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_CHARGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHEETAH, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_CHEETAH, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_CHEETAH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHIEFTAIN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_CHIEFTAI, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_CHIEFTAI);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COBRA, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_COBRA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_COBRA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COMET, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_COMET, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_COMET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CONDOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_CONDOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_CONDOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COUGAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_COUGAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_COUGAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COWBOY, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_COWBOY, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_COWBOY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DARKHORSE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_DARKHORS, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_DARKHORS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DEMON, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_DEMON, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_DEMON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DODGER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_DODGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_DODGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DRAGON, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_DRAGON, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_DRAGON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EAGLE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_EAGLE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_EAGLE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EIGHTBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_EIGHTBAL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_EIGHTBAL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FARSIGHT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_FARSIGHT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_FARSIGHT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_FIREBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_FIREBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBIRD, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_FIREBIRD, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_FIREBIRD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREFOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_FIREFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_FIREFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FREELANCER, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_FREELANC, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_FREELANC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GATOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_GATOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_GATOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GAUNTLET, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_GAUNTLET, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_GAUNTLET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GHOSTRIDER, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_GHOSTRID, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_GHOSTRID);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GLADIATOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_GLADIATO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_GLADIATO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOLIATH, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_GOLIATH, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_GOLIATH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOOSE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_GOOSE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_GOOSE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HAWKEYE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_HAWKEYE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_HAWKEYE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HELLCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_HELLCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_HELLCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HUNTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_HUNTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_HUNTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JAGUAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_JAGUAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_JAGUAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JESTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_JESTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_JESTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUPITER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_JUPITER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_JUPITER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUGGERNAUT, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_JUGGERNA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_JUGGERNA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_KESTREL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_KESTREL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_KESTREL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LANCER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_LANCER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_LANCER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LIMA, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_LIMA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_LIMA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANIAC, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MANIAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MANIAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANTIS, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MANTIS, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MANTIS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MAULER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MAULER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MAULER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERCURY, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MERCURY, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MERCURY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERLIN, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MERLIN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MERLIN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MILKMAN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MILKMAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MILKMAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MUSTANG, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_MUSTANG, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_MUSTANG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_NIGHTMARE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_NIGHTMAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_NIGHTMAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PANTHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_PANTHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_PANTHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PATRIOT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_PATRIOT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_PATRIOT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHANTOM, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_PHANTOM, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_PHANTOM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHOENIX, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_PHOENIX, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_PHOENIX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PREACHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_PREACHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_PREACHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PYTHON, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_PYTHON, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_PYTHON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAPTOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_RAPTOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_RAPTOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RATTLESNAKE, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_RATTLESN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_RATTLESN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORBACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_RAZORBAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_RAZORBAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORWORKS, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_RAZORWOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_RAZORWOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_REAPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_REAPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_REAPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RENEGADE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_RENEGADE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_RENEGADE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SABRE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SABRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SABRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SAVAGE, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SAVAGE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SAVAGE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHADOW, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SHADOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SHADOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHERIFF, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SHERIFF, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SHERIFF);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHOGUN, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SHOGUN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SHOGUN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SNOWBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SNOWBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SNOWBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPARTAKUS, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SPARTACU, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SPARTACU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPECTRUM, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SPECTRUM, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SPECTRUM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STALKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_STALKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_STALKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STINGRAY, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_STINGRAY, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_STINGRAY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STRIKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_STRIKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_STRIKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SUNDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SUNDOWN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SUNDOWN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SWAMP_FOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_SWAMPFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_SWAMPFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TEMPEST, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_TEMPEST, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_TEMPEST);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TIGER_SHARK, 		SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_TIGERSHA, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_TIGERSHA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TOUCHDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_TOUCHDOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_TOUCHDOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VAMPIRE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VAMPIRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VAMPIRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VERTIGO, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VERTIGO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VERTIGO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIGILANTE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VIGILANT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VIGILANT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIKING, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VIKING, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VIKING);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VIPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VIPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VOODOO, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VOODOO, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VOODOO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULCAN, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VULCAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VULCAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULTURE, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_VULTURE, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_VULTURE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLOCK, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WARLOCK, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WARLOCK);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLORD, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WARLORD, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WARLORD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARRIOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WARRIOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WARRIOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WILDCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WILDCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WILDCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WOLFPACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WOLFPACK, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WOLFPACK);

		#endif
	}

	//
	// AIR TRAFFIC CONTROLLER
	//
	{	
		o = SPEECH_ORIGINATOR_AIR_TRAFFIC_CONTROLLER;
		
		initialise_sample_index_array (a, o, max_items);

		#if !DEMO_VERSION

		initialise_speech_data (a, o, GROUP_CALLSIGN_ANGEL, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ANGEL, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ANGEL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_APOLLO, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_APOLLO, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_APOLLO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_ARCHER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_ARCHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_ARCHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BANSHEE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BANSHEE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BANSHEE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BLOODHOUND, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BLOODHOU, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BLOODHOU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BULLDOG, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_BULLDOG, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_BULLDOG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHARGER, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHARGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHARGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHEETAH, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHEETAH, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHEETAH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHIEFTAIN, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CHIEFTAI, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CHIEFTAI);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COBRA, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COBRA, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COBRA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COMET, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COMET, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COMET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CONDOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_CONDOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_CONDOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COUGAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COUGAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COUGAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COWBOY, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_COWBOY, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_COWBOY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DARKHORSE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DARKHORS, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DARKHORS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DEMON, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DEMON, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DEMON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DODGER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DODGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DODGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DRAGON, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_DRAGON, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_DRAGON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EAGLE, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_EAGLE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_EAGLE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EIGHTBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_EIGHTBAL, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_EIGHTBAL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FARSIGHT, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FARSIGHT, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FARSIGHT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBIRD, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREBIRD, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREBIRD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREFOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FIREFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FIREFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FREELANCER, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_FREELANC, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_FREELANC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GATOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GATOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GATOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GAUNTLET, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GAUNTLET, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GAUNTLET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GHOSTRIDER, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GHOSTRID, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GHOSTRID);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GLADIATOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GLADIATO, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GLADIATO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOLIATH, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GOLIATH, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GOLIATH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOOSE, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_GOOSE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_GOOSE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HAWKEYE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HAWKEYE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HAWKEYE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HELLCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HELLCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HELLCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HUNTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_HUNTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_HUNTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JAGUAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JAGUAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JAGUAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JESTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JESTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JESTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUPITER, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JUPITER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JUPITER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUGGERNAUT, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_JUGGERNA, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_JUGGERNA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_KESTREL, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_KESTREL, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_KESTREL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LANCER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_LANCER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_LANCER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LIMA, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_LIMA, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_LIMA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANIAC, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MANIAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MANIAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANTIS, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MANTIS, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MANTIS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MAULER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MAULER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MAULER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERCURY, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MERCURY, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MERCURY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERLIN, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MERLIN, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MERLIN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MILKMAN, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MILKMAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MILKMAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MUSTANG, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_MUSTANG, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_MUSTANG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_NIGHTMARE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_NIGHTMAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_NIGHTMAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PANTHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PANTHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PANTHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PATRIOT, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PATRIOT, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PATRIOT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHANTOM, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PHANTOM, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PHANTOM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHOENIX, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PHOENIX, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PHOENIX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PREACHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PREACHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PREACHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PYTHON, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_PYTHON, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_PYTHON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAPTOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAPTOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAPTOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RATTLESNAKE, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RATTLESN, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RATTLESN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORBACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAZORBAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAZORBAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORWORKS, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RAZORWOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RAZORWOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_REAPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_REAPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_REAPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RENEGADE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_RENEGADE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_RENEGADE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SABRE, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SABRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SABRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SAVAGE, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SAVAGE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SAVAGE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHADOW, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHADOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHADOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHERIFF, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHERIFF, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHERIFF);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHOGUN, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SHOGUN, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SHOGUN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SNOWBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SNOWBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SNOWBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPARTAKUS, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPARTACU, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPARTACU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPECTRUM, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SPECTRUM, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SPECTRUM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STALKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STALKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STALKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STINGRAY, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STINGRAY, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STINGRAY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STRIKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_STRIKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_STRIKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SUNDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SUNDOWN, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SUNDOWN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SWAMP_FOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_SWAMPFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_SWAMPFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TEMPEST, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TEMPEST, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TEMPEST);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TIGER_SHARK, 		SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TIGERSHA, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TIGERSHA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TOUCHDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_TOUCHDOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_TOUCHDOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VAMPIRE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VAMPIRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VAMPIRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VERTIGO, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VERTIGO, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VERTIGO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIGILANTE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIGILANT, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIGILANT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIKING, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIKING, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIKING);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VIPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VIPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VOODOO, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VOODOO, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VOODOO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULCAN, 				SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VULCAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VULCAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULTURE, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_VULTURE, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_VULTURE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLOCK, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARLOCK, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARLOCK);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLORD, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARLORD, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARLORD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARRIOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WARRIOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WARRIOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WILDCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WILDCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WILDCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WOLFPACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_ATC_WOLFPACK, SOUND_SAMPLE_INDEX_SPEECH_CIS_ATC_WOLFPACK);

		#endif
	}

	//
	// FORWARD AIR CONTROLLER 
	//
	{	
		o = SPEECH_ORIGINATOR_FORWARD_AIR_CONTROLLER;
		
		initialise_sample_index_array (a, o, max_items);

		#if !DEMO_VERSION
		
		initialise_speech_data (a, o, GROUP_CALLSIGN_ANGEL, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_ANGEL, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_ANGEL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_APOLLO, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_APOLLO, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_APOLLO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_ARCHER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_ARCHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_ARCHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BANSHEE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BANSHEE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BANSHEE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BLOODHOUND, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BLOODHOU, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BLOODHOU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_BULLDOG, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_BULLDOG, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_BULLDOG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHARGER, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHARGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHARGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHEETAH, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHEETAH, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHEETAH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CHIEFTAIN, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CHIEFTAI, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CHIEFTAI);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COBRA, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COBRA, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COBRA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COMET, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COMET, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COMET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_CONDOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_CONDOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_CONDOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COUGAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COUGAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COUGAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_COWBOY, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_COWBOY, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_COWBOY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DARKHORSE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DARKHORS, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DARKHORS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DEMON, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DEMON, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DEMON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DODGER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DODGER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DODGER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_DRAGON, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_DRAGON, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_DRAGON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EAGLE, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_EAGLE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_EAGLE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_EIGHTBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_EIGHTBAL, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_EIGHTBAL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FARSIGHT, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FARSIGHT, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FARSIGHT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREBIRD, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREBIRD, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREBIRD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FIREFOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FIREFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FIREFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_FREELANCER, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_FREELANC, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_FREELANC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GATOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GATOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GATOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GAUNTLET, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GAUNTLET, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GAUNTLET);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GHOSTRIDER, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GHOSTRID, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GHOSTRID);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GLADIATOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GLADIATO, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GLADIATO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOLIATH, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GOLIATH, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GOLIATH);
		initialise_speech_data (a, o, GROUP_CALLSIGN_GOOSE, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_GOOSE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_GOOSE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HAWKEYE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HAWKEYE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HAWKEYE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HELLCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HELLCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HELLCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_HUNTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_HUNTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_HUNTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JAGUAR, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JAGUAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JAGUAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JESTER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JESTER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JESTER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUPITER, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JUPITER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JUPITER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_JUGGERNAUT, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_JUGGERNA, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_JUGGERNA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_KESTREL, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_KESTREL, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_KESTREL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LANCER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_LANCER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_LANCER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_LIMA, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_LIMA, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_LIMA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANIAC, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MANIAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MANIAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MANTIS, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MANTIS, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MANTIS);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MAULER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MAULER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MAULER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERCURY, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MERCURY, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MERCURY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MERLIN, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MERLIN, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MERLIN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MILKMAN, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MILKMAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MILKMAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_MUSTANG, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_MUSTANG, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_MUSTANG);
		initialise_speech_data (a, o, GROUP_CALLSIGN_NIGHTMARE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_NIGHTMAR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_NIGHTMAR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PANTHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PANTHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PANTHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PATRIOT, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PATRIOT, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PATRIOT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHANTOM, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PHANTOM, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PHANTOM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PHOENIX, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PHOENIX, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PHOENIX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PREACHER, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PREACHER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PREACHER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_PYTHON, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_PYTHON, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_PYTHON);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAPTOR, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAPTOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAPTOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RATTLESNAKE, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RATTLESN, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RATTLESN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORBACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAZORBAC, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAZORBAC);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RAZORWORKS, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RAZORWOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RAZORWOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_REAPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_REAPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_REAPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_RENEGADE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_RENEGADE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_RENEGADE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SABRE, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SABRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SABRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SAVAGE, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SAVAGE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SAVAGE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHADOW, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHADOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHADOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHERIFF, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHERIFF, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHERIFF);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SHOGUN, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SHOGUN, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SHOGUN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SNOWBALL, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SNOWBALL, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SNOWBALL);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPARTAKUS, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPARTACU, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPARTACU);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SPECTRUM, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SPECTRUM, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SPECTRUM);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STALKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STALKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STALKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STINGRAY, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STINGRAY, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STINGRAY);
		initialise_speech_data (a, o, GROUP_CALLSIGN_STRIKER, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_STRIKER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_STRIKER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SUNDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SUNDOWN, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SUNDOWN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_SWAMP_FOX, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_SWAMPFOX, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_SWAMPFOX);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TEMPEST, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TEMPEST, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TEMPEST);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TIGER_SHARK, 		SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TIGERSHA, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TIGERSHA);
		initialise_speech_data (a, o, GROUP_CALLSIGN_TOUCHDOWN, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_TOUCHDOW, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_TOUCHDOW);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VAMPIRE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VAMPIRE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VAMPIRE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VERTIGO, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VERTIGO, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VERTIGO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIGILANTE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIGILANT, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIGILANT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIKING, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIKING, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIKING);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VIPER, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VIPER, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VIPER);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VOODOO, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VOODOO, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VOODOO);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULCAN, 				SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VULCAN, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VULCAN);
		initialise_speech_data (a, o, GROUP_CALLSIGN_VULTURE, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_VULTURE, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_VULTURE);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLOCK, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARLOCK, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARLOCK);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARLORD, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARLORD, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARLORD);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WARRIOR, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WARRIOR, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WARRIOR);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WILDCAT, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WILDCAT, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WILDCAT);
		initialise_speech_data (a, o, GROUP_CALLSIGN_WOLFPACK, 			SOUND_SAMPLE_INDEX_SPEECH_US_FAC_WOLFPACK, SOUND_SAMPLE_INDEX_SPEECH_CIS_FAC_WOLFPACK);

		#endif
	}

	//
	// GROUND CONTROLLER
	//
	{	
		o = SPEECH_ORIGINATOR_GROUND_CONTROLLER;
		
		initialise_sample_index_array (a, o, max_items);
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
