// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "project.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
// WINGMAN MESSAGES ARRAY
// 

void initialise_speech_wingman_data (void)
{
	speech_array_types
		a = SPEECH_ARRAY_WINGMAN_MESSAGES;

	speech_originator_types
		o;

	int
		max_items = NUM_SPEECH_WINGMAN_MESSAGES;

	//
	// WINGMAN
	//
	{	
		o = SPEECH_ORIGINATOR_WINGMAN1;
		
		initialise_sample_index_array (a, o, max_items);

		#if !DEMO_VERSION

		initialise_speech_data (a, o, SPEECH_WINGMAN_INTRODUCTION, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_01, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_01);
		initialise_speech_data (a, o, SPEECH_WINGMAN_NEGATIVE, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_02, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_02);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AFFIRMATIVE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_03, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_03);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AT_GRID, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_04, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_04);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TALLY_SPOT, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_05, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_05);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_LASED, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_06, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_06);
		initialise_speech_data (a, o, SPEECH_WINGMAN_EXECUTE_SPOT, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_07, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_07);
		initialise_speech_data (a, o, SPEECH_WINGMAN_SPOT_ON, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_08, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_08);
		initialise_speech_data (a, o, SPEECH_WINGMAN_APPROACHING_ENGAGEMENT_AREA, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_09, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_09);
		initialise_speech_data (a, o, SPEECH_WINGMAN_APPROACHING_BATTLE_POSITION, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_10, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_10);
		initialise_speech_data (a, o, SPEECH_WINGMAN_APPROACHING_RP, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_11, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_11);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MISSION_COMPLETE1, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_12, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_12);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MISSION_COMPLETE2, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_13, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_13);
		initialise_speech_data (a, o, SPEECH_WINGMAN_INCOMING, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_14, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_14);
		initialise_speech_data (a, o, SPEECH_WINGMAN_INCOMING_MISSILE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_15, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_15);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TAKING_HITS, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_16, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_16);
		initialise_speech_data (a, o, SPEECH_WINGMAN_GOING_DOWN, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_17, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_17);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_HIT, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_18, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_18);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_MISSED, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_19, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_19);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_DESTROYED, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_20, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_20);
		initialise_speech_data (a, o, SPEECH_WINGMAN_BOBBING_UP, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_21, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_21);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ENGAGING_TARGET, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_22, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_22);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_MAINTAINING_POSITION, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_23, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_23);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_REJOINING_FORMATION, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_24, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_24);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_BOBBING_UP, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_25, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_25);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_RETURNING_TO_BASE, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_26, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_26);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_WEAPONS_HOLD, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_27, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_27);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_WEAPONS_FREE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_28, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_28);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_ENGAGING_TARGET, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_29, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_29);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_COMING_TO_ASSIST, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_30, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_30);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_MOVING_INTO_ORDERED_POSITION, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_31, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_31);
		initialise_speech_data (a, o, SPEECH_WINGMAN_WE_HAVE, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_32, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_32);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AIR_TO_GROUND_MISSILES, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_33, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_33);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AIR_TO_AIR_MISSILES, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_34, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_34);
		initialise_speech_data (a, o, SPEECH_WINGMAN_PERCENT, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_35, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_35);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROCKETS, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_36, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_36);
		initialise_speech_data (a, o, SPEECH_WINGMAN_CANNON_AMMO, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_37, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_37);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FULLY_MISSION_CAPABLE, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_38, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_38);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MINOR_DAMAGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_39, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_39);
		initialise_speech_data (a, o, SPEECH_WINGMAN_SOME_DAMAGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_40, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_40);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MAJOR_DAMAGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_41, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_41);
		initialise_speech_data (a, o, SPEECH_WINGMAN_LAUNCHING_MISSILE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_42, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_42);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MISSILE_AWAY, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_43, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_43);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FIRING_ROCKETS, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_44, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_44);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROCKETS_AWAY, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_45, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_45);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FIRING_CANNON, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_46, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_46);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ENGAGING_WITH_CANNON, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_47, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_47);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ACKNOWLEDGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_48, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_48);
		initialise_speech_data (a, o, SPEECH_WINGMAN_UNABLE_TO_COMPLY, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_49, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_49);
		initialise_speech_data (a, o, SPEECH_WINGMAN_REQUEST_PERMISSION_TO_LAND, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_50, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_50);
		initialise_speech_data (a, o, SPEECH_WINGMAN_REQUEST_PERMISSION_TO_TAKEOFF, 						SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_51, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_51);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TRANSMITTING_RECON_DATA, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_52, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_52);
		initialise_speech_data (a, o, SPEECH_WINGMAN_SEEKING_COVER, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_53, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_53);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FLYING_TO_COVER, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_54, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_54);
		initialise_speech_data (a, o, SPEECH_WINGMAN_IN_POSITION, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_55, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_55);
		initialise_speech_data (a, o, SPEECH_WINGMAN_UNDER_ATTACK_AIRCRAFT, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_56, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_56);
		initialise_speech_data (a, o, SPEECH_WINGMAN_UNDER_ATTACK_ARMOUR, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_57, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_57);
		initialise_speech_data (a, o, SPEECH_WINGMAN_REQUEST_ASSISTANCE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN1_WING_58, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN1_WING_58);

		#endif
	}

	{	
		o = SPEECH_ORIGINATOR_WINGMAN2;
		
		initialise_sample_index_array (a, o, max_items);

		#if !DEMO_VERSION

		initialise_speech_data (a, o, SPEECH_WINGMAN_INTRODUCTION, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_01, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_01);
		initialise_speech_data (a, o, SPEECH_WINGMAN_NEGATIVE, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_02, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_02);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AFFIRMATIVE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_03, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_03);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AT_GRID, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_04, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_04);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TALLY_SPOT, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_05, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_05);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_LASED, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_06, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_06);
		initialise_speech_data (a, o, SPEECH_WINGMAN_EXECUTE_SPOT, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_07, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_07);
		initialise_speech_data (a, o, SPEECH_WINGMAN_SPOT_ON, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_08, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_08);
		initialise_speech_data (a, o, SPEECH_WINGMAN_APPROACHING_ENGAGEMENT_AREA, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_09, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_09);
		initialise_speech_data (a, o, SPEECH_WINGMAN_APPROACHING_BATTLE_POSITION, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_10, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_10);
		initialise_speech_data (a, o, SPEECH_WINGMAN_APPROACHING_RP, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_11, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_11);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MISSION_COMPLETE1, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_12, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_12);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MISSION_COMPLETE2, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_13, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_13);
		initialise_speech_data (a, o, SPEECH_WINGMAN_INCOMING, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_14, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_14);
		initialise_speech_data (a, o, SPEECH_WINGMAN_INCOMING_MISSILE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_15, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_15);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TAKING_HITS, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_16, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_16);
		initialise_speech_data (a, o, SPEECH_WINGMAN_GOING_DOWN, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_17, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_17);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_HIT, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_18, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_18);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_MISSED, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_19, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_19);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TARGET_DESTROYED, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_20, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_20);
		initialise_speech_data (a, o, SPEECH_WINGMAN_BOBBING_UP, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_21, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_21);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ENGAGING_TARGET, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_22, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_22);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_MAINTAINING_POSITION, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_23, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_23);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_REJOINING_FORMATION, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_24, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_24);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_BOBBING_UP, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_25, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_25);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_RETURNING_TO_BASE, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_26, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_26);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_WEAPONS_HOLD, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_27, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_27);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_WEAPONS_FREE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_28, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_28);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_ENGAGING_TARGET, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_29, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_29);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_COMING_TO_ASSIST, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_30, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_30);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROGER_MOVING_INTO_ORDERED_POSITION, 				SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_31, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_31);
		initialise_speech_data (a, o, SPEECH_WINGMAN_WE_HAVE, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_32, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_32);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AIR_TO_GROUND_MISSILES, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_33, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_33);
		initialise_speech_data (a, o, SPEECH_WINGMAN_AIR_TO_AIR_MISSILES, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_34, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_34);
		initialise_speech_data (a, o, SPEECH_WINGMAN_PERCENT, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_35, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_35);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROCKETS, 													SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_36, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_36);
		initialise_speech_data (a, o, SPEECH_WINGMAN_CANNON_AMMO, 												SOUND_SAMPLE_INDEX_NONE, 								SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_37);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FULLY_MISSION_CAPABLE, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_38, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_38);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MINOR_DAMAGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_39, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_39);
		initialise_speech_data (a, o, SPEECH_WINGMAN_SOME_DAMAGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_40, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_40);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MAJOR_DAMAGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_41, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_41);
		initialise_speech_data (a, o, SPEECH_WINGMAN_LAUNCHING_MISSILE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_42, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_42);
		initialise_speech_data (a, o, SPEECH_WINGMAN_MISSILE_AWAY, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_43, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_43);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FIRING_ROCKETS, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_44, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_44);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ROCKETS_AWAY, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_45, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_45);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FIRING_CANNON, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_46, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_46);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ENGAGING_WITH_CANNON, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_47, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_47);
		initialise_speech_data (a, o, SPEECH_WINGMAN_ACKNOWLEDGE, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_48, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_48);
		initialise_speech_data (a, o, SPEECH_WINGMAN_UNABLE_TO_COMPLY, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_49, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_49);
		initialise_speech_data (a, o, SPEECH_WINGMAN_REQUEST_PERMISSION_TO_LAND, 							SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_50, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_50);
		initialise_speech_data (a, o, SPEECH_WINGMAN_REQUEST_PERMISSION_TO_TAKEOFF, 						SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_51, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_51);
		initialise_speech_data (a, o, SPEECH_WINGMAN_TRANSMITTING_RECON_DATA, 								SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_52, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_52);
		initialise_speech_data (a, o, SPEECH_WINGMAN_SEEKING_COVER, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_53, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_53);
		initialise_speech_data (a, o, SPEECH_WINGMAN_FLYING_TO_COVER, 											SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_54, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_54);
		initialise_speech_data (a, o, SPEECH_WINGMAN_IN_POSITION, 												SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_55, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_55);
		initialise_speech_data (a, o, SPEECH_WINGMAN_UNDER_ATTACK_AIRCRAFT, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_56, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_56);
		initialise_speech_data (a, o, SPEECH_WINGMAN_UNDER_ATTACK_ARMOUR, 									SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_57, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_57);
		initialise_speech_data (a, o, SPEECH_WINGMAN_REQUEST_ASSISTANCE, 										SOUND_SAMPLE_INDEX_SPEECH_US_WINGMAN2_WING_58, SOUND_SAMPLE_INDEX_SPEECH_CIS_WINGMAN2_WING_58);

		#endif
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

