;NSIS Modern User Interface
;EECH setup exe script, by gotcha jan 2005

SetCompressor /SOLID lzma

;--------------------------------
;Include Modern UI

	!include "MUI.nsh"

;--------------------------------
;General

	;define these variable
	!define VERSION "1.15.2"

	;Name and file
	Name "EECH Dev release ${VERSION}"
	OutFile "eech-allmods-${VERSION}.exe"

	;Default installation folder
	InstallDir "C:\Program Files\Razorworks"

	;Get installation folder from registry if available
	InstallDirRegKey HKLM "Software\Razorworks\Comanche Hokum" "INSTALLATION PATH"

;--------------------------------
;Interface Settings

	!define MUI_ABORTWARNING

;--------------------------------
;Pages
	!define MUI_ICON eech.ico
	!define MUI_WELCOMEFINISHPAGE_BITMAP enemyengagedlogo.bmp
	!define MUI_WELCOMEFINISHPAGE_BITMAP_NOSTRETCH
	!define MUI_WELCOMEPAGE_TITLE_3LINES

		!define MUI_COMPONENTSPAGE_TEXT_TOP "You should have EECH 1.15.0 with all components installed (allmods, maps, terrain, smoke 1.14.0). Check/Uncheck what 1.15.2 components you want to install."
	!insertmacro MUI_PAGE_COMPONENTS
		!define MUI_DIRECTORYPAGE_TEXT_TOP "Please select the Razorworks root folder. This installer will place the files in the correct directories."
	!insertmacro MUI_PAGE_DIRECTORY
	!insertmacro MUI_PAGE_INSTFILES
		!define MUI_FINISHPAGE_NOAUTOCLOSE
	!insertmacro MUI_PAGE_FINISH

	ShowInstDetails show
;--------------------------------
;Languages

	!insertmacro MUI_LANGUAGE "English"

;--------------------------------
;Installer Sections

	!define SRCDIR "../"
	!define EE_BASE_DIR "${SRCDIR}"



Section "System and misc files" SectionSystem

	SetOutPath "$INSTDIR\cohokum"

	File "${SRCDIR}\cohokum\cohokum.exe"
	File "${SRCDIR}\cohokum\cohokum_DS.exe"
	File "${SRCDIR}\cohokum\DEBUG.exe"
	File "${SRCDIR}\cohokum\readme.html"
	File "${SRCDIR}\cohokum\eech_keyguide_3.pdf"
	File "${SRCDIR}\cohokum\GWUT1152.CSV"
	File "${SRCDIR}\cohokum\GWUT.xls"

	Delete "$INSTDIR\cohokum\eech_keyguide_2.pdf"
	Delete "$INSTDIR\cohokum\eech_keyguide_190_2.9.pdf"

SectionEnd

Section "Models and textures" SectionModels

	SetOutPath "$INSTDIR\cohokum\3ddata\objects"

	File "${SRCDIR}\cohokum\3ddata\objects\1007.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\2403.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\2404.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\2405.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\2406.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\2449.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\244A.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\244B.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\244C.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\246B.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\246C.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\246D.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\246E.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\246F.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\2470.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\2471.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\2472.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\ASO-2V.EEO"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\AH-1Z Viper"

	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1_COPILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1_LEFT_SKI.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1_PILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1_RIGHT_SKI.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1_TAIL_BUMPER.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1W_MAIN_ROTOR_BLADE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z_COLLISION_OBJECT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-1Z Viper\AH1Z_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\AH-64D Apache Longbow"

	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_COLLISION_OBJECT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_LT_MAIN_GEAR_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_LT_MAIN_GEAR_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_RT_MAIN_GEAR_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_RT_MAIN_GEAR_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_TAILWHEEL_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\M130.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_APACHE_LONGBOW.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\AH-64D Apache Longbow\AH64D_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\ah-64d-cockpit"

	File "${SRCDIR}\cohokum\3ddata\objects\ah-64d-cockpit\ah-64d-cockpit.EEO"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\AH1T_SEACOBRA"

	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1_COPILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1_LEFT_SKI.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1_PILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1_RIGHT_SKI.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1_TAIL_BUMPER.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1T_COLLISION_OBJECT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1T_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1T_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1T_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1W_MAIN_ROTOR_BLADE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1_T.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1T_SEACOBRA\AH1T_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\AH1W_SUPERCOBRA"

	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1_LEFT_SKI.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1_RIGHT_SKI.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1_TAIL_BUMPER.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_COLLISION_OBJECT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_COPILOT_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_COPILOT_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_MAIN_ROTOR_BLADE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_PILOT_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_PILOT_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1_W.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\AH1W_SUPERCOBRA\AH1W_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\AH64A_APACHE"

	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64A_TAILPLANE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_LT_MAIN_GEAR_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_LT_MAIN_GEAR_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_LT_MAIN_GEAR_TRAILING_ARM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_RT_MAIN_GEAR_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_RT_MAIN_GEAR_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_RT_MAIN_GEAR_TRAILING_ARM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_TAILWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_TAILWHEEL_DOUBLE_TRAILING_ARM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_TAILWHEEL_FORK.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_TAILWHEEL_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64D_TAILWHEEL_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH_64A_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH_64A_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH_64A_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH_64A_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\M130.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH64A_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\AH64A_APACHE\AH_64A.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CH3_JOLLY_GREEN_GIANT"

	File "${SRCDIR}\cohokum\3ddata\objects\CH3_JOLLY_GREEN_GIANT\CH3_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\CH3_JOLLY_GREEN_GIANT\CH_3.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CH46E_SEA_KNIGHT"

	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\CH46_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\CH46_NOSEWHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\CH46_NOSEWHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\MV22_WHEEL_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\CH46_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\CH46E_SEA_KNIGHT\CH_46.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CH47D_CHINOOK"

	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47_NOSEWHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47_NOSEWHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_CABIN_DOOR_LOWER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_CABIN_DOOR_UPPER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_CARGO_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_MAIN_ROTOR_HUB_STATIC.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\M130.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\MV22_WHEEL_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\CH47D_CHINOOK\CH47D_CHINOOK.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CH53E_SUPER_STALLION"

	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_CARGO_DOOR_LOWER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_CARGO_DOOR_UPPER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_MAIN_ROTOR_BLADE_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_MAIN_ROTOR_HUB.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_MAIN_ROTOR_HUB_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_NOSE_WHEEL_UNDERCARRIAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_SIDE_DOOR_LOWER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_SIDE_DOOR_UPPER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_WHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_WHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53E_WHEEL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\RAH66_MAINWHEEL_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH53_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\CH53E_SUPER_STALLION\CH_53.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CIS_MARINE_WALK"

	File "${SRCDIR}\cohokum\3ddata\objects\CIS_MARINE_WALK\CIS_MARINE_WALK.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CLOUDS"

	File "${SRCDIR}\cohokum\3ddata\objects\CLOUDS\CLOUD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CLOUDS\CLOUD.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\CRATER"

	File "${SRCDIR}\cohokum\3ddata\objects\CRATER\CRATER.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\CRATER\CRATER_ROUND.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\digits"

	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_0.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_2.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_3.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_4.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_5.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_6.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_7.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_8.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_9.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_0.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_1.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_2.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_3.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_4.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_5.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_6.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_7.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_8.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\digits\dig_9.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\FARP"

	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_COLLISION.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_HESCO.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_HESCO_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_HESCO_LOD2.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_HESCO_LOD3.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_MAT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_MAT_GREY.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_MAT.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\FARP\FARP_MAT_GREY.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\ka-50-cockpit"

	File "${SRCDIR}\cohokum\3ddata\objects\ka-50-cockpit\k50-cockpit.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\ka-50-cockpit\KA50_COCKPIT.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\KA29_HELIX_B"

	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\ASO-2V.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\ATAKA_RACK_4X.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_BACK_DOOR_LOWER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_BACK_DOOR_UPPER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_BACK_DOOR_UPPER_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FRONT_DOOR_LOWER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FRONT_DOOR_UPPER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FRONT_DOOR_UPPER_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_MAIN_WHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_MAIN_WHEEL_LEFT_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_MAIN_WHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_MAIN_WHEEL_RIGHT_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_NOSE_WHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_NOSE_WHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_NOSE_WHEEL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_WHEEL_FORK.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_HELIX_B.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\KA29_HELIX_B\KA29_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\KA50_HOKUM"

	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_FUSELAGE_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_FUSELAGE_LOD2.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_FUSELAGE_LOD3.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_LT_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_MAIN_GEAR_ARM_LINK.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_MAIN_GEAR_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_MAIN_GEAR_TRAILING_ARM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_NOSEWHEEL_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_NOSEWHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_NS_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50_RT_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA50_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\KA50_HOKUM\KA_50.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\KA52_HOKUM_B"

	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_COLLISION_OBJECT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_COPILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_COPILOT_DOOR_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_FUSELAGE_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_FUSELAGE_LOD2.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_FUSELAGE_LOD3.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_PILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_PILOT_DOOR_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_LT_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_MAIN_GEAR_ARM_LINK.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_MAIN_GEAR_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_MAIN_GEAR_TRAILING_ARM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_NOSEWHEEL_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_NOSEWHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_NS_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_50_RT_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA52_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\KA52_HOKUM_B\KA_52.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\Mi-24 Hind"

	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\ASO-2V.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_COPILOT_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_COPILOT_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_DOOR_DOWN_LEFT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_DOOR_DOWN_RIGHT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_DOOR_UP_LEFT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_DOOR_UP_RIGHT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_HORIZONTAL_STABILIZER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LEFT_UNDERCARRIAGE_1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LEFT_UNDERCARRIAGE_2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LT_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LT_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LT_MAIN_STRUT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LT_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_LT_SEC_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NOSE_GUN.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NOSE_GUN_BARRELS.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NOSE_GUN_POD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NOSE_WHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NOSE_WHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NOSE_WHEEL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_NS_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_PILOT_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_PILOT_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RIGHT_UNDERCARRIAGE_1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RIGHT_UNDERCARRIAGE_2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RT_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RT_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RT_MAIN_STRUT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RT_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_RT_SEC_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_STATIC_ROTOR_HUB.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_HIND.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-24 Hind\MI24_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\Mi-28 Havoc"

	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_COLLISION_OBJECT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_FUSELAGE_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_FUSELAGE_LOD2.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_MAIN_GEAR_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_MAIN_GEAR_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_MAIN_GEAR_TRAILING_ARM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_TAILWHEEL_FORK.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_TAILWHEEL_STRUT_CYL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_TAILWHEEL_STRUT_PISTON.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\Mi-28 Havoc\MI28N_HAVOC.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\MI17_HIP"

	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\ASO-2V.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_HORIZONTAL_STABILIZER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_LEFT_CARGO_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_LEFT_CARGO_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_MAIN_WHEEL_CYL1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_MAIN_WHEEL_CYL2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_MAIN_WHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_MAIN_WHEEL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_NOSE_WHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_NOSE_WHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_NOSE_WHEEL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_RIGHT_CARGO_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_RIGHT_CARGO_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_SIDE_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_SIDE_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_HIP.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\MI17_HIP\MI17_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\MI6_HOOK"

	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\ASO-2V.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_BRIDGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_HORIZONTAL_STABILIZER.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_LEFT_BACK_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_LEFT_BACK_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_LEFT_CARGO_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_LEFT_CARGO_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_LEFT_FRONT_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_LEFT_FRONT_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_MAIN_GEAR_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_MAIN_GEAR_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_MAIN_GEAR_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_NOSEWHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_NOSEWHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_RIGHT_CARGO_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_RIGHT_CARGO_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_RIGHT_DOOR.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_RIGHT_DOOR_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_HOOK.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\MI6_HOOK\MI6_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\MV22_OSPREY"

	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_NOSEWHEEL_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_NOSEWHEEL_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_WHEEL_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV22_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\MV22_OSPREY\MV_22.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\OH-58D Kiowa Warrior"

	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\oh58d-gunpod.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\oh58d-m260.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\oh58d-mast.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\oh58d-undermast.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\oh58d-wings.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_COLLISION_OBJECT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_GUNPOD_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_LEFT_SKI.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_M260_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_MAIN_ROTOR_BLADE_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_RIGHT_SKI.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_TAIL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D_WINGS_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58_ROTOR_BLADE_DAMAGED.ees"
	File "${SRCDIR}\cohokum\3ddata\objects\OH-58D Kiowa Warrior\OH58D.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\RAH-66 Comanche"

	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_COPILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_COPILOT_DOOR_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_FUSELAGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_LEFT_MAIN_STRUT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_MAIN_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_MAIN_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_MAIN_ROTOR_BLADE_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_MAINWHEEL_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_PILOT_DOOR.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_PILOT_DOOR_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_RIGHT_MAIN_STRUT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_TAILWHEEL_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\RAH-66 Comanche\RAH66_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\ROTOR_BLADE_DAMAGED"

	File "${SRCDIR}\cohokum\3ddata\objects\ROTOR_BLADE_DAMAGED\ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\TARAWA"

	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\M2HB_BARREL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\M2HB_BARREL_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\M2HB_BASE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\M2HB_BASE_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\M2HB_PLATFORM.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK15_PHALANX_BARRELS.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK15_PHALANX_BARRELS_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK15_PHALANX_BASE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK15_PHALANX_BASE_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK15_PHALANX_BODY.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK15_PHALANX_BODY_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK38_BARREL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK38_BARREL_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK38_BASE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\MK38_BASE_LOD.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\TARAWA\TARAWA.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\UH-60 Blackhawk"

	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\AH64D_MAINWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\AH64D_STINGER_RAIL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\AH64D_TAILWHEEL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\M130.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_blackhawk_stabilator.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_COLLISION_OBJECT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_DETAILS_LOD.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_DOORS.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_DOORS_LOD1.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_FUSELAGE.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_FUSELAGE_LOD1.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_FUSELAGE_LOD2.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_FUSELAGE_LOD3.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_FUSELAGE_LOD4.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_LT_MAIN_GEAR_TRAILING_ARM.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_MAIN_GEAR_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_MAIN_GEAR_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_RT_MAIN_GEAR_TRAILING_ARM.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_TAILWHEEL_FORK.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_TAILWHEEL_STRUT.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_TAILWHEEL_STRUT_CYL.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_TAILWHEEL_STRUT_PISTON.eeo"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_BLACKHAWK.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\UH-60 Blackhawk\UH60_ROTOR_BLADE_DAMAGED.ees"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\US_MARINE_WALK"

	File "${SRCDIR}\cohokum\3ddata\objects\US_MARINE_WALK\US_MARINE_WALK.EES"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\camo"

	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1Z_WING_DARKII.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH64_STINGER-D.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH64_STINGER.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\CHROME.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\STINGER_TUBE-D.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\STINGER_TUBE-W.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\STINGER_TUBE.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1WFUCT-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1WFUCT-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1WFUCT.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1WFUST-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1WFUST-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH1WFUST.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH64_POD_CASE-D.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH64_POD_CASE-W.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\AH64_POD_CASE.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\avchinook.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\CH-53E-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\CH-53E-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\CH-53E.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\Hellfire_LT.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\Hellfire_RT.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\KA29-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\KA29-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\KA29.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\KA29_INT.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\M130.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI-24-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI-24-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI-24.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI17-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI17-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI17.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI6-D.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MI6-W.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\camo\mi6.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\MK15_PHALANX.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\REFLECTION_DESERT.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\REFLECTION_FOREST.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\REFLECTION_JUNGLE.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\REFLECTION_ROCKS.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\REFLECTION_WINTER.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\VIP_HELLFIRE_LT.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\VIP_HELLFIRE_RT.dds"
	File "${SRCDIR}\cohokum\graphics\textures\camo\US_ARMY_FLIGHT_SUIT-D.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\camo\US_ARMY_FLIGHT_SUIT-W.bmp"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\general"

	File "${SRCDIR}\cohokum\graphics\textures\general\aso-2v.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\B8V20.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\CRATER.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\diffuse.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\GLASS_DETAILS.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\NEW-CLOUDS.DDS"
	File "${SRCDIR}\cohokum\graphics\textures\general\SCRATCHED_GLASS.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\UB32A.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\YAKB.dds"
	File "${SRCDIR}\cohokum\graphics\textures\general\TRACER_FIRE_BLUE.tga"
	File "${SRCDIR}\cohokum\graphics\textures\general\TRACER_FIRE_GREEN.tga"
	File "${SRCDIR}\cohokum\graphics\textures\general\TRACER_FIRE_ORANGE.tga"
	File "${SRCDIR}\cohokum\graphics\textures\general\TRACER_FIRE_PURPLE.tga"
	File "${SRCDIR}\cohokum\graphics\textures\general\TRACER_FIRE_RED.tga"
	File "${SRCDIR}\cohokum\graphics\textures\general\TRACER_FIRE_WHITE.tga"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_LITE_HIP-D.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_LITE_HIP-W.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_LITE_HIP.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_V1_CAMO-D.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_V1_CAMO-W.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_V1_CAMO.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_V1_CAMO_SMALL-D.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_V1_CAMO_SMALL-W.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\general\US_PILOT_V1_CAMO_SMALL.bmp"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\terrain\Europe"

	File "${SRCDIR}\cohokum\graphics\textures\terrain\Europe\GREY_TERRAIN_TREE_CROSS.dds"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\terrain\lebanon"

	File "${SRCDIR}\cohokum\graphics\textures\terrain\lebanon\GREY_TERRAIN_TREE_CROSS.dds"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\terrain\taiwan"

	File "${SRCDIR}\cohokum\graphics\textures\terrain\taiwan\GREY_TERRAIN_TREE_CROSS.dds"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\terrain\water"

	File "${SRCDIR}\cohokum\graphics\textures\terrain\water\reservoir1.dds"
	File "${SRCDIR}\cohokum\graphics\textures\terrain\water\SEAbottom.dds"

SectionEnd

Section "Smokes and explosions" SectionSmokes

	SetOutPath "$INSTDIR\cohokum"

	File "${SRCDIR}\cohokum\EXPLOS.CSV"
	File "${SRCDIR}\cohokum\METASMOK.CSV"
	File "${SRCDIR}\cohokum\SMOKES.CSV"

	SetOutPath "$INSTDIR\cohokum\graphics\textures\animation"

	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT000.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT001.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT002.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT003.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT004.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT005.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT006.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT007.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT008.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT009.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT010.bmp"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SPARK001.BMP"
	File "${SRCDIR}\cohokum\graphics\textures\animation\debris001.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\FLARE001.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\FRONT_SHIP_WAKE_001.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\INFRARED_FLAME.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\REAR_SHIP_WAKE001.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL001.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL002.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL003.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL004.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL005.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL006.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL007.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL008.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL009.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL010.dds"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE000.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE001.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE002.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE003.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE004.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE005.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE006.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE007.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE008.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE009.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE010.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH001.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH002.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH003.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH004.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH005.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH006.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH007.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH008.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH009.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH010.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH011.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH012.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH013.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH014.tga"
	File "${SRCDIR}\cohokum\graphics\textures\animation\debris.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\FRONT_SHIP_WAKE.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\INFRARED_FLAME.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\MISSILE_FLARE.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\REAR_SHIP_WAKE.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_FRONT.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\ROCKET_FLAME_SIDE.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SMOKE_TRAIL.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\SPARK.txt"
	File "${SRCDIR}\cohokum\graphics\textures\animation\WATER_SPLASH.txt"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\EFFECTS"

	File "${SRCDIR}\cohokum\3ddata\objects\EFFECTS\EFFECT_SMALL_WATER_SPLASH.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\EFFECTS\ROCKET_FLAME.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\EFFECTS\ROCKET_FLAME_FRONT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\EFFECTS\ROCKET_FLAME_SIDE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\EFFECTS\EFFECT_ROCKET_FLAME.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\EFFECTS\EFFECT_SMALL_WATER_SPLASH.EES"

	SetOutPath "$INSTDIR\cohokum\3ddata\objects\PROJECTILES"

	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\CANNON_SABOT.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\CANNON_SHELL.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_BLUE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_GREEN.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_ORANGE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_PURPLE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_RED.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_WHITE.EEO"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\CANNON_SABOT.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\CANNON_SHELL.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_BLUE.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_GREEN.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_ORANGE.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_PURPLE.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_RED.EES"
	File "${SRCDIR}\cohokum\3ddata\objects\PROJECTILES\TRACER_FIRE_WHITE.EES"

SectionEnd

Section "Dynamics and suspension configs" SectionDynamics

	Delete "$INSTDIR\common\data\dyn\*.txt"
	Delete "$INSTDIR\common\data\*.dyn"

	SetOutPath "$INSTDIR\common\data\dynamics"

	File "${SRCDIR}\common\data\dynamics\ah64a.dyn"
	File "${SRCDIR}\common\data\dynamics\apache.dyn"
	File "${SRCDIR}\common\data\dynamics\blckhwk.dyn"
	File "${SRCDIR}\common\data\dynamics\chinook.dyn"
	File "${SRCDIR}\common\data\dynamics\comanche.dyn"
	File "${SRCDIR}\common\data\dynamics\greengiant.dyn"
	File "${SRCDIR}\common\data\dynamics\havoc.dyn"
	File "${SRCDIR}\common\data\dynamics\helixb.dyn"
	File "${SRCDIR}\common\data\dynamics\hind.dyn"
	File "${SRCDIR}\common\data\dynamics\hip.dyn"
	File "${SRCDIR}\common\data\dynamics\hokum.dyn"
	File "${SRCDIR}\common\data\dynamics\hook.dyn"
	File "${SRCDIR}\common\data\dynamics\ka50.dyn"
	File "${SRCDIR}\common\data\dynamics\kiowa.dyn"
	File "${SRCDIR}\common\data\dynamics\osprey.dyn"
	File "${SRCDIR}\common\data\dynamics\seacobra.dyn"
	File "${SRCDIR}\common\data\dynamics\seaknight.dyn"
	File "${SRCDIR}\common\data\dynamics\supercobra.dyn"
	File "${SRCDIR}\common\data\dynamics\superstallion.dyn"
	File "${SRCDIR}\common\data\dynamics\viper.dyn"

	SetOutPath "$INSTDIR\common\data\suspension"

	File "${SRCDIR}\common\data\suspension\ah-1-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ah-64-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ch-3-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ch-46-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ch-47-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ch-53-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ka-29-suspension.txt"
	File "${SRCDIR}\common\data\suspension\ka-52-suspension.txt"
	File "${SRCDIR}\common\data\suspension\mi-17-suspension.txt"
	File "${SRCDIR}\common\data\suspension\mi-24-suspension.txt"
	File "${SRCDIR}\common\data\suspension\mi-28-suspension.txt"
	File "${SRCDIR}\common\data\suspension\mi-6-suspension.txt"
	File "${SRCDIR}\common\data\suspension\mv-22-suspension.txt"
	File "${SRCDIR}\common\data\suspension\oh-58-suspension.txt"
	File "${SRCDIR}\common\data\suspension\rah-66-suspension.txt"
	File "${SRCDIR}\common\data\suspension\uh-60-suspension.txt"

SectionEnd

Section "Forcefeedback effects" SectionFFB

	SetOutPath "$INSTDIR\cohokum\forcefeedback"

	File "${SRCDIR}\cohokum\forcefeedback\fedit.exe"
	File "${SRCDIR}\cohokum\forcefeedback\AGM-114K Hellfire II.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\S-8KOM HEAT.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\ffe filenames.txt"

	SetOutPath "$INSTDIR\cohokum\forcefeedback\samples"

	File "${SRCDIR}\cohokum\forcefeedback\samples\autocannon.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\blowout.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\car1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\car2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\car3.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\csawing1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\csawing2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\csawing3.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\csawing4.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\dirt4.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\energy1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\energy2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\Explosion.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\gatling.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\gatling2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\jump.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\land1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\land2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\lightnng.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\machineg.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\mech1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\mech2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\missile.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\offroad2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\offroad3.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\offroad4.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\punch.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\punched1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\punched2.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\rocket1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\shake.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\shotgun1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\trampa.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\turbulen.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\vortex.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\walking.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\windgust.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\wsheer1.ffe"
	File "${SRCDIR}\cohokum\forcefeedback\samples\wsheer2.ffe"

SectionEnd

Section "US ATC voice pack" SectionUSATC

	SetOutPath "$INSTDIR\cohokum\audio\speech\us\atc"

 	File "${SRCDIR}\cohokum\audio\speech\us\atc\0.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\01.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\02.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\03.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\04.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\05.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\06.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\07.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\08.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\09.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\100.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ANGEL.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\APOLLO.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ARCHER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_01.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_02.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_03.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_04.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_05.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_06.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_07.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_08.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_09.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_10.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_11.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\ATC_12.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\BANSHEE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\BEARING.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\BLOODHOU.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\BULLDOG.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\CHARGER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\CHEETAH.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\CHIEFTAI.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\COBRA.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\COMET.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\CONDOR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\COUGAR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\COWBOY.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\DARKHORS.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\DEMON.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\DODGER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\DRAGON.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\EAGLE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\EIGHTBAL.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\FARSIGHT.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\FIREBALL.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\FIREBIRD.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\FIREFOX.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\FREELANC.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\GATOR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\GAUNTLET.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\GHOSTRID.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\GLADIATO.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\GOLIATH.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\GOOSE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\HAWKEYE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\HELLCAT.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\HUNTER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\JAGUAR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\JESTER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\JUGGERNA.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\JUPITER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\KESTREL.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\KNOT.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\KNOTS.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\LANCER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\LIMA.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MANIAC.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MANTIS.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MAULER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MERCURY.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MERLIN.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MILKMAN.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\MUSTANG.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\NIGHTMAR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\PANTHER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\PATRIOT.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\PHANTOM.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\PHOENIX.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\PREACHER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\PYTHON.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\RANGE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\RAPTOR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\RATTLESN.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\RAZORBAC.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\RAZORWOR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\REAPER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\RENEGADE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SABRE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SAVAGE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SHADOW.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SHERIFF.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SHOGUN.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SNOWBALL.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SPARTACU.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SPECTRUM.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SPEED.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\STALKER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\STINGRAY.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\STRIKER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SUNDOWN.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\SWAMPFOX.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\TEMPEST.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\TIGERSHA.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\TOUCHDOW.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VAMPIRE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VERTIGO.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VIGILANT.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VIKING.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VIPER.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VOODOO.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VULCAN.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\VULTURE.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\WARLOCK.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\WARLORD.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\WARRIOR.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\WILDCAT.PCM"
 	File "${SRCDIR}\cohokum\audio\speech\us\atc\WOLFPACK.PCM"

SectionEnd

Section "Additional campaigns" SectionCampaigns

	SetOutPath "$INSTDIR\common\maps\map2\Ricclcamp"

	File "${SRCDIR}\common\maps\map2\Ricclcamp\CUBA.BIN"
	File "${SRCDIR}\common\maps\map2\Ricclcamp\Base_temp.BTP"
	File "${SRCDIR}\common\maps\map2\Ricclcamp\CUBA.CHC"
	File "${SRCDIR}\common\maps\map2\Ricclcamp\FORMCOMP.DAT"
	File "${SRCDIR}\common\maps\map2\Ricclcamp\CUBA.SCR"
	File "${SRCDIR}\common\maps\map2\Ricclcamp\CUBA.SID"

	SetOutPath "$INSTDIR\common\maps\map2\Ricclcamp2"

	File "${SRCDIR}\common\maps\map2\Ricclcamp2\CUBA.BIN"
	File "${SRCDIR}\common\maps\map2\Ricclcamp2\CUBA.CHC"
	File "${SRCDIR}\common\maps\map2\Ricclcamp2\FORMCOMP.DAT"
	File "${SRCDIR}\common\maps\map2\Ricclcamp2\CUBA.SCR"
	File "${SRCDIR}\common\maps\map2\Ricclcamp2\CUBA.SID"

	SetOutPath "$INSTDIR\common\maps\map10\RicBWCamp"

	File "${SRCDIR}\common\maps\map10\RicBWCamp\LYBIA.BIN"
	File "${SRCDIR}\common\maps\map10\RicBWCamp\LYBIA.CHC"
	File "${SRCDIR}\common\maps\map10\RicBWCamp\FORMCOMP.DAT"
	File "${SRCDIR}\common\maps\map10\RicBWCamp\LYBIA.SCR"
	File "${SRCDIR}\common\maps\map10\RicBWCamp\LYBIA.SID"

SectionEnd

Section "Clear player profile" SectionPlayer

	SetOutPath "$INSTDIR"
	Delete "$INSTDIR\cohokum\playersv.bin"
	Delete "$INSTDIR\cohokum\players2.bin"
	Delete "$INSTDIR\cohokum\players.bin"

SectionEnd

Section "Clear EECH.INI" SectionINI

	SetOutPath "$INSTDIR"
	Delete "$INSTDIR\cohokum\EECH.INI"

SectionEnd

;--------------------------------
;Descriptions

	;Language strings
	LangString DESC_SectionSystem ${LANG_ENGLISH} "Install EECH ${VERSION} EXE, GWUT and help files"
	LangString DESC_SectionModels ${LANG_ENGLISH} "Install EECH ${VERSION} models and textures"
	LangString DESC_SectionSmokes ${LANG_ENGLISH} "Install EECH ${VERSION} smokes, explosions, weapon effects"
	LangString DESC_SectionDynamics ${LANG_ENGLISH} "Install EECH ${VERSION} dynamics and suspension config files"
	LangString DESC_SectionFFB ${LANG_ENGLISH} "Forcefeedback effect files. Not necessary even if you have FFB joystick"
	LangString DESC_SectionUSATC ${LANG_ENGLISH} "Install US ATC male voice pack v0.9"
	LangString DESC_SectionCampaigns ${LANG_ENGLISH} "Install campaigns Cuba Libre, Cuba Libre 2 and Border War"
	LangString DESC_SectionPlayer ${LANG_ENGLISH} "Necessary for first installation"
	LangString DESC_SectionINI ${LANG_ENGLISH} "Necessary for first installation"

	;Assign language strings to sections
	!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionSystem} $(DESC_SectionSystem)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionModels} $(DESC_SectionModels)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionSmokes} $(DESC_SectionSmokes)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionDynamics} $(DESC_SectionDynamics)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionFFB} $(DESC_SectionFFB)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionUSATC} $(DESC_SectionUSATC)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionCampaigns} $(DESC_SectionCampaigns)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionPlayer} $(DESC_SectionPlayer)
	!insertmacro MUI_DESCRIPTION_TEXT ${SectionINI} $(DESC_SectionINI)
	!insertmacro MUI_FUNCTION_DESCRIPTION_END
;--------------------------------
