// 
// 	 Enemy Engaged RAH-66 Comanche Versus KA-52 Hokum
// 	 Copyright (C) 2000 Empire Interactive (Europe) Ltd,
// 	 677 High Road, North Finchley, London N12 0DA
// 
// 	 Please see the document LICENSE.TXT for the full licence agreement
// 
// 2. LICENCE
//  2.1 	
//  	Subject to the provisions of this Agreement we now grant to you the 
//  	following rights in respect of the Source Code:
//   2.1.1 
//   	the non-exclusive right to Exploit  the Source Code and Executable 
//   	Code on any medium; and 
//   2.1.2 
//   	the non-exclusive right to create and distribute Derivative Works.
//  2.2 	
//  	Subject to the provisions of this Agreement we now grant you the
// 	following rights in respect of the Object Code:
//   2.2.1 
// 	the non-exclusive right to Exploit the Object Code on the same
// 	terms and conditions set out in clause 3, provided that any
// 	distribution is done so on the terms of this Agreement and is
// 	accompanied by the Source Code and Executable Code (as
// 	applicable).
// 
// 3. GENERAL OBLIGATIONS
//  3.1 
//  	In consideration of the licence granted in clause 2.1 you now agree:
//   3.1.1 
// 	that when you distribute the Source Code or Executable Code or
// 	any Derivative Works to Recipients you will also include the
// 	terms of this Agreement;
//   3.1.2 
// 	that when you make the Source Code, Executable Code or any
// 	Derivative Works ("Materials") available to download, you will
// 	ensure that Recipients must accept the terms of this Agreement
// 	before being allowed to download such Materials;
//   3.1.3 
// 	that by Exploiting the Source Code or Executable Code you may
// 	not impose any further restrictions on a Recipient's subsequent
// 	Exploitation of the Source Code or Executable Code other than
// 	those contained in the terms and conditions of this Agreement;
//   3.1.4 
// 	not (and not to allow any third party) to profit or make any
// 	charge for the Source Code, or Executable Code, any
// 	Exploitation of the Source Code or Executable Code, or for any
// 	Derivative Works;
//   3.1.5 
// 	not to place any restrictions on the operability of the Source 
// 	Code;
//   3.1.6 
// 	to attach prominent notices to any Derivative Works stating
// 	that you have changed the Source Code or Executable Code and to
// 	include the details anddate of such change; and
//   3.1.7 
//   	not to Exploit the Source Code or Executable Code otherwise than
// 	as expressly permitted by  this Agreement.
// 



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define FULL_TYPE_CHECKING	1

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_GUIDANCE_TYPES
{
	WEAPON_GUIDANCE_TYPE_NONE,
	WEAPON_GUIDANCE_TYPE_PASSIVE_INFRA_RED,					// fire and forget
	WEAPON_GUIDANCE_TYPE_SEMI_ACTIVE_RADAR,					// illumination source
	WEAPON_GUIDANCE_TYPE_ACTIVE_RADAR,							// fire and forget
	WEAPON_GUIDANCE_TYPE_SEMI_ACTIVE_LASER,					// illumination source
	WEAPON_GUIDANCE_TYPE_SEMI_ACTIVE_LASER_BEAM_RIDING,   // illumination source
	WEAPON_GUIDANCE_TYPE_ACTIVE_LASER,							// fire and forget
	WEAPON_GUIDANCE_TYPE_RADIO_COMMAND,							// control source
	WEAPON_GUIDANCE_TYPE_WIRE_GUIDED,   						// control source
	NUM_WEAPON_GUIDANCE_TYPES
};

#if (FULL_TYPE_CHECKING)

typedef enum WEAPON_GUIDANCE_TYPES weapon_guidance_types;

#else

typedef int weapon_guidance_types;

#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_WARHEAD_TYPES
{
	WEAPON_WARHEAD_TYPE_NONE,
	WEAPON_WARHEAD_TYPE_SMOKE_GRENADE,
	WEAPON_WARHEAD_TYPE_ILLUMINATION_FLARE,
	WEAPON_WARHEAD_TYPE_SOLID_SHOT,
	WEAPON_WARHEAD_TYPE_HIGH_EXPLOSIVE_ANTI_TANK,
	WEAPON_WARHEAD_TYPE_HIGH_EXPLOSIVE_DUAL_PURPOSE,
	WEAPON_WARHEAD_TYPE_HIGH_EXPLOSIVE,
	WEAPON_WARHEAD_TYPE_HIGH_EXPLOSIVE_ANTI_AIRCRAFT,
	WEAPON_WARHEAD_TYPE_CONVENTIONAL_MUNITIONS,
	NUM_WEAPON_WARHEAD_TYPES
};

#if (FULL_TYPE_CHECKING)

typedef enum WEAPON_WARHEAD_TYPES weapon_warhead_types;

#else

typedef int weapon_warhead_types;

#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_DECOY_TYPES
{
	WEAPON_DECOY_TYPE_NONE,
	WEAPON_DECOY_TYPE_CHAFF,
	WEAPON_DECOY_TYPE_FLARE,
	WEAPON_DECOY_TYPE_SMOKE_GRENADE,
	NUM_WEAPON_DECOY_TYPES
};

#if (FULL_TYPE_CHECKING)

typedef enum WEAPON_DECOY_TYPES weapon_decoy_types;

#else

typedef int weapon_decoy_types;

#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_KILL_CODES
{
	WEAPON_KILL_CODE_OK,
	WEAPON_KILL_CODE_EXHAUSTED,
	WEAPON_KILL_CODE_OUT_OF_BOUNDS,
	WEAPON_KILL_CODE_HIT_LAND,
	WEAPON_KILL_CODE_HIT_WATER,
	WEAPON_KILL_CODE_HIT_TARGET,
	WEAPON_KILL_CODE_OVERSHOT_TARGET,
	WEAPON_KILL_CODE_SELF_DESTRUCT,
	NUM_WEAPON_KILL_CODES
};

#if (FULL_TYPE_CHECKING)

typedef enum WEAPON_KILL_CODES weapon_kill_codes;

#else

typedef int weapon_kill_codes;

#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define WEAPON_CLASS_AIR_TO_AIR				(1 << 0)
#define WEAPON_CLASS_AIR_TO_SURFACE			(1 << 1)
#define WEAPON_CLASS_SURFACE_TO_AIR			(1 << 2)
#define WEAPON_CLASS_SURFACE_TO_SURFACE	(1 << 3)
#define WEAPON_CLASS_DECOY						(1 << 4)
#define WEAPON_CLASS_CARGO						(1 << 5)
#define WEAPON_CLASS_DEBRIS					(1 << 6)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_LAUNCH_WINGMAN_SPEECH_TYPES
{
	WEAPON_LAUNCH_WINGMAN_SPEECH_CANNON,
	WEAPON_LAUNCH_WINGMAN_SPEECH_ROCKET,
	WEAPON_LAUNCH_WINGMAN_SPEECH_MISSILE,

	NUM_WEAPON_LAUNCH_WINGMAN_SPEECH_TYPES
};

typedef enum WEAPON_LAUNCH_WINGMAN_SPEECH_TYPES weapon_launch_wingman_speech_types;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum
{
	PARACHUTE_STATUS_CLOSED,
	PARACHUTE_STATUS_OPEN1,
	PARACHUTE_STATUS_OPEN2,
	PARACHUTE_STATUS_OPEN3,
	PARACHUTE_STATUS_COLLAPSED
};

#define NUM_PARACHUTE_STATUS_BITS	(3)

enum
{
	MISSILE_PHASE1,
	MISSILE_PHASE2,
	MISSILE_PHASE3,
	MISSILE_FINAL_PHASE	
};

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct WEAPON
{
	mobile
		mob;

	float
		weapon_lifetime,
		decoy_timer;

	int
		burst_size;

	unsigned int
		kill_code			:NUM_WEAPON_KILL_CODE_BITS,
		weapon_on_ground	:NUM_WEAPON_ON_GROUND_BITS,
		parachute_status	:NUM_PARACHUTE_STATUS_BITS,
		loal_mode			:NUM_LOCK_ON_AFTER_LAUNCH_BITS,
		missile_phase		:NUM_WEAPON_MISSILE_PHASE_BITS;

	list_link
		launched_weapon_link,
		view_weapon_link;
	list_root
		task_dependent_root;
};

typedef struct WEAPON weapon;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum MUZZLE_FLASH_TYPES
{
	MUZZLE_FLASH_INVALID,
	MUZZLE_FLASH_SMALL_CALIBRE_STRAIGHT,
	MUZZLE_FLASH_SMALL_CALIBRE_FLARED,
	MUZZLE_FLASH_MEDIUM_CALIBRE_STRAIGHT,
	MUZZLE_FLASH_MEDIUM_CALIBRE_FLARED,
	MUZZLE_FLASH_LARGE_CALIBRE_STRAIGHT,
	MUZZLE_FLASH_LARGE_CALIBRE_FLARED,
	MUZZLE_FLASH_SMALL_ROCKET,
	MUZZLE_FLASH_MEDIUM_ROCKET,
	MUZZLE_FLASH_LARGE_ROCKET,
	NUM_MUZZLE_FLASH_TYPES
};

#if (FULL_TYPE_CHECKING)

typedef enum MUZZLE_FLASH_TYPES muzzle_flash_types;

#else

typedef int muzzle_flash_types;

#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct MUZZLE_FLASH_ANIMATION
{
	object_3d_index_numbers
		object_3d_index_number;

	texture_animation_indices
		texture_animation_index1,
		texture_animation_index2;

	float
		muzzle_flash_duration;
};

typedef struct MUZZLE_FLASH_ANIMATION muzzle_flash_animation;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_CONFIG_TYPES
{
	WEAPON_CONFIG_TYPE_UNARMED,

	////////////////////////////////////////////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT
	//
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AH64D_APACHE_LONGBOW
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_1,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_2,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_3,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_4,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_5,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_6,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_7,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_8,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_9,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_10,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_11,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_12,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_13,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_14,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_15,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_16,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_17,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_18,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_19,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_20,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_21,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_22,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_23,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_24,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_25,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_26,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_27,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_28,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_29,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_30,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_31,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_32,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_33,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_34,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_35,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_36,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_37,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_38,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_39,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_40,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_41,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_42,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_43,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_44,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_45,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_46,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_47,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_48,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_49,
	WEAPON_CONFIG_TYPE_AH64D_APACHE_LONGBOW_50,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_MI28N_HAVOC_B
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_1,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_2,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_3,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_4,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_5,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_6,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_7,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_8,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_9,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_10,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_11,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_12,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_13,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_14,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_15,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_16,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_17,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_18,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_19,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_20,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_21,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_22,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_23,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_24,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_25,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_26,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_27,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_28,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_29,
	WEAPON_CONFIG_TYPE_MI28N_HAVOC_B_30,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_RAH66_COMANCHE
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_1,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_2,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_3,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_4,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_5,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_6,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_7,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_8,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_9,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_10,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_11,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_12,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_13,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_14,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_15,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_16,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_17,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_18,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_19,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_20,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_21,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_22,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_23,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_24,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_25,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_26,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_27,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_28,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_29,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_30,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_31,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_32,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_33,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_34,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_35,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_36,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_37,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_38,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_39,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_40,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_41,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_42,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_43,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_44,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_45,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_46,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_47,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_48,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_49,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_50,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_51,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_52,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_53,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_54,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_55,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_56,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_57,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_58,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_59,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_60,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_61,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_62,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_63,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_64,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_65,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_66,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_67,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_68,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_69,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_70,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_71,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_72,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_73,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_74,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_75,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_76,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_77,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_78,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_79,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_80,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_81,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_82,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_83,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_84,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_85,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_86,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_87,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_88,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_89,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_90,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_91,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_92,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_93,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_94,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_95,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_96,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_97,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_98,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_99,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_100,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_101,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_102,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_103,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_104,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_105,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_106,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_107,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_108,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_109,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_110,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_111,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_112,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_113,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_114,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_115,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_116,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_117,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_118,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_119,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_120,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_121,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_122,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_123,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_124,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_125,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_126,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_127,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_128,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_129,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_130,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_131,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_132,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_133,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_134,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_135,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_136,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_137,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_138,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_139,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_140,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_141,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_142,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_143,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_144,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_145,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_146,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_147,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_148,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_149,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_150,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_151,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_152,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_153,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_154,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_155,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_156,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_157,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_158,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_159,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_160,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_161,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_162,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_163,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_164,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_165,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_166,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_167,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_168,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_169,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_170,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_171,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_172,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_173,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_174,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_175,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_176,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_177,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_178,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_179,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_180,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_181,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_182,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_183,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_184,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_185,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_186,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_187,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_188,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_189,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_190,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_191,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_192,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_193,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_194,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_195,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_196,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_197,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_198,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_199,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_200,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_201,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_202,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_203,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_204,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_205,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_206,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_207,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_208,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_209,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_210,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_211,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_212,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_213,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_214,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_215,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_216,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_217,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_218,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_219,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_220,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_221,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_222,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_223,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_224,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_225,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_226,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_227,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_228,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_229,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_230,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_231,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_232,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_233,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_234,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_235,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_236,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_237,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_238,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_239,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_240,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_241,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_242,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_243,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_244,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_245,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_246,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_247,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_248,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_249,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_250,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_251,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_252,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_253,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_254,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_255,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_256,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_257,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_258,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_259,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_260,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_261,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_262,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_263,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_264,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_265,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_266,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_267,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_268,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_269,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_270,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_271,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_272,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_273,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_274,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_275,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_276,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_277,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_278,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_279,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_280,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_281,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_282,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_283,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_284,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_285,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_286,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_287,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_288,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_289,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_290,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_291,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_292,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_293,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_294,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_295,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_296,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_297,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_298,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_299,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_300,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_301,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_302,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_303,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_304,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_305,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_306,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_307,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_308,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_309,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_310,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_311,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_312,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_313,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_314,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_315,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_316,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_317,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_318,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_319,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_320,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_321,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_322,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_323,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_324,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_325,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_326,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_327,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_328,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_329,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_330,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_331,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_332,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_333,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_334,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_335,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_336,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_337,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_338,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_339,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_340,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_341,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_342,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_343,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_344,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_345,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_346,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_347,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_348,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_349,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_350,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_351,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_352,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_353,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_354,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_355,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_356,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_357,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_358,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_359,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_360,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_361,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_362,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_363,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_364,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_365,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_366,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_367,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_368,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_369,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_370,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_371,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_372,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_373,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_374,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_375,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_376,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_377,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_378,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_379,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_380,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_381,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_382,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_383,
	WEAPON_CONFIG_TYPE_RAH66_COMANCHE_384,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_KA52_HOKUM_B
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_1,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_2,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_3,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_4,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_5,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_6,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_7,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_8,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_9,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_10,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_11,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_12,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_13,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_14,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_15,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_16,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_17,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_18,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_19,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_20,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_21,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_22,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_23,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_24,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_25,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_26,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_27,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_28,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_29,
	WEAPON_CONFIG_TYPE_KA52_HOKUM_B_30,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_UH60_BLACK_HAWK
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_1,
////Moje 030525 Start
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_2,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_3,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_4,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_5,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_6,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_7,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_8,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_9,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_10,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_11,
	WEAPON_CONFIG_TYPE_UH60_BLACK_HAWK_12,
////Moje 030525 End
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_MI24D_HIND
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_MI24D_HIND_1,
////Moje 030613 start
	WEAPON_CONFIG_TYPE_MI24D_HIND_2,
	WEAPON_CONFIG_TYPE_MI24D_HIND_3,
	WEAPON_CONFIG_TYPE_MI24D_HIND_4,
	WEAPON_CONFIG_TYPE_MI24D_HIND_5,
	WEAPON_CONFIG_TYPE_MI24D_HIND_6,
	WEAPON_CONFIG_TYPE_MI24D_HIND_7,
	WEAPON_CONFIG_TYPE_MI24D_HIND_8,
	WEAPON_CONFIG_TYPE_MI24D_HIND_9,
	WEAPON_CONFIG_TYPE_MI24D_HIND_10,
	WEAPON_CONFIG_TYPE_MI24D_HIND_11,
	WEAPON_CONFIG_TYPE_MI24D_HIND_12,
	WEAPON_CONFIG_TYPE_MI24D_HIND_13,
	WEAPON_CONFIG_TYPE_MI24D_HIND_14,
	WEAPON_CONFIG_TYPE_MI24D_HIND_15,
	WEAPON_CONFIG_TYPE_MI24D_HIND_16,
	WEAPON_CONFIG_TYPE_MI24D_HIND_17,
	WEAPON_CONFIG_TYPE_MI24D_HIND_18,
	WEAPON_CONFIG_TYPE_MI24D_HIND_19,
	WEAPON_CONFIG_TYPE_MI24D_HIND_20,
	WEAPON_CONFIG_TYPE_MI24D_HIND_21,
	WEAPON_CONFIG_TYPE_MI24D_HIND_22,
	WEAPON_CONFIG_TYPE_MI24D_HIND_23,
	WEAPON_CONFIG_TYPE_MI24D_HIND_24,
	WEAPON_CONFIG_TYPE_MI24D_HIND_25,
	WEAPON_CONFIG_TYPE_MI24D_HIND_26,
	WEAPON_CONFIG_TYPE_MI24D_HIND_27,
	WEAPON_CONFIG_TYPE_MI24D_HIND_28,
	WEAPON_CONFIG_TYPE_MI24D_HIND_29,
	WEAPON_CONFIG_TYPE_MI24D_HIND_30,
	WEAPON_CONFIG_TYPE_MI24D_HIND_31,
	WEAPON_CONFIG_TYPE_MI24D_HIND_32,
	WEAPON_CONFIG_TYPE_MI24D_HIND_33,
	WEAPON_CONFIG_TYPE_MI24D_HIND_34,
	WEAPON_CONFIG_TYPE_MI24D_HIND_35,
	WEAPON_CONFIG_TYPE_MI24D_HIND_36,
	WEAPON_CONFIG_TYPE_MI24D_HIND_37,
	WEAPON_CONFIG_TYPE_MI24D_HIND_38,
	WEAPON_CONFIG_TYPE_MI24D_HIND_39,
	WEAPON_CONFIG_TYPE_MI24D_HIND_40,
	WEAPON_CONFIG_TYPE_MI24D_HIND_41,
	WEAPON_CONFIG_TYPE_MI24D_HIND_42,
	WEAPON_CONFIG_TYPE_MI24D_HIND_43,
	WEAPON_CONFIG_TYPE_MI24D_HIND_44,
	WEAPON_CONFIG_TYPE_MI24D_HIND_45,
	WEAPON_CONFIG_TYPE_MI24D_HIND_46,
	WEAPON_CONFIG_TYPE_MI24D_HIND_47,
	WEAPON_CONFIG_TYPE_MI24D_HIND_48,
	WEAPON_CONFIG_TYPE_MI24D_HIND_49,
	WEAPON_CONFIG_TYPE_MI24D_HIND_50,
	WEAPON_CONFIG_TYPE_MI24D_HIND_51,
	WEAPON_CONFIG_TYPE_MI24D_HIND_52,
	WEAPON_CONFIG_TYPE_MI24D_HIND_53,
	WEAPON_CONFIG_TYPE_MI24D_HIND_54,
	WEAPON_CONFIG_TYPE_MI24D_HIND_55,
	WEAPON_CONFIG_TYPE_MI24D_HIND_56,
	WEAPON_CONFIG_TYPE_MI24D_HIND_57,
	WEAPON_CONFIG_TYPE_MI24D_HIND_58,
	WEAPON_CONFIG_TYPE_MI24D_HIND_59,
	WEAPON_CONFIG_TYPE_MI24D_HIND_60,
////moje 030613 end
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_CH46E_SEA_KNIGHT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CH46E_SEA_KNIGHT_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_KA29_HELIX_B
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_KA29_HELIX_B_1,
	WEAPON_CONFIG_TYPE_KA29_HELIX_B_2,
	WEAPON_CONFIG_TYPE_KA29_HELIX_B_3,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_CH3_JOLLY_GREEN_GIANT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CH3_JOLLY_GREEN_GIANT_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_MI17_HIP
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_MI17_HIP_1,
	WEAPON_CONFIG_TYPE_MI17_HIP_2,
	WEAPON_CONFIG_TYPE_MI17_HIP_3,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_CH47D_CHINOOK
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CH47D_CHINOOK_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_MI6_HOOK
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_MI6_HOOK_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_A10A_THUNDERBOLT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_A10A_THUNDERBOLT_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_SU25_FROGFOOT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_SU25_FROGFOOT_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_F16_FIGHTING_FALCON
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_F16_FIGHTING_FALCON_1,
	WEAPON_CONFIG_TYPE_F16_FIGHTING_FALCON_2,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_MIG29_FULCRUM
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_MIG29_FULCRUM_1,
	WEAPON_CONFIG_TYPE_MIG29_FULCRUM_2,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AV8B_HARRIER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AV8B_HARRIER_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_YAK41_FREESTYLE
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_YAK141_FREESTYLE_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_FA18_HORNET
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_FA18_HORNET_1,
	WEAPON_CONFIG_TYPE_FA18_HORNET_2,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_SU33_FLANKER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_SU33_FLANKER_1,
	WEAPON_CONFIG_TYPE_SU33_FLANKER_2,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AH64A_APACHE
	//
	////////////////////////////////////////
////Moje 030817 start Added number 3 to 32
	WEAPON_CONFIG_TYPE_AH64A_APACHE_1,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_2,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_3,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_4,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_5,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_6,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_7,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_8,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_9,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_10,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_11,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_12,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_13,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_14,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_15,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_16,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_17,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_18,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_19,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_20,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_21,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_22,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_23,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_24,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_25,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_26,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_27,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_28,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_29,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_30,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_31,
	WEAPON_CONFIG_TYPE_AH64A_APACHE_32,
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_KA50_HOKUM
	//
	////////////////////////////////////////
////Moje 030817 Added number 3 to 30
	WEAPON_CONFIG_TYPE_KA50_HOKUM_1,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_2,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_3,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_4,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_5,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_6,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_7,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_8,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_9,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_10,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_11,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_12,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_13,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_14,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_15,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_16,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_17,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_18,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_19,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_20,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_21,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_22,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_23,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_24,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_25,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_26,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_27,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_28,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_29,
	WEAPON_CONFIG_TYPE_KA50_HOKUM_30,
////Moje 030817 end
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_OH58D_KIOWA_WARRIOR
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_1,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_2,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_3,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_4,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_5,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_6,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_7,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_8,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_9,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_10,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_11,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_12,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_13,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_14,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_15,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_16,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_17,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_18,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_19,
	WEAPON_CONFIG_TYPE_OH58D_KIOWA_WARRIOR_20,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_MV22_OSPREY
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_MV22_OSPREY_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AH1T_SEACOBRA
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AH1T_SEACOBRA_1,
	WEAPON_CONFIG_TYPE_AH1T_SEACOBRA_2,
	WEAPON_CONFIG_TYPE_AH1T_SEACOBRA_3,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AH1W_SUPERCOBRA
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AH1W_SUPERCOBRA_1,
	WEAPON_CONFIG_TYPE_AH1W_SUPERCOBRA_2,
	WEAPON_CONFIG_TYPE_AH1W_SUPERCOBRA_3,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AH1Z_VIPER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AH1Z_VIPER_1,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_2,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_3,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_4,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_5,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_6,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_7,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_8,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_9,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_10,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_11,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_12,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_13,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_14,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_15,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_16,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_17,
	WEAPON_CONFIG_TYPE_AH1Z_VIPER_18,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_CH53E_SUPER_STALLION
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CH53E_SUPER_STALLION_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_C17_GLOBEMASTER_III
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_C17_GLOBEMASTER_III_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_IL76MD_CANDID_B
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_IL76MD_CANDID_B_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_C130J_HERCULES_II
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_C130J_HERCULES_II_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_AIRCRAFT_AN12B_CUB
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AN12B_CUB_1,

	////////////////////////////////////////////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLES
	//
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M1A2_ABRAMS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M1A2_ABRAMS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_T80U
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_T80U_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M2A2_BRADLEY
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M2A2_BRADLEY_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_BMP2
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_BMP2_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_BMP3
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_BMP3_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M113A2
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M113A2_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_BTR80
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_BTR80_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M1025_HUMVEE
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_BRDM2
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_BRDM2_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M109A2
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M109A2_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_2S19
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_2S19_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M270_MLRS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M270_MLRS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_BM21_GRAD
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_BM21_GRAD_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M163_VULCAN
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M163_VULCAN_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_SA19_GRISON
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_SA19_GRISON_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M1037_AVENGER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M1037_AVENGER_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M48A1_CHAPARRAL
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_M48A1_CHAPARRAL_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_SA13_GOPHER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_SA13_GOPHER_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M998_HUMVEE
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_UAZ469B
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M923A1_BIG_FOOT
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M923A1_BIG_FOOT_COVERED
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_URAL_4320
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_M978_HEMTT
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_URAL_FUEL_TANKER
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_TARAWA_CLASS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_TARAWA_CLASS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_KIEV_CLASS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_KIEV_CLASS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_OLIVER_HAZARD_PERRY_CLASS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_OLIVER_HAZARD_PERRY_CLASS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_KRIVAK_II_CLASS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_KRIVAK_II_CLASS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_LCU
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_LCAC
	//
	////////////////////////////////////////

	// unarmed

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_AIST_CLASS
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_AIST_CLASS_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_INFANTRY
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_INFANTRY_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_INFANTRY_SAM_STANDING
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_INFANTRY_SAM_STANDING_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_INFANTRY_SAM_KNEELING
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_INFANTRY_SAM_KNEELING_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_CIS_INFANTRY
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CIS_INFANTRY_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_CIS_INFANTRY_SAM_STANDING
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CIS_INFANTRY_SAM_STANDING_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_CIS_INFANTRY_SAM_KNEELING
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_CIS_INFANTRY_SAM_KNEELING_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_MANPAD
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_MANPAD_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_MACHINEGUNNER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_MACHINEGUNNER_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_RS_MANPAD
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_RS_MANPAD_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_RS_MACHINEGUNNER
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_RS_MACHINEGUNNER_1,
	
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_LIGHT_FIRING_POINT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_LIGHT_FIRING_POINT_1,
	
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_MEDIUM_FIRING_POINT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_MEDIUM_FIRING_POINT_1,
	
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_US_HEAVY_FIRING_POINT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_US_HEAVY_FIRING_POINT_1,
	
	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_RS_LIGHT_FIRING_POINT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_RS_LIGHT_FIRING_POINT_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_RS_MEDIUM_FIRING_POINT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_RS_MEDIUM_FIRING_POINT_1,

	////////////////////////////////////////
	//
	// ENTITY_SUB_TYPE_VEHICLE_RS_HEAVY_FIRING_POINT
	//
	////////////////////////////////////////

	WEAPON_CONFIG_TYPE_RS_HEAVY_FIRING_POINT_1,

	NUM_WEAPON_CONFIG_TYPES
};

#if (FULL_TYPE_CHECKING)

typedef enum WEAPON_CONFIG_TYPES weapon_config_types;

#else

typedef int weapon_config_types;

#endif

#define weapon_config_type_valid(TYPE) (((TYPE) >= 0) && ((TYPE) < NUM_WEAPON_CONFIG_TYPES))

#define WEAPON_CONFIG_TYPE_UNINITIALISED	((weapon_config_types) -1)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// don't change the order of these!
#define APACHE_LHS_INNER_PYLON	  		(0)
#define APACHE_RHS_INNER_PYLON	  		(1)
#define APACHE_LHS_OUTER_PYLON	  		(2)
#define APACHE_RHS_OUTER_PYLON	  		(3)
#define APACHE_LHS_WING_TIP_MOUNT  		(4)
#define APACHE_RHS_WING_TIP_MOUNT  		(5)
#define APACHE_CHAIN_GUN_TURRET	  		(6)
#define APACHE_CHAFF_DISPENSER	  		(7)
#define APACHE_FLARE_DISPENSER	  		(7)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define HAVOC_LHS_INNER_PYLON		 		(0)
#define HAVOC_RHS_INNER_PYLON		  		(1)
#define HAVOC_LHS_OUTER_PYLON		  		(2)
#define HAVOC_RHS_OUTER_PYLON		  		(3)
#define HAVOC_CANNON_TURRET		  		(4)
#define HAVOC_LHS_CHAFF_DISPENSER		  		(5)
#define HAVOC_LHS_FLARE_DISPENSER		  		(5)
#define HAVOC_RHS_CHAFF_DISPENSER		  		(6)
#define HAVOC_RHS_FLARE_DISPENSER		  		(6)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define COMANCHE_LHS_STUB_WING			(0)
#define COMANCHE_RHS_STUB_WING			(1)
#define COMANCHE_LHS_BAY_DOOR_INNER		(5)
#define COMANCHE_LHS_BAY_DOOR_MIDDLE	(6)
#define COMANCHE_LHS_BAY_DOOR_OUTER		(7)
#define COMANCHE_RHS_BAY_DOOR_INNER		(8)
#define COMANCHE_RHS_BAY_DOOR_MIDDLE	(9)
#define COMANCHE_RHS_BAY_DOOR_OUTER		(10)
#define COMANCHE_CANNON_TURRET			(4)
#define COMANCHE_LHS_CHAFF_DISPENSER	(2)
#define COMANCHE_RHS_CHAFF_DISPENSER	(3)
#define COMANCHE_LHS_FLARE_DISPENSER	(2)
#define COMANCHE_RHS_FLARE_DISPENSER	(3)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define HOKUM_LHS_INNER_PYLON				(1)
#define HOKUM_RHS_INNER_PYLON				(2)
#define HOKUM_LHS_OUTER_PYLON				(3)
#define HOKUM_RHS_OUTER_PYLON				(4)
#define HOKUM_CANNON_TURRET				(0)
#define HOKUM_LHS_CHAFF_DISPENSER		(5)
#define HOKUM_RHS_CHAFF_DISPENSER		(6)
#define HOKUM_LHS_FLARE_DISPENSER		(5)
#define HOKUM_RHS_FLARE_DISPENSER		(6)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////Moje 030521 Start
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define BLACKHAWK_LHS_INNER_PYLON	  		(0)
#define BLACKHAWK_RHS_INNER_PYLON	  		(1)
#define BLACKHAWK_LHS_OUTER_PYLON	  		(2)
#define BLACKHAWK_RHS_OUTER_PYLON	  		(3)
#define BLACKHAWK_LHS1_CHAFF_DISPENSER	  		(4)
#define BLACKHAWK_LHS1_FLARE_DISPENSER	  		(4)
#define BLACKHAWK_LHS2_CHAFF_DISPENSER	  		(5)
#define BLACKHAWK_LHS2_FLARE_DISPENSER	  		(5)
#define BLACKHAWK_RHS_CHAFF_DISPENSER	  		(6)
#define BLACKHAWK_RHS_FLARE_DISPENSER	  		(6)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////Moje 030521 End
////Moje 030613 start
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define HIND_LHS_INNER_PYLON	  		(0)
#define HIND_RHS_INNER_PYLON	  		(1)
#define HIND_LHS_OUTER_PYLON	  		(2)
#define HIND_RHS_OUTER_PYLON	  		(3)
#define HIND_LHS_WING_TIP_MOUNT  		(4)
#define HIND_RHS_WING_TIP_MOUNT  		(5)
#define HIND_CANNON_TURRET			(6)
#define HIND_LHS_CHAFF_DISPENSER		(7)
#define HIND_RHS_CHAFF_DISPENSER		(8)
#define HIND_LHS_FLARE_DISPENSER		(7)
#define HIND_RHS_FLARE_DISPENSER		(8)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////Moje 030613 end
////Moje 030817 start
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define AH64A_LHS_INNER_PYLON	  		(0)
#define AH64A_RHS_INNER_PYLON	  		(1)
#define AH64A_LHS_OUTER_PYLON	  		(2)
#define AH64A_RHS_OUTER_PYLON	  		(3)
#define AH64A_LHS_WING_TIP_MOUNT  		(4)
#define AH64A_RHS_WING_TIP_MOUNT  		(5)
#define AH64A_CHAIN_GUN_TURRET	  		(6)
#define AH64A_CHAFF_DISPENSER	  		(7)
#define AH64A_FLARE_DISPENSER	  		(7)

// added by GCsDriver
#define COBRA_LHS_INNER_PYLON	  		(1)
#define COBRA_RHS_INNER_PYLON	  		(2)
#define COBRA_LHS_OUTER_PYLON	  		(3)
#define COBRA_RHS_OUTER_PYLON	  		(4)
#define COBRA_CANNON_TURRET	  		(0)
#define COBRA_LHS_CHAFF_DISPENSER	  		(5)
#define COBRA_RHS_CHAFF_DISPENSER	  		(6)
#define COBRA_LHS_FLARE_DISPENSER	  		(5)
#define COBRA_RHS_FLARE_DISPENSER	  		(6)

#define VIPER_LHS_INNER_PYLON       (1)
#define VIPER_RHS_INNER_PYLON       (2)
#define VIPER_LHS_OUTER_PYLON       (3)
#define VIPER_RHS_OUTER_PYLON       (4)
#define VIPER_LHS_WING_TIP_MOUNT    (5)
#define VIPER_RHS_WING_TIP_MOUNT    (6)
#define VIPER_CANNON_TURRET         (0)
#define VIPER_LFHS_CHAFF_DISPENSER  (7)
#define VIPER_RFHS_CHAFF_DISPENSER  (8)
#define VIPER_LFHS_FLARE_DISPENSER  (7)
#define VIPER_RFHS_FLARE_DISPENSER  (8)
#define VIPER_LBHS_CHAFF_DISPENSER  (9)
#define VIPER_RBHS_CHAFF_DISPENSER  (10)
#define VIPER_LBHS_FLARE_DISPENSER  (9)
#define VIPER_RBHS_FLARE_DISPENSER  (10)

#define KIOWA_LHS_PYLON	  					(0)
#define KIOWA_RHS_PYLON	  					(1)
#define KIOWA_CHAFF_DISPENSER	  		(2)
#define KIOWA_FLARE_DISPENSER	  		(2)
  		
#define HELIX_LHS_CHAFF_DISPENSER	  		(4)
#define HELIX_RHS_CHAFF_DISPENSER	  		(5)
#define HELIX_LHS_FLARE_DISPENSER	  		(4)
#define HELIX_RHS_FLARE_DISPENSER	  		(5)

#define DEFAULT_CHAFF_DISPENSER	  		(0)
#define DEFAULT_FLARE_DISPENSER	  		(1)

#define HIP_LHS_CHAFF_DISPENSER	  		(6)
#define HIP_RHS_CHAFF_DISPENSER	  		(7)
#define HIP_LHS_FLARE_DISPENSER	  		(6)
#define HIP_RHS_FLARE_DISPENSER	  		(7)
// end GCsDriver

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define KA50_LHS_INNER_PYLON				(1)
#define KA50_RHS_INNER_PYLON				(2)
#define KA50_LHS_OUTER_PYLON				(3)
#define KA50_RHS_OUTER_PYLON				(4)
#define KA50_CANNON_TURRET				(0)
#define KA50_LHS_CHAFF_DISPENSER		(5)
#define KA50_RHS_CHAFF_DISPENSER		(6)
#define KA50_LHS_FLARE_DISPENSER		(5)
#define KA50_RHS_FLARE_DISPENSER		(6)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////Moje 030817 end

struct WEAPON_PACKAGE
{
	int
		sub_type,
		number,
		heading_depth,
		pitch_depth,
		muzzle_depth,
		make_weapon_system_ready,
		rotate,
		salvo_size;

	float
		heading_rate,
		min_heading_limit,
		max_heading_limit,
		pitch_rate,
		min_pitch_limit,
		max_pitch_limit,
		muzzle_rotate_rate,
		rotate_inhibit_velocity;

	unsigned int
		heading_share_mask,
		pitch_share_mask;

	muzzle_flash_types
		muzzle_flash_type;
};

typedef struct WEAPON_PACKAGE weapon_package;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define SHARE_WEAPON_PACKAGE1		(1 << 0)
#define SHARE_WEAPON_PACKAGE2		(1 << 1)
#define SHARE_WEAPON_PACKAGE3		(1 << 2)
#define SHARE_WEAPON_PACKAGE4		(1 << 3)
#define SHARE_WEAPON_PACKAGE5		(1 << 4)
#define SHARE_WEAPON_PACKAGE6		(1 << 5)
#define SHARE_WEAPON_PACKAGE7		(1 << 6)
#define SHARE_WEAPON_PACKAGE8		(1 << 7)
#define SHARE_WEAPON_PACKAGE9		(1 << 8)
#define SHARE_WEAPON_PACKAGE10	(1 << 9)
#define SHARE_WEAPON_PACKAGE11	(1 << 10)
#define SHARE_WEAPON_PACKAGE12	(1 << 11)
#define SHARE_WEAPON_PACKAGE13	(1 << 12)
#define SHARE_WEAPON_PACKAGE14	(1 << 13)
#define SHARE_WEAPON_PACKAGE15	(1 << 14)
#define SHARE_WEAPON_PACKAGE16	(1 << 15)
#define SHARE_WEAPON_PACKAGE17	(1 << 16)
#define SHARE_WEAPON_PACKAGE18	(1 << 17)
#define SHARE_WEAPON_PACKAGE19	(1 << 18)
#define SHARE_WEAPON_PACKAGE20	(1 << 19)
#define SHARE_WEAPON_PACKAGE21	(1 << 20)
#define SHARE_WEAPON_PACKAGE22	(1 << 21)
#define SHARE_WEAPON_PACKAGE23	(1 << 22)
#define SHARE_WEAPON_PACKAGE24	(1 << 23)
#define SHARE_WEAPON_PACKAGE25	(1 << 24)
#define SHARE_WEAPON_PACKAGE26	(1 << 25)
#define SHARE_WEAPON_PACKAGE27	(1 << 26)
#define SHARE_WEAPON_PACKAGE28	(1 << 27)
#define SHARE_WEAPON_PACKAGE29	(1 << 28)
#define SHARE_WEAPON_PACKAGE30	(1 << 29)
#define SHARE_WEAPON_PACKAGE31	(1 << 30)
#define SHARE_WEAPON_PACKAGE32	(1 << 31)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct WEAPON_PACKAGE_STATUS
{
	unsigned short int
		number,
		damaged;

	float
		weapon_system_heading,
		weapon_system_pitch,
		muzzle_flash_timer,
		rearming_timer;
};

typedef struct WEAPON_PACKAGE_STATUS weapon_package_status;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define NUM_WEAPON_PACKAGES					(32)

#define SIZE_WEAPON_PACKAGE_STATUS_ARRAY	((sizeof (weapon_package_status)) * NUM_WEAPON_PACKAGES)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define FIRE_SINGLE_WEAPON		(0.0)

#define BURST_SIZE_DONT_CARE	(0)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum WEAPON_AIMING_TYPES
{
	WEAPON_AIMING_TYPE_NONE,
	WEAPON_AIMING_TYPE_CALC_INTERCEPT_POINT,
	WEAPON_AIMING_TYPE_CALC_ANGLE_OF_PROJECTION,
	WEAPON_AIMING_TYPE_CALC_LEAD_AND_BALLISTIC,
	NUM_WEAPON_AIMING_TYPES
};

#if (FULL_TYPE_CHECKING)

typedef enum WEAPON_AIMING_TYPES weapon_aiming_types;

#else

typedef int weapon_aiming_types;

#endif

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "damage.h"

#include "wn_anim.h"

#include "wn_cllsn.h"

#include "wn_creat.h"

#include "wn_dbase.h"

#include "wn_decoy.h"

#include "wn_draw.h"

#include "wn_dstry.h"

#include "wn_float.h"

#include "wn_funcs.h"

#include "wn_int.h"

#include "wn_list.h"

#include "wn_load.h"

#include "wn_misc.h"

#include "wn_move.h"

#include "wn_msgs.h"

#include "wn_pack.h"

#include "wn_selct.h"

#include "wn_spch.h"

#include "wn_str.h"

#include "wn_tgt.h"

#include "wn_updt.h"

#include "wn_vec3d.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

extern void load_local_entity_weapon_config (entity *en);

extern int get_local_entity_weapon_available (entity *launcher, entity_sub_types weapon_sub_type);

extern void detach_local_entity_weapon (entity *launcher, entity_sub_types weapon_sub_type, int burst_size, viewpoint *vp);

extern void update_entity_weapon_systems (entity *source);

extern void animate_and_draw_entity_muzzle_flash_effect (entity *en);

extern void update_entity_weapon_system_weapon_and_target_vectors (entity *launcher);

extern int get_local_entity_selected_weapon_to_target_offsets (entity *launcher, float *heading_offset, float *pitch_offset);

extern int get_local_entity_selected_weapon_viewpoint (entity *launcher, viewpoint *vp);

extern void get_target_intercept_point (entity *source, entity *target, entity_sub_types weapon_sub_type, vec3d *intercept_point);

extern int get_local_entity_weapon_ammunition_available (entity *launcher);

extern int get_local_entity_weapon_salvo_size (entity *launcher, entity_sub_types weapon_sub_type);

extern void suppress_ineffective_ship_weapons (entity *source, entity *target);

extern void create_weapon_launched_sound_effects (entity *launcher, entity_sub_types weapon_sub_type);

extern int guidance_type_can_use_point_lock(weapon_guidance_types type);

extern unsigned get_number_of_pods_firing(entity* launcher, entity_sub_types weapon_type);

extern int get_lead_and_ballistic_intercept_point_and_angle_of_projection (vec3d *pitch_device_position,entity_sub_types wpn_type,float parent_velocity,
		entity *source,entity *target,vec3d *intercept_point,float *angle_of_projection,float *time_of_flight);

extern int check_guided_missile_type_alive (entity *en);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#undef FULL_TYPE_CHECKING

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
